### ISSUE TITLE
Suggestion: find all snapshots that contain a specific file/folder

### ISSUE THREAD

**Issue by Ithilion** [gilbertchen/duplicacy#106]
Let's say i want to fully remove a specific file (or folder) from the backup, i would use a "find" command to list all snapshots containing it and purge them. Does it make sense? If there is a better way to implement this (or if a way is already implemented) ignore this.

**Comment by gilbertchen** [comment]
If it is a file, you can run the history command to show revisions that have that file and then prune those revisions.  The history command does not work on a folder, but I guess you can run it multiple times, one for each file, until no files under the folder can be found.
