### ISSUE TITLE
Restoring is slow from gdrive on version 2.0.6 gui

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#107]
Here is a link with a screenshot:
https://drive.google.com/drive/folders/0B4p7jBq4sl5aUUJBcGllbHpYZlU?usp=sharing

You can see there that the backup was started at 15:44. it has ended at around 17:00, maybe even sooner for about 50 GB of data. (That's faster than arq, nice :) ), and then i started the download/restore. 
Now it's 22:00 and the restore still isn't finished.
No system resources are used, except from time to time (35 GB restored), but nothing much.

The "running duplicacy -background -log restore -r 1" screen is AlwaysOnTop, which is annoying (it's even in front of the task manager!)

**Comment by TheBestPessimist** [comment]
At the same link is also the log

**Comment by TheBestPessimist** [comment]
Hello, i updated the link with the right read permissions --sorry about that

**Comment by TheBestPessimist** [comment]
Looking at the logs (in the .duplicacy folder -- in the gui version that path should be changed, or made hidden and not synced), i see that there are logs only for backups, and not for restores. Is this correct? can i give you any restore logs?

**Comment by gilbertchen** [comment]
Can you try using 2 threads to see if it makes a difference?  I'll run some tests myself.

Yes, restore logs aren't saved under the .duplicacy/logs folder.

**Comment by TheBestPessimist** [comment]
i cannot select in the gui the number of threads, from what i could see.

**Comment by TheBestPessimist** [comment]
Also, i have started another restore this morning, and now it still isn't finished (but it's almost there, just 1 more GB out of 52).

**Comment by gilbertchen** [comment]
My bad.  In the GUI version, restore doesn't take the number of threads specified on the backup page so it always uses only one thread.  That was probably why it was so slow for you.  Did you use multiple threads for the backup?

You can run the CLI version and specify the number of threads:
```
cd /path/to/restore
duplicacy restore -r 1 -threads 4
```

In my tests the restore speed is between 1-2MBs with one thread, but can reach 7MB/s with 4 threads.  This is on purely random data and for actual files it may be 50% faster.

I'll make a change in version 2.0.7 to force the restore process to take the number of threads.

**Comment by TheBestPessimist** [comment]
For the upload i just used 64 threads. This saturated at times my upload speeds (i have 50 mega bytes per second upload). 
In download however, since it used only a single thread, the speed was most of the time less than 1MBPS.

**Comment by TheBestPessimist** [comment]
Closing this since it is related to rate limiting, solved in another pull request
