### ISSUE TITLE
Can not build from git because of Azure

### ISSUE THREAD

**Issue by pbtrung** [gilbertchen/duplicacy#108]
After the commit 315dfff7d6b285242b12bc061e5af13b40c77cd8, I got the following errors when trying to build from git:

storage.clients[threadIndex].GetBlob undefined (type *"github.com/gilbertchen/azure-sdk-for-go/storage".BlobStorageClient has no field or method GetBlob)
storage.clients[threadIndex].CreateBlockBlobFromReader undefined (type *"github.com/gilbertchen/azure-sdk-for-go/storage".BlobStorageClient has no field or method CreateBlockBlobFromReader)

Thanks.

**Comment by gilbertchen** [comment]
Sorry for breaking the build. I updated gilbertchen/azure-sdk-go to bring it in sync with the origin, but didn't realized that the API has changed.

The latest commit should fix the issue.

**Comment by pbtrung** [comment]
Thanks for the quick fix. `duplicacy` is really cool.
Best.
