### ISSUE TITLE
Remove backup from storage

### ISSUE THREAD

**Issue by stevenhorner** [gilbertchen/duplicacy#114]
How to delete a snapshot completely from my backup storage.

If I delete the .duplicacy folder how does this tell duplicacy to remove it. Basically I want to delete the repository from the backup completely, tried various purge options but can't get it to remove it.

To add more details I have initialized a repository with _duplicacy -init test b2://mybucket_
Then successfully backed up some test files to it  _duplicacy backup_  , but how can I totally remove this from my B2 storage?   

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gilbertchen** [comment]
First you can run the list command from that repository to see how many revisions it has created:
```
duplicacy list
```

And then pass the revision numbers to the prune command:
```
duplicacy prune -r 1-10 -exclusive
```

The -exclusive option will immediately delete all chunks referenced in deleted backups.  However, remember this is a dangerous option and it should only be used when there are no other backups in progress that back up to the same storage.

If you have already removed the original repository, you can recreate it under any directory and on any computer by issuing the same init command:

```
mkdir -p any/path
cd any/path
duplicacy init test b2://mybucket
duplicacy list
duplicacy prune -r 1-10 -exclusive
```

If you need to completely nuke the backup storage you can just empty the bucket from the B2 web page.

**Comment by stevenhorner** [comment]
Excellent that worked, it was missing the:
```
-exclusive
```
