### ISSUE TITLE
B2 multiple upload threading

### ISSUE THREAD

**Issue by jgadbois** [gilbertchen/duplicacy#115]
I'm getting slow upload speeds syncing to Backblaze B2.  I reached out to them to see if it was on their end and they mentioned checking to see if my client supported multiple upload threading in their client, as recommended on their integrations checklist: https://www.backblaze.com/b2/docs/integration_checklist.html

Do you know if this is implemented in duplicacy?

**Comment by stevenhorner** [comment]
It's an option on the backup command, see the guide[Guide](https://github.com/gilbertchen/duplicacy/blob/master/GUIDE.md)

```
duplicacy backup -threads 2
```
Changing the 2 to the number of upload threads.

**Comment by jgadbois** [comment]
I don't know how i missed that, thanks!
