### ISSUE TITLE
gdrive restore 503 problem

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#124]
![capture](https://user-images.githubusercontent.com/4482210/29661214-05476f88-88cc-11e7-8ae0-e47ca1e5d561.PNG)

this happened after more than 2 hours of restoring  a backup with 20 threads.

**Comment by gilbertchen** [comment]
Not sure about this one.  503 error is retried, so maybe the server returned something not parseable? Did the log show other errors before this one?

**Comment by TheBestPessimist** [comment]
There is no log for restores :( (in gui)

**Comment by TheBestPessimist** [comment]
Nothing else shown, that's why i took the screenshot

**Comment by TheBestPessimist** [comment]
In CLI at least, this is fixed for me, so i am going to close it now.
