### ISSUE TITLE
There should be an option to purge the local cache/or this should be done automatically

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#131]
storage: gdrive, cli

I have deleted the contents of the chunks folder and also the content of snapshots/mysnap.

when i do a backup everything is ok, but when i try to restore (i have a different folder which was used previously only to test restores, in which i only delete the actual restored data), i get an error that a chuck is not found. 
if a do a list, i can see that i only have 1 single backup, which is correct.

Is there a way for duplicacy to automatically clean itself if cache contents is wrong?

**Comment by gilbertchen** [comment]
After you deleted folders in Google Drive, did you go into the trash and remove everything there?  If you don't do that, Google Drive may think some files still exist which may cause weird things to Duplicacy.

**Comment by TheBestPessimist** [comment]
Nope, didnt empty the trash in gdrive.
This however was never a problem for arq, so that's why i've created this issue.

**Comment by TheBestPessimist** [comment]
After deleting all the data from gdrive and trash, and doing the restore after 10+ hours, i can confirm that no problems occured this time.

This means that gdrive doesn't update fast enough its trashed/deleted data?

**Comment by TheBestPessimist** [comment]
Closing this as we don't have any more info about the issue, as it seems google drive is itself just slow and weird when dealing with a lot of files in a short time.

Plus: `google drive file stream` is good enough for me now.
