### ISSUE TITLE
Copy Performance

### ISSUE THREAD

**Issue by jt70471** [gilbertchen/duplicacy#134]
Hi, I'm backing up to a local directory, then using COPY to copy snapshots to the backblaze b2 cloud. If I have the local and remote destinations in sync, performing a local snapshot that produces a small number of new chunks.

When I then copy the local repository snapshots using:

```
duplicacy copy -to b2
```
it would appear that duplicacy goes through each chunk and prints a message that the chunk has been copied for every chunk. I know this isn't possible, because my upload speed isn't fast enough to actually perform the copy of all chunks.

I would have expected the copy to only copy the chunks that were new in the last snapshot. I.e. List all chunks in the "-from" snapshots and all chunks in the "-to" snapshots, which would then be used to only upload the new chunks to the remote repository, which should drastically speed up COPY processing.

Is that possible or can you explain why I'm seeing COPY produce messages that it's copied each and every chunk, even when I know the "-to" location already has copies of most of the chunks?

Thanks.

**Comment by gilbertchen** [comment]
```
            if skipped {
                LOG_INFO("SNAPSHOT_COPY", "Chunk %s (%d/%d) exists in the destination", chunk.GetID(), chunkIndex, len(chunks))
            } else {
                LOG_INFO("SNAPSHOT_COPY", "Copied chunk %s (%d/%d)", chunk.GetID(), chunkIndex, len(chunks))
            }

```

It could be a bug that `skipped` isn't set correctly.  I'll take a close look.

**Comment by jt70471** [comment]
Hi, I have reviewed duplicacy_backupmanager.go and for the life of me, I don't see anywhere that the skipped flag is being set or even how it's supposed to be passed to the uploadCompletion function.

If you could give me a few hints how you think that should occur, I'm happy to try to figure it out.

Thanks

**Comment by gilbertchen** [comment]
I found out the place where the `skipped` flag should be set: https://github.com/gilbertchen/duplicacy/commit/3ae2de241e37f1b10e147a96d37ee75eba30276b
