### ISSUE TITLE
Failed to resize the initial file [path] for in-place writing

### ISSUE THREAD

**Issue by Ithilion** [gilbertchen/duplicacy#135]
I'm getting this error while trying to restore a 8 GiB Veracrypt dynamic container (it's a sparse file). Is there a solution?  
I'm using Duplicacy 2.0.7 on Windows 7 Ultimate x64 (if it's useful, the backup was made with Duplicacy 2.0.6). Both drives, backup and the one I'm restoring to, are NTFS formatted.

EDIT1: for the record, I was just able to restore a 500 MiB container, maybe the size is the issue?  
EDIT2: it seems indeed that 8 GiB is the problematic size. I've tried creating a 7.99 GiB (8191 MiB exactly) container and it restores without problem. Then made another 8 GiB one just after and it errors out on restore.
EDIT3: I've made some more tests and i found out that the error occurs on files (regardless if sparse or not) when the size is EXACTLY 8 GiB (no idea if other problematic sizes exist).
8191 MiB -> no error
8192 MiB -> error
8193 MiB -> no error

**Comment by TheBestPessimist** [comment]
This issue may be somehow related to a problem with my restore [here](https://github.com/gilbertchen/duplicacy/issues/123#issuecomment-325259305)

```
Downloading vm/Windows 10 x64 my cloud testing/564d3796-b537-73a1-4bdb-19a6768515a2.vmem
Failed to resize the initial file Z:\backup_software_test\duplicacy\4/vm/Windows 10 x64 my cloud testing/564d3796-b537-73a1-4bdb-19a6768515a2.vmem for in-place writing
```

**Comment by gilbertchen** [comment]
Can you run this command to create a all-zero file and then run the restore command to overwrite this file:

```
fsutil file createnew file_name 8589934592
```

It is apparent that this line in duplicacy_backupmanager.go gives the error:
```
                _, err = existingFile.Seek(entry.Size - 1, 0)
                if err != nil {
                    LOG_ERROR("DOWNLOAD_CREATE", "Failed to resize the initial file %s for in-place writing", fullPath)
                    return false
                }

```
I need to figure out why.

**Comment by Ithilion** [comment]
Just tried and it restored without error.

**Comment by gilbertchen** [comment]
This is a go bug that affects Windows only; I just filed an issue here: https://github.com/golang/go/issues/21681

I'll be working on a workaround today.

@Ithilion Glad Duplicacy can help.  It saved me some trouble a few times when I needed old versions of some files.  Nothing catastrophic, but what a relief to find the files in old backups...

**Comment by gilbertchen** [comment]
This is fixed by https://github.com/gilbertchen/duplicacy/commit/197d20f0e07284c9c8a35d9d0800b366d53b2f18
