### ISSUE TITLE
Could GCD backoff sleep time be wrong?

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#144]
Sorry in advance, but i don't know GO, so i looked the language reference before writing this. Please tell me if i'm wrong.

This issue references #123.

https://github.com/gilbertchen/duplicacy/blob/6f70b37d61c962fda55c8aa8204e882d07c3dba1/src/duplicacy_gcdstorage.go#L92-L96

This may be just my opinion, but sleep times between transfer retries is wrong:

In line 92: 
https://github.com/gilbertchen/duplicacy/blob/6f70b37d61c962fda55c8aa8204e882d07c3dba1/src/duplicacy_gcdstorage.go#L92
you compute ```delay``` as the backoff of the thread multiplied by some random float between 0 and 1.0.

But in line 96:
https://github.com/gilbertchen/duplicacy/blob/6f70b37d61c962fda55c8aa8204e882d07c3dba1/src/duplicacy_gcdstorage.go#L94
You don't sleep for that duration (```delay```), but for the (longer i think, since it's not divided by 10) ```backoffs[threadIndex]``` seconds.

Again, excuse me if i'm wrong. This is my first time reading GO, so maybe correct me where i missunderstood.

**Comment by TheBestPessimist** [comment]
Possibly related to this

https://github.com/gilbertchen/duplicacy/blob/6f70b37d61c962fda55c8aa8204e882d07c3dba1/src/duplicacy_gcdstorage.go#L64-L67

In the code i see that you simply use "User Rate Limit Exceeded" for 403, but in gdrive docs i see that 403 is used for more rate limits:
https://developers.google.com/drive/v3/web/handle-errors#403_daily_limit_exceeded

- 403: Daily Limit Exceeded
- 403: User Rate Limit Exceeded
- 403: Rate Limit Exceeded
- 403: Sharing Rate Limit Exceeded
- 403: The user has not granted the app {appId} {verb} access to the file {fileId}
- 403: The user does not have sufficient permissions for file {fileId}
- 403: App with id {appId} cannot be used within the authenticated user's domain

Wouldn't it help if in the message field you would put the error from google instead of the current "default" one?

**Comment by TheBestPessimist** [comment]
In a library for google, i see that they have as sleep time a maximum of 15 minutes, and they don't actually increase exponentially, but rather by a formula, so it takes more than 10 retries (1024 = 2**10) before dying:

https://github.com/google/google-http-java-client/blob/acdaeacc3c43402d795266d2ebcb584abe918961/google-http-client/src/main/java/com/google/api/client/util/ExponentialBackOff.java#L94-L95

**Comment by gilbertchen** [comment]
You're right.  It should be `delay` instead of `storage.backoffs[threadIndex]`.

I also think backoff should start from 10 seconds at least if the rate limit window is 100 seconds.

**Comment by thrnz** [comment]
A base of 10 seconds seems a bit excessive. 

A psuedocode example using the Google recommended exponential backoff method would be:

```
maximum_backoff = 32
delay = 2^storage.backoffs[threadIndex] + rand.Float32() 
If delay > maximum_backoff then delay = maximum_backoff + rand.Float32() 
```

> If the request fails, wait 1 + random_number_milliseconds seconds and retry the request.
> If the request fails, wait 2 + random_number_milliseconds seconds and retry the request.
> If the request fails, wait 4 + random_number_milliseconds seconds and retry the request.
> And so on, up to a maximum_backoff time.
> Continue waiting and retrying up to some maximum number of retries, but do not increase the wait period between retries.

https://developers.google.com/drive/v3/web/handle-errors#exponential-backoff
https://cloud.google.com/storage/docs/exponential-backoff

**Comment by TheBestPessimist** [comment]
I think there are multiple problems here:
delay shouldn't be multiplied with the rand.Float32(), because that means that the thread doesn't sleep enough (=as much as the log sais). see the following example:
```go
package main

import (
	"fmt"
	"math/rand"
)

func main() {
	var currentThreadBackoff int = 7
	var random float32 = rand.Float32()	
	fmt.Println("This is wrong: " , currentThreadBackoff, "*", random, "=", float32(currentThreadBackoff) * random )
	


	currentThreadBackoff = 128	
	fmt.Println("This is still wrong: " , currentThreadBackoff, "*", random, "=", float32(currentThreadBackoff) * random )
}
```

I have tried locally something along the lines of what @thrnz suggested: wait for a maximum of 256 seconds (which is about 4 minutes), but let it retry with the said backoff (256) for 15 times before dying.

This means that here: ```if !retry || storage.backoffs[threadIndex] >= 256 {``` i changed the limit to 512.

I also did not multiply the  backoff array value with the random float, but added to it, since that lets me actually sleep for that many seconds, and gives a little wiggle room.
Hence line ``` delay := float32(storage.backoffs[threadIndex]) * rand.Float32()``` became ``` delay := float32(storage.backoffs[threadIndex]) + rand.Float32()```

Another thing: 10 seconds 1st backoff sounds excessive to me as well, especially since you said that you were to raise the user rate limit quota (for example to 1000 from 100?) in your google app, as you stated here: https://github.com/gilbertchen/duplicacy/issues/123#issuecomment-325016052.

After more testing and playing (go is weird 😵 ), i will show you the version that gave me better results.

**Comment by gilbertchen** [comment]
There is a quota of 1000 requests over 100 seconds per user; there is also a quota of 10000 requests over 100 seconds per app.  I can only decrease the quotas.  To increase them it has to be approved by Google.

> A base of 10 seconds seems a bit excessive.

Maybe.  But I think the number of threads should be taken into account when calculating backoffs.  For instance, if you have 64 threads then the first backoff should be significantly larger than that of a single thread.

**Comment by thrnz** [comment]
> I think the number of threads should be taken into account when calculating backoffs. For instance, if you have 64 threads then the first backoff should be significantly larger than that of a single thread.

Perhaps something like a base of 0.5s per thread then? That way a reasonable 1-4 threads would still start backing off 'to spec' (at 1-2s for the first retry), whereas something large like 64 threads would back off much more aggressively. I guess that way a single user with a high thread count and higher number of API calls would have less impact on other users of the app also. Bear in mind the max backoff suggested  by Google is 32-64 seconds ([source](https://cloud.google.com/storage/docs/exponential-backoff)).

IIRC the real world Google Drive API limits are less than whats shown in the API quota dashboard. For instance a single user with their own personal API key would get throttled well before they reach 1000 requests in a 100 second period. I'd imagine there would be significant throttling with 64 transfer threads.

**Comment by TheBestPessimist** [comment]
From my tests, now google drive upload works with 18 threads, and my average speed is about 10MBPS for backup and 8MBPS for restore, which it's good enough.

Since i am also using `google drive file stream` i am not bothered as much by this.

Do you think we could close this?

**Comment by gilbertchen** [comment]
Yes, please.
