### ISSUE TITLE
Support for Windows scripts

### ISSUE THREAD

**Issue by cristihcd** [gilbertchen/duplicacy#145]
Hi,

The readme [describes](https://github.com/gilbertchen/duplicacy/blob/master/GUIDE.md#scripts) the posibility of running custom bash scripts before/after commands. Is it possible to run Windows batch files in the same manner?

I've tried modifying [runScript](https://github.com/gilbertchen/duplicacy/blob/49129110173ac90fb6e929bd4dd215a3f699a664/duplicacy/duplicacy_main.go#L150), adding a .bat extension, but in my tests it didn't work. I have very little experience so maybe I missed something obvious. It should of course add this only on windows.

Thanks!

**Comment by gilbertchen** [comment]
This is an oversight.  Should add the .bat extension to script names on Windows.

Fixed by https://github.com/gilbertchen/duplicacy/commit/d7fdb5fe7fd95519981300a4b7097ca11d82a203

**Comment by cristihcd** [comment]
I have updated and compiled duplicacy. By the way, the instructions for building are no longer included in the readme.

I put `pre-backup.bat` in the .duplicacy folder and ran a backup. There is no mention of running the script and the script does not run (it should echo something into a file).

In `.\src\github.com\gilbertchen\duplicacy`
`git log -1 --format="%H"`
`dfa61132794762cad5574a686f6691fa67136d81`

`cd .\src\github.com\gilbertchen\duplicacy\duplicacy & go build`

Thanks for taking the time to look into this.

**Comment by gilbertchen** [comment]
It should be under `.duplicacy\scripts`.

**Comment by cristihcd** [comment]
Great, thank you. I have tested it and it works.
