### ISSUE TITLE
Errors Handling

### ISSUE THREAD

**Issue by buzzzo** [gilbertchen/duplicacy#160]
I'm testing duplicacy with wasabi and sometimes the chunk's upload ends with messages like "internal errors", probably caused by wasabi .
In this cases duplicacy exit.

Is there a way to specify to continuing backup or to retry the chunks upload ?

**Comment by gilbertchen** [comment]
The s3 backend is based on the [official amazon sdk](https://github.com/aws/aws-sdk-go), which already does retry on most common http errors.  Maybe it doesn't retry on that particular error.  Do you have a log of what the error message looks like?

You can also try changing the storage url prefix from s3:// to s3c:// which uses https://github.com/goamz/goamz (which does retry too).

**Comment by buzzzo** [comment]
This is the error:

Failed to upload the chunk 12cb778c62ca8cf93a71976f14086536b65cc00fd94117485e0eae77f443907d: XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.
        status code: 400, request id: 24CB136C106B6E7C, host id: x8r1qnOIpGvu/zsd32gpzpYkI73A/6iHSqVNKq9cwLz2SzRQ8miS14aqtjStYFnq199p9ofNjSw4
error 100

**Comment by gilbertchen** [comment]
https://github.com/gilbertchen/duplicacy/commit/8808ad5c28ada2562ce6baf6504e7935a527f166 added 3 attempts when this XAmzContentSHA256Mismatch error occurs.  This is more of an experimental fix.  I couldn't reproduce the error so I'm not sure if retrying helps.

**Comment by buzzzo** [comment]
I've tried the s3c method and I'm able to complete the upload.
So in my case this backend seems to be more fail proof.

Thx

**Comment by gilbertchen** [comment]
See Danny's latest reply in this thread: https://duplicacy.com/issue?id=5162772954349568

I guess it was Wasabi's issue that may have been fixed.
