### ISSUE TITLE
Renaming snapshot id's

### ISSUE THREAD

**Issue by jt70471** [gilbertchen/duplicacy#164]
Hi, is there anything sacred about snapshot id's or can I simply rename the folder names under .duplicacy/snapshots and update my preferences file to match?

Thanks

**Comment by gilbertchen** [comment]
The snapshot id is used as the name for the subdirectory under `snapshots` on the storage.  You can rename those subdirectories and update the .duplicacy/preferences file to match.

**Comment by jt70471** [comment]
Thanks!
