### ISSUE TITLE
Linux not saving passwords

### ISSUE THREAD

**Issue by nikjft** [gilbertchen/duplicacy#166]
I initialized a new repo with a simple "duplicacy init -e my-snapshot b2://my-bucket", went through the song and dance of passwords and whatnot. When I then ran a backup, it asked for passwords again.

Using a basic Ubuntu configuration and I have gnome-keyring installed. How would I go about troubleshooting this?

**Comment by gilbertchen** [comment]
Run `duplicacy -d list` to see if it complains about any issue on getting passwords from gnome-keyring.

**Comment by flamingm0e** [comment]
I saw something similar.  I wound up putting the env variables in my zshrc.  I will remove these and do some testing if you would like.

Fedora 26, GNOME Desktop

**Comment by gilbertchen** [comment]
This is a duplicate of #103
