### ISSUE TITLE
Can the "copy" chunk comparison be accomplished O(n) in memory?

### ISSUE THREAD

**Issue by TheLeftSeat** [gilbertchen/duplicacy#172]
Hi all,

I built the latest source for the command-line executable of Duplicacy on Windows. This has, I believe, all the latest efficiencies with regard to only copying changed chunks during a _duplicacy copy_ command.

However, even if no files at all have changed in the latest un-copied revision, the copy command still takes 4.5 hours to complete on an 800 GB set of backup files using default chunk size (A total of approximately 166,000 chunks). My use case is something like this:

    Every hour:
        duplicacy backup to NAS
        duplicacy copy from NAS to portable-drive
        duplicacy copy from NAS to B2

The backup every hour usually only takes 30 seconds since few/no files have changed. However, the 4.5 hour execution time for each copy command, even when there are no new chunks to copy, makes this use case a no-go.

Questions:
1. Is every chunk comparison in a copy operation accessing the disk on both the FROM storage and the TO storage? I'm thinking so, since my portable drive blinks like mad during the chunk comparisons. If so, could this be done more quickly in memory? Just read all the chunk IDs at once into a map?
2. Is the copy chunk comparison O(n^2) in complexity? If so, can anything be done to drive it down to O(n) with maps?
3. In the meantime, I have to reduce the number of chunks to make this work for me. What chunk size would you recommend for an 800 GB backup comprised of typical documents, home photos and home videos?

And finally, I'd like to congratulate Mr. Chen and all who have worked on this project. This is utterly exceptional work, and I absolutely marvel at the solid stability of this program as it operates. It inspired me to figure out enough about Go to build the current source tonight. Very nice code! You have my admiration.

**Comment by jt70471** [comment]
Can you post a snippet of your output from the copy command? For each chunk, you should see a message that it already exists at the destination or whether it has been copied to the destination.

**Comment by TheLeftSeat** [comment]
Oh yes, it definitely does that. However, it is _comparing_ all 166,000 chunks one at a time over the network (albeit a fast gigabit network), so it takes 4.5 hours.
    
    ...
    Chunk 0c6879f334eb6811e6816ed0e9bd8111020132506ab953954de9be8b7feec36c (48317/166196) exists at the destination
    Chunk eb40c963fc2f76cc11018648e9579242189b1d7c85a8485beb89c675cd5ed3d0 (48318/166196) exists at the destination
    Chunk 8812f08e5db7f4af646a95e2fd0b6222c81cb360563cc6235db0f461807fb5d4 (48319/166196) exists at the destination
    Chunk 34dfea7a6a1e32cf42575f0be5100633ab39f7b9204426a4a3c0c58e316f7f9f (48320/166196) exists at the destination
    ...

Imagine 166,196 lines of this, taking about 4.5 hours to complete. And that's with multithreading - takes much longer without.

**Comment by gilbertchen** [comment]
I suspected that you didn't get the optimization made by @jt70471: https://github.com/gilbertchen/duplicacy/commit/72ba2dfa87131b1ecb75c25a090f66af3d059ddb

This is exactly the behavior that you would expect without his changes.  I merged this PR on Thursday (sorry it took me that long) so maybe you are still running an older version?

**Comment by TheLeftSeat** [comment]
Hi Gilbert - thanks for replying. I actually pulled the code on Friday late afternoon, and I believe I have the very latest copy of backupmanager. For example, line 1653 is:

    LOG_INFO("SNAPSHOT_COPY", "Chunk %s (%d/%d) exists at the destination", chunk.GetID(), chunkIndex, len(chunks))

Is this not the most current one? 

It's definitely not trying to _copy_ every chunk that has already been copied, but it is definitely iterating through every chunk, trying to determine if it exists at the destination, and that is what is taking 4.5 hours.

**Comment by jt70471** [comment]
It would appear that your build doesn't have the optimization, because there are two "versions" of the "exits at the destination" message. If the message ends with a period, then no round trip was made and the chunk was skipped because it was found referenced in one or more destination snapshots. If the message does not have the ending period, then the destination is checked if the chunk physically resides at the destination, which is the original behavior before optimization.

The difference in the messages was not intentional, but a happy accident because it shows whether or not the round trip was made or not. I should perhaps change the message altogether when the optimization is done, perhaps "skipped at destination" so it's clear which chunks are outright skipped vs physically found on the destination.

**Comment by jt70471** [comment]
I have submitted PR #173 to change the message when a chunk is optimized and skipped.

**Comment by TheLeftSeat** [comment]
I have the ones with and without periods. See below:

    Chunk f7cc5a8ca1c0839ff04e859f669f195a31b825bf8e54df4b1e333fb2f509bc65 (48142/166196) exists at the destination
    Chunk 1c2316eaf5fd1bb7497bd00b11b11205fa26378d22e8811d48cce57fdb6f3861 (48144/166196) exists at the destination
    Chunk 8a76696841cbef14b2667e43c9b21a7885d5f8422512cac83df9d916c82be04b (48145/166196) exists at the destination
    Chunk d3beeb82618ec726a100beed5ae3896072dac1d32bb14429f5e26909fb5a5ae6 (48147/166196) exists at the destination.
    Chunk 3f0249c4b0a05466d116f996c614225951ff84169fe9c2efac9d17467c8d2390 (48146/166196) exists at the destination
    Chunk 0a2ca65e3701f0ebfbe935f1d49b341de96f0a2055e9d1d81858409e4d020dd1 (48148/166196) exists at the destination
    Chunk 5d388b9406b49381745304f789cd5d74cc9ceeade22d72f9332c265ab16684d0 (48149/166196) exists at the destination
    Chunk f83e968223541cb0c428db9e7f161699d502f2d03565dd516708875bc4010864 (48150/166196) exists at the destination
    Chunk 9fc9bc9ecad6827cac10e40653e6199bce33c027a17618286d595ff79070cfcd (48151/166196) exists at the destination
    Chunk f45e05947b8420a9bf622dc2bb0a47d881a93899f978720c9d19d332df5b6f62 (48153/166196) exists at the destination.
    Chunk 88e93b23317d5277d924fd4431618a1b9c409b7e84781484df53ec1ef6c94040 (48154/166196) exists at the destination.
    Chunk 9d4b4cc64fae4fb148ddc4231bc2de5d849739956a71571b652d3331d2776d4b (48152/166196) exists at the destination
    Chunk b406783c6368d13f1a2d2e6d539e4e52b27ed26e2f5538ba7aa28d90fc1397ed (48155/166196) exists at the destination
    Chunk 6cf31ead2d8d5a74df7cb021e29a306e04dec6de8891acff725fc4fb763166da (48156/166196) exists at the destination
    Chunk 4ecdb317bd0070c359f6672300c049b4d0c280708be5f80c09639ece42cfdc52 (48157/166196) exists at the destination
    Chunk 30c3d9a9c7f9f36ef4c62ad41784b1f908f79c61f2cd11ffec1e860f7fd230fb (48158/166196) exists at the destination
    Chunk 59a08eeac2b5765196b94f0c72b19aa4ea6c12bc07c8720de0176334794aa626 (48159/166196) exists at the destination
    Chunk 63aba97b8818b5093b5a3c06206bf4a4b4e81ed39fff39f242be2a2116c215b4 (48160/166196) exists at the destination
    Chunk e098da5f0cdd2cc14a8b47fd0ebeafe3603f484a581e5f7bd335e502b613dcc2 (48161/166196) exists at the destination
    Chunk 17f8c8cc4c49094d8a87063df3ca485aa6d3396f7fd6fa2e0d19ba76a1ce6d7f (48162/166196) exists at the destination
    Chunk 89c171913452be9206415ab9a7fe7caa72d2f4ef8a549886c0d9167c105bd016 (48164/166196) exists at the destination.
    Chunk 7581b86a3ba8c6de675d7ffc04c6a985d409a1fcbe5230195b9e29453e3643c2 (48163/166196) exists at the destination
    Chunk 3a3205b6e9ffdb1ab1d422cb2307d8bd52fd43fdcbe05af3a110de0c646a98fd (48165/166196) exists at the destination
    Chunk 73df199ae8c9929646fed23899e58e5b7d7022a4ace2f5f70b0f84d6feed5f03 (48166/166196) exists at the destination
    Chunk f80c4829601ed8f7d025162db3743c27d7a05fce8887915eb19000cc189d1bd7 (48168/166196) exists at the destination.
    Chunk 6999bdb255815a3f380f5c63abeedc36a3ca6c9c40f6abc0c656be46bf0d130e (48169/166196) exists at the destination.
    Chunk bfcd743017ab712925ede9a0d62f1e508b34ff8687f0b1feb9c3dd65c1865ed2 (48167/166196) exists at the destination
    Chunk d96e41fb41ce446cc0cae93912e83b247998a3b1e9dafd1dac279ee1505dd263 (48170/166196) exists at the destination
    Chunk e30d4459b3e84346470e263d9683823e705f54091cc3fe7d3ff86d2bebc49167 (48171/166196) exists at the destination
    Chunk 759c4ddbc779cf31f37da222adb92dbbd62b12fe4826a3dcf3355e5fa31dce2d (48172/166196) exists at the destination
    Chunk adb43c1e7aa67223105e966341120a637986dcc52cddab970f561895d7806cd1 (48173/166196) exists at the destination
    Chunk f3fb9e14cd77af09d96e10e5a8c58d8838bd90e472e07748cffdafc50b972e3f (48174/166196) exists at the destination
    Chunk c6eb2f71e1b6a52ce159cb35e769cc2e54f106b690c0dd46c4257f1cd12a3ee6 (48175/166196) exists at the destination
    Chunk 5401f99accf81e3279808401064c856ec60e50136f8e9d346267c1b4af6a8acb (48176/166196) exists at the destination
    Chunk c2b35883eecfeb66ea9c0e4584e65cb9539271146060cd5063c42c8076ad5b9a (48177/166196) exists at the destination
    Chunk 53dcda0bc93a8ba8f88e10784d9e192610976d45238e63eac7268666f1d17644 (48178/166196) exists at the destination
    Chunk 3c05f4944dd95c4385ad9368896b5d946567ceeab14cf216f035c390d9d65d57 (48180/166196) exists at the destination.
    Chunk 568aedc93283a08bd4bba8066569963fff9d26d4ec481da1326604237ab7a799 (48179/166196) exists at the destination
    Chunk 6ee930498763e28ad64459c088bdfdf2e07352e58ce6b8627a7c639afe14b3fd (48181/166196) exists at the destination
    Chunk a07ea1f5fdc552c26c5522a140c98f2db222be2f34f5763264d416b17d59db00 (48182/166196) exists at the destination
    Chunk 88eef96388511d0e6d97ef94198bd63373e89364f75c48a88cb53b1df9645eb3 (48183/166196) exists at the destination
    Chunk 7418e1173922e713de22a6a3d6406fb7adccf5b77e9dbfc207a45439ce2763da (48184/166196) exists at the destination
    Chunk 8173380e9370574371ea4f634210516efef9408b1671511ccd564ddb72841a2c (48185/166196) exists at the destination
    Chunk 474b3eeb8e7461b658381e6459ec0137384ce797c18c340eb996d45c6983fb82 (48186/166196) exists at the destination
    Chunk 88e7810242c0eb8b4c9577960a2d588be174d8211bd703f61c99547be7d7da41 (48188/166196) exists at the destination.
    Chunk 0e06ca9a13a750f62b795f58524fa3b5f80737e1ad6e92043e8be387d34eab01 (48187/166196) exists at the destination
    Chunk 9ea1aa0810703764d13c0e3079c6a679c415b427904706ff5c72de06369f159f (48189/166196) exists at the destination

**Comment by jt70471** [comment]
Can you provide duplicacy list -a output for the "-from" and "-to" storage please?

For the messages without the period, the chunk is not found as residing in any of the destination snapshot revisions, so duplicacy attempts to upload the chunk. Before actually uploading the chunk data, duplicacy checks to see if the chunk id resides under the chunks/ directory and skips the upload if it is.

Is it just the B2 copy that is taking a long time or is the copy to your usb portable drive also taking a very long time?

**Comment by TheLeftSeat** [comment]
I wiped the previous backups and am trying again with chunk size = 512 MB to try to cut down on the high degree of comparison. I know that totally smites the deduplication, but without a quick copy command, my use case doesn't work. 

I never got to try B2 because I couldn't get the copy command where I wanted it. The portable drive took 4.5 hours when there was nothing to copy and about 10 hours to copy the whole 800+ GB the first time. That's totally understandable for the first big copy, but the nearly-0-byte deltas should go quick, and they were taking 4.5 hours. 

I'll let you know how I fare with 512 MB chunk size. I think it will be quicker because there will be 1/128 as many chunks, which I'm hoping will bring a 0-byte copy operation down to 2 minutes.

I'm curious - have you tested your changes on Windows?

**Comment by jt70471** [comment]
I am a mac only user, so the short answer is no, I did not personally test the changes on Windows, but there's nothing in the code that I saw that would be OS specific, but perhaps @gilbertchen might know of some reason why that may be the case.

The reason I asked for the listing of both from and to storage is that the optimization works by figuring out all of the chunks on the from storage using the snapshot id and revisions, then queries the destination storage for the chunks associated with the same snapshot id's. If the chunks exist, but are in a different snapshot id, then they would not be optimized in the current implementation.

If you can confirm that, I could try to rework the optimization to match all chunks on the destination that are part of *any* snapshot id.

The reason I implemented it this way is that the "copy" command, in my opinion, should make a copy of the snapshot id / revisions from source to destination.

**Comment by gilbertchen** [comment]
A chunk size of 512MB may be too large.  The default maximum chunk size is 4 times the average chunk size, which means each chunk buffer may be 2GB.  For n threads there will be (n+1) chunk buffer, so unless you have tons of memory you will run out of memory soon.

Our nightly build runs only on Linux, but I agree with @jt70471 that there is nothing in the code path that can leads to a Windows-only issue.  I also agree that the mostly likely cause in your case, if you're running the post-patch version, was that you used a different repository id on your B2 storage so @jt70471's optimization did not retrieve all the information about previous snapshots that did exist on the storage.

**Comment by jt70471** [comment]
I have submitted another optimization for copy processing. @TheLeftSeat, can you build from the latest source and let me know if you see any change in behavior for the copy optimization?

**Comment by jt70471** [comment]
This one should be able to be closed too after inclusion of PR #181.
