### ISSUE TITLE
Support regex in include/exclude patterns

### ISSUE THREAD

**Issue by tbain98** [gilbertchen/duplicacy#175]
Please support regexes in include/exclude patterns.

I know you've said you plan to do this eventually, so this issue is to 1) document that intent, and 2) request that you do it sooner rather than later.

**Comment by jt70471** [comment]
@gilbertchen, did you have an idea how you'd like to implement this? I assume you'd want existing include/exclude processing to continue to work ASIS for compatibility reasons. Perhaps a new method of providing include/exclude filters using a new file named something like includeexclude or regularexpressions, etc?

That would give people a method of migrating from old to new include/exclude processing if they chose. Another approach would be to use the existing filters file and use a prefix like re:+ and re:- for example.

I'd be happy to tackle this one if you share how you'd like to see it implemented. Thanks.

**Comment by gilbertchen** [comment]
re:+ and re:- should work.  Or maybe i: for include and e: for exclude.

We can even offer a -regex switch to the backup and restore commands to force all regex-based patterns.

I think you just need to add some regex matching code to [MatchPath](https://github.com/gilbertchen/duplicacy/blob/d1817ae5573499105f469a1d386c21012b9c528e/src/duplicacy_utils.go#L289).

**Comment by jt70471** [comment]
This can be closed after inclusion of PR #187.
