### ISSUE TITLE
Restore - skip or resume

### ISSUE THREAD

**Issue by anugupta** [gilbertchen/duplicacy#186]
Is there a way to make a restore skip over existing files or resume if there was an error?

Doing some testing with B2, and hit a download cap when testing out the restore process. Now, if I redo the restore command, I get a message that `[filename] already exists. Please specify the -overwrite option to continue`

Ideally, I'd like to resume the restore from the point where it stopped, or specify that existing files should be skipped. Is there any way of doing this?

**Comment by gilbertchen** [comment]
By default the restore command skips existing files with the same timestamps and sizes.  In your case I think the cap was reached while working on a large file, so the first backup left an incomplete file and the second backup started restoring the same file again.  The chunks that have been downloaded and stored in the incomplete file will not be downloaded again, so it is fast resuming (of course you need to specify the -overwrite option).

**Comment by anugupta** [comment]
Yes, you're right - I've misunderstood the overwrite flag, which I thought would essentially start the restore from the beginning (and leaving it out caused the restore to fail on the first file that was backed up). 

I am a bit confused by what the -overwrite flag is supposed to do, as it doesn't actually overwrite already restored files, or have I misunderstood this (again!)?

**Comment by gilbertchen** [comment]
Without the -overwrite flag, Duplicacy will refuse to restore a file if a different copy (by timestamp and size) already exists.  This is mainly to avoid accidental overwrites in the case when the latest version of a file has not been backed up and then a restore command attempts to restore to a previous version.

With the -overwrite flag, Duplicacy will overwrite an existing file with the version to be restored.  In your case, it was a partially restored file from an aborted restore, but Duplicacy couldn't tell if it was a partially restore file or a new file recently modified.  Therefore, it wouldn't overwrite it unless you specify the -overwrite flag.

**Comment by jt70471** [comment]
If using the -hash option for restore, I presume that would also restore the chunks that are different than the snapshot revision?

**Comment by gilbertchen** [comment]
Right, if a file has been modified by another program without changing the timestamp and size, then a restore with the -hash option will skip this file.  Only the -hash option will guarantee that the old version will be faithfully restored.

**Comment by anugupta** [comment]
Thanks for the explanation, I hadn't quite got my head around what was happening, and this all makes sense now.

**Comment by Fonant** [comment]
I was a bit confused too.

The restore will skip/ignore any existing files that match timestamp+size (or hash if -hash is used) and will only restore files that are missing.

However if an apparently-changed file is present then duplicacy will abort the restore with an error message, suggesting using the -overwrite option.

In the situation where you might want to retain the safety-net of not using -overwrite, there are other options:

The file might be a partially-restored file from a previous attempt: the fix in that case is simply to delete the file and run the same restore again: duplicacy will start again with that file and then carry on.

If the changed file is needed, either re-name it so it's not "in the way" or exclude it from the restore using an exclude pattern.

**Comment by fracai** [comment]
Maybe an "interactive" mode would be helpful where the restore would pause on each conflict with options to "[s]kip once, [o]verwrite once, [S]kip all, [O]verwrite all". Maybe a confirmation on the all and overwrite options? A summary could be reported at the end to indicate everything that has been handled differently.

**Comment by m-o-e** [comment]
I ran into this today.

duplicacy needs a flag that tells it to not abort when a changed file exists.
It should simply skip over them (and log the event).

Currently the restore procedure is *extremely painful* when you need
to fill in missing files from backup while leaving all existing files alone.

**Comment by dns72** [comment]
I'm having the exact same problem as m-o-e - I managed to get a partial recovery of files following a ransomware attack using shadow copy and was hoping to fill in the missing files from a Duplicacy backup. But the only way I can have it not stop constantly seems to be to specify -overwrite, which is a shame because it will waste loads of time downloading and replacing files which a) are already present anyway and b) even worse might have been modified meantime.
