### ISSUE TITLE
After init, can the default storage be changed?

### ISSUE THREAD

**Issue by anugupta** [gilbertchen/duplicacy#190]
Can a new storage location be added, set to default and the original storage location be given a new name? 

For example:

**Current state:**
`default = b2://<bucket name>`

**Desired state:**
`default = /path/to/local/folder`
`b2 = b2://<bucket name>`

**Comment by jt70471** [comment]
yes, you can rearrange the order of the storage locations in the .duplicacy/preferences file. Just make a backup copy first and make sure you get the comma's correct.

You can also change the name "default" to something else, but keep in mind that environment variables and keys in preferences use the storage name if not "default".
