### ISSUE TITLE
Unable to list snapshots for a repository created with -pref-dir

### ISSUE THREAD

**Issue by tbain98** [gilbertchen/duplicacy#192]
Using Duplicacy 2.0.9, I've done the following:
* Create a bucket in B2
* Set my B2 credentials as environment variables in the shell.
* duplicacy_linux_arm_2.0.9 init -e -c 2M -pref-dir /home/pi/duplicacy/storage-prefs/ExternalDrive ExternalDrive b2://my-bucket-name
* Rename the storage to "B2"
* Create a filters file that is appropriately filtered
* duplicacy_linux_arm_2.0.9 list -a -storage B2

I get the following output:
```
Failed to retrieve the information about the directory /home/pi/duplicacy/storage-prefs/ExternalDrive
: stat /home/pi/duplicacy/storage-prefs/ExternalDrive
: no such file or directory
```

However, the directory definitely exists:
```
# ls /home/pi/duplicacy/storage-prefs/ExternalDrive
filters  preferences
```

As described in the comments, the root cause of the behavior was that I edited the file with vi to change the path used, and vi automatically inserted a \n at the end. Since changing the contents via a text editor isn't an unreasonable thing to do and vi isn't an unreasonable tool to use, I'm requesting that the code that reads the path from this file consider only content up to (but not including) the first \n character, and that the \n and any content thereafter be ignored.

**Comment by gilbertchen** [comment]
I have no clue how this could happen.  The error `stat /home/pi/duplicacy/storage-prefs/ExternalDrive: no such file or directory` was returned by go, so if we trust go then this directory really didn't exist when the list command was running.

**Comment by tbain98** [comment]
And yet I ran Duplicacy, ran ls, ran Duplicacy, ran ls, and each gave
consistent output each time.

Moving the .duplicacy file out of the way and copying the pref-dir to
.duplicacy produced normal behavior.

The only thing that jumps to mind that might be relevant is that the
repository and the pref-dir are on different volumes (pref-dir is on the
root volume and the repository is on a Samba share). It sounds a bit like
https://github.com/gilbertchen/duplicacy/issues/82, but you fixed that
issue months ago. Could there be another rename() call hanging around
somewhere?

**Comment by tbain98** [comment]
After looking more closely at that bug, it's a similar situation, but not
at all the same symptoms. So that's probably a red herring.

**Comment by gilbertchen** [comment]
I know what happened.  Somehow the .duplicacy file has an extra newline in it, so the path becomes `/home/pi/duplicacy/storage-prefs/ExternalDrive\n`.  And that is why the error message you copied and pasted was multiple lines.

**Comment by tbain98** [comment]
OK, that makes sense. And I can explain what happened to get into that state: I edited the file with vi to change the path it pointed to, and vi always puts a newline at the end.

Given that, I'm re-purposing this story to request that any code that parses content from a .duplicacy file should read/use only the first line, ignoring any content after the first new-line character. I'll update the description accordingly.

**Comment by gilbertchen** [comment]
Fixed by https://github.com/gilbertchen/duplicacy/commit/3cf3ad06fa244c0c3a147563caa683818d433e4b.

**Comment by tbain98** [comment]
Great, thanks!
