### ISSUE TITLE
backing up multiple repositories to same storage locations

### ISSUE THREAD

**Issue by anugupta** [gilbertchen/duplicacy#193]
I'm backing up 2 separate repositories (2 WordPress sites on the same server) to 
- the same local storage location 
- the same b2 bucket

```
cd /path/to/site1/root
duplicacy init site1  ~/backups/duplicacy_root/
duplicacy add b2 site1 b2://backup-bucket-name
duplicacy backup -t 'initial backup'
duplicacy copy -to b2

cd /path/to/site2/root
duplicacy init site2  ~/backups/duplicacy_root/
duplicacy add b2 site2 b2://backup-bucket-name
duplicacy backup -t 'initial backup'
duplicacy copy -to b2
```

When doing the second copy (ie copying the second site from local storage to b2), I'm seeing a lot of these messages:

`chunk xxx skipped at destination`
`chunk xxx exists at destination`

Is this normal and part of the de-duplication (which is why I'm trying to backup both sites to the same storage).

**Comment by jt70471** [comment]
Yes, the skipped message indicates that the chunk at the source already exists at the destination, so it is not copied again. Not part of de-duplication per se, but an optimization that was implemented for the copy process.
