### ISSUE TITLE
Info to get Google drive token missing

### ISSUE THREAD

**Issue by dottoreD** [gilbertchen/duplicacy#197]
Maybe CLI version for Linux is for geeks only, which I'm not. I'd say User_Guide.md miss essential things to start it running. Anyway:
In some older archive I've found a link to https://duplicacy.com/gcd_start to get relevant token. Is this info also in some actual documentation? I missed it. Also the  information how to get access to Google Drive via "gcd".

Secondary duplicacy Init failed in: "Failed to load the Google Drive storage at gcd://drive.google.com/drive/my-drive: Path drive.google.com/drive/my-drive doesn't exist"
I've copied the link from Google drive and replaced _https_ with _gcd_ 

I'm using linux_i386_2.0.9 under Ubuntu Mint.

**Comment by gilbertchen** [comment]
The instruction for setting up the Google Drive backend is actually in README.md: https://github.com/gilbertchen/duplicacy#storages

You are very close.  The storage url should be `gcd://path/to/storage`, and you just need to create the directory `path/to/storage`.

**Comment by dottoreD** [comment]
Got it at the end

in README.md subchapters can be expanded by a click, that was not self explaining to me :)

And maybe its worth to note that only the path to storage **in** Google Drive needs to be added, not the full path
