### ISSUE TITLE
Syntax for path of the Google Drive token file

### ISSUE THREAD

**Issue by dottoreD** [gilbertchen/duplicacy#200]
My repository is not home directory and active. I run from there `~/duplicacy init test_backup gcd://backup`. Folder "backup" in google drive exists. Token file is generated and in folder `~/.duplicacy` . What is the correct path when I'm asked `Enter the path of the Google Drive token file (downloadable from https://duplicacy.com/gcd_start):`? I tried so many version without success.

And is there a special (other?) forum for this kind of questions? Or posting this here?

**Comment by gilbertchen** [comment]
`~` is your home directory but is only recognized by your shell.  You should try to find our what the real path is, by running `ls ~/.duplicacy/gcd-token.json`.  On linux it is usually `/home/username/.duplicacy/gcd-token.json`.

**Comment by dottoreD** [comment]
Sometimes it can be that easy :) Thanks, I was not aware that `~` works only for myself.
