### ISSUE TITLE
'cipher: message authentication failed' when downloading chunks from wasabi

### ISSUE THREAD

**Issue by macdanny** [gilbertchen/duplicacy#207]
'duplicacy copy -from wasabi -to local -threads 16' frequently crashes with this message:

```
2017-09-20 19:27:10.262 ERROR UPLOAD_CHUNK Failed to decrypt the chunk da7f61e4ba27912563f37d1a1849479dac940cd85e60dc5b8068528df8eb889e: cipher: message authentication failed
```

Sometimes it crashes after less than 100 chunks, sometimes it crashes after more than 1000, but it will reliably crash. It's a different chunk every time.

The same behaviour occurs with both the s3 and s3c providers. v2.0.9 is affected. So is HEAD (ae44bf722696e1a33e311ffe6729eebf23fca755). Linux and FreeBSD are both impacted.

**Comment by gilbertchen** [comment]
I was able to reproduce the bug twice, with less than 300 chunks.  Strangely enough, however, after those two successful attempts in maybe 2 runs, I couldn't reproduce it any more, even with more than 10 runs.  Can you still reliably reproduce it now?

And there is no reason this will only affect the Wasabi backend if this is a bug in the copy command.

Looking at the code, this decryption error can only happen in the chunk downloader.  The only thing that can cause it would be that the chunk buffer was reused for the next chunk to be downloaded before being released.  But this is unlikely according to my read of the relevant code path:
https://github.com/gilbertchen/duplicacy/blob/923cd0aa63247fdee1c3b3b6eb166ca712e5e00a/src/duplicacy_backupmanager.go#L1667-L1668

Therefore, I suspect this may have been an transient issue with Wasabi's servers.

**Comment by macdanny** [comment]
Yes, it is still happening.  It happened 15 minutes ago.

The longest I've been able to get it to go so far is around 5000 chunks.  It happens frequently in less than 100 chunks and almost always in less than 1000.

**Comment by macdanny** [comment]
I wrote some code to stash the chunk in a file before duplicacy tries to decrypt it. I ran the program until I got the error. Then I downloaded the same chunk from Wasabi and compared them.

About 95% of the file is the same. There's a block in the middle that disagrees. The first different byte is at offset 0x39439a and the last different one is at 0x3d06cf.  It's about 200,000 bytes that is completely garbled in the middle of a file ~11 megabytes in size.

**Comment by macdanny** [comment]
It's pretty hard for me to believe this is a Wasabi issue because if they were this unreliable no one could use them.

**Comment by gilbertchen** [comment]
Where did you stash the chunk?  Inside `func (storage *S3Storage) DownloadFile`?  Can you do the same to `func (storage *S3CStorage) DownloadFile` and then try s3c://?

**Comment by macdanny** [comment]
Another run just completed, in this case there are 3 big blocks of discrepant bytes and one small one, but still about 70% of the file is correct, including the beginning and the end.

I actually put it in chunkdownloader, after the call to DownloadFile and before the call to Decrypt.  I can try s3c, no problem, I shouldn't have to change the code at all.

**Comment by macdanny** [comment]
By the way, something that's interesting is after I added the code to write the chunk to a file, it seems like the program will run longer before it encounters this error. The one that just failed was almost 12,000 chunks in. Could still be a coincidence but that's by far the longest it's gone yet.

**Comment by macdanny** [comment]
Ran it with s3c.  about 13k discrepancy in a 2.8M file.

**Comment by gilbertchen** [comment]
What if you just use one thread?  Only the uploading part of the copy command is parallelized.  The downloading is actually sequential, although multiple goroutines are created with only one being active at a time.  In this case since the destination is a local storage, using one thread shouldn't reduce the copy speed dramatically.

**Comment by macdanny** [comment]
It actually failed almost immediately with argument "-threads 1" and I confess I find that surprising.  Fails with both s3 and s3c providers.

**Comment by macdanny** [comment]
I installed the AWS CLI and I'm running "aws s3 sync" to download everything from Wasabi. If it's a Wasabi problem this should fail.  I've only just started but so far so good.  It's downloading at 17.8 MiB/s and there's no reason in principle Duplicacy can't approach these same speeds.

**Comment by gilbertchen** [comment]
I got the same 'cipher: message authentication failed' error when I tried restore.  So it is not the copy code.  

I also found Wasabi's speeds varied a lot.  On one restore run I got 20MB/s but the other was only
 7MB/s.

**Comment by gilbertchen** [comment]
Below is a small program that can detect if a downloaded file is corrupted by comparing the hash with the file name.  I was able to generate an error on the 5th iteration:

```
[5] test2/20341729f1cc1381529001cdd411855deb7c98d6852988b877532cd23a4375c4
test2/20341729f1cc1381529001cdd411855deb7c98d6852988b877532cd23a4375c4 != test2/3f697b868f3143aa9b01100d641309b56961923df3bc9836565359bd1879496f
```

I'll contact Wasabi's technical support shortly.

```
package main

import (
    "os"
    "io"
    "fmt"
    "path"
    "bytes"
    "crypto/sha256"
    "encoding/hex"
    "math/rand"
    crypto_rand "crypto/rand"
	
    "github.com/gilbertchen/goamz/aws"
    "github.com/gilbertchen/goamz/s3"
)

func main() {
    if len(os.Args) < 5  {
        fmt.Printf("Usage: %s s3_id s3_secret bucket dir\n")
        return
    }
    auth := aws.Auth{
        AccessKey: os.Args[1],
        SecretKey: os.Args[2],
    }

    region := aws.Region { S3Endpoint:"https://s3.wasabisys.com" }

    connection := s3.New(auth, region)

    bucket := connection.Bucket(os.Args[3])
    dir := os.Args[4]

    list, err := bucket.List(dir, "", "", 1000)
    if err != nil {
        fmt.Printf("Failed to list files: %v\n", err)
        return
    }

    n := 250
    maxFileSize := 4 * 1024 * 1024 

    if len(list.Contents) < n {
        for i := 0; i < n - len(list.Contents); i++ {
            content := make([]byte, rand.Int() % maxFileSize + maxFileSize)
	    _, err = crypto_rand.Read(content)
            if err != nil {
	        fmt.Printf("Error generating random content: %v", err)
		return
	    }

	    hasher := sha256.New()
	    hasher.Write(content)
	    filename := path.Join(dir, hex.EncodeToString(hasher.Sum(nil)))

    	    options := s3.Options{}
	    err = bucket.PutReader(filename, bytes.NewReader(content), int64(len(content)), "application/duplicacy", s3.Private, options)
            if err != nil {
	        fmt.Printf("Failed to upload %s: %v\n", filename, err)
                return
            }
            fmt.Printf("Uploaded %s\n", filename)
        }

        list, err = bucket.List(dir, "", "", 1000)
        if err != nil {
            fmt.Printf("Failed to list files: %v\n", err)
            return
        }
    }

    var files []string
    for _, entry := range list.Contents {
        if len(entry.Key) > len(dir) + 10 {
            files = append(files, entry.Key)
        }
    }

    for i := 0; i < 10; i++ {
        for _, file := range files {
            fmt.Printf("[%d] %s\n", i, file)
   	    readCloser, err := bucket.GetReader(file)
	    if err != nil {
		fmt.Printf("Failed to download %s: %v\n", file, err)
                return 
	    }

            hasher := sha256.New()
            _, err = io.Copy(hasher, readCloser)
            if err != nil {
		fmt.Printf("Failed to read %s: %v\n", file, err)
                return
            }
            readCloser.Close()
            hash := path.Join(dir, hex.EncodeToString(hasher.Sum(nil)))
            if file != hash {
                fmt.Printf("%s != %s\n", file, hash)
                return
            }

        } 
    }

}


```

**Comment by macdanny** [comment]
"aws s3 sync" completed with no errors.  However when I unflattened the chunks directory and ran "duplicacy check -files" on the resulting storage I got:

```
2017-09-23 18:28:40.477 DEBUG DOWNLOAD_FETCH Fetching chunk 34ea2e2907b64a8892555d2cb096df8f72266dbd04964450cb0c2e6671ec0ef6
2017-09-23 18:28:40.505 ERROR UPLOAD_CHUNK Failed to decrypt the chunk 34ea2e2907b64a8892555d2cb096df8f72266dbd04964450cb0c2e6671ec0ef6: cipher: message authen
tication failed
goroutine 57 [running]:
runtime/debug.Stack(0xaf, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:177 +0x13d
panic(0xc98be0, 0xc431dc29c0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/gilbertchen/duplicacy/src.logf(0x2, 0xd47735, 0xc, 0xd5bfc4, 0x22, 0xc422411d40, 0x2, 0x2)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:160 +0x1bc
github.com/gilbertchen/duplicacy/src.LOG_ERROR(0xd47735, 0xc, 0xd5bfc4, 0x22, 0xc422411d40, 0x2, 0x2)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:98 +0x73
github.com/gilbertchen/duplicacy/src.(*ChunkDownloader).Download(0xc4201e4000, 0x0, 0x0, 0x269ae, 0xc42b411920, 0x20, 0x0, 0x1, 0x1)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:336 +0x547
github.com/gilbertchen/duplicacy/src.CreateChunkDownloader.func1(0xc4201e4000, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:81 +0x161
created by github.com/gilbertchen/duplicacy/src.CreateChunkDownloader
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:86 +0x23f
```

I downloaded the chunk from wasabi using the web UI and it is indeed different from the one downloaded by "aws s3 sync". So it seems this is a Wasabi problem after all.  This is evidently the conclusion you also have come to.  It's quite troubling that "aws s3 sync" didn't report any errors.

**Comment by macdanny** [comment]
Although ... https://github.com/aws/aws-cli/issues/599

**Comment by macdanny** [comment]
I guess that isn't the same issue though, since it would only impact a case where a file is updated and the chunk files are immutable.

**Comment by gilbertchen** [comment]
Wasabi's people are looking at it.  I wondered why users of other backup tools didn't report this issue before, and I thought the content type might have played a role.  So I modified the content type from "application/duplicacy" to "application/octet-stream" and still got the same error.

The corrupted response actually included a Etag field that is the MD5 of the original chunk.  However, I guess aws-cli doesn't check the Etag because according to [this](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html), the Etag isn't always the MD5 of the data.

**Comment by macdanny** [comment]
Thanks for the note about Etag. I was able to write a little script to check my downloaded chunks for corruption, which is much faster than running "duplicacy check -files".

Now my question is: is there any reason duplicacy can't use the Etag to validate the chunks it is downloading, and retry if it gets a corrupted chunk? It doesn't look like duplicacy does multi-part uploads so the Etag should be equal to the MD5 of the chunk contents, right?

**Comment by gilbertchen** [comment]
That is doable but neither aws-sdk-go nor goamz returns the response header to us, so it will involve changes internal to these two libraries.  Then there is still the problem of what if chunks are uploaded by third-party tools such as aws-cli...

**Comment by macdanny** [comment]
I had considered the fact that chunks might be uploaded by some other tool, and thought the ETag checking could be made optional for that reason.

GetObjectOutput does include the ETag field and it could be checked in S3Storage.DownloadFile, unless you mean it's not populated for some reason. I'll look into this if time allows.

**Comment by macdanny** [comment]
GetObjectOutput also includes a PartsCount field which I guess could be consulted to see whether checking the ETag _should_ match the MD5.

**Comment by gilbertchen** [comment]
You're right.  I didn't check the source code carefully.

**Comment by macdanny** [comment]
PartsCount is nil unless you are downloading an explicitly numbered part rather than the whole object. It could still be done by downloading the part(s) explicitly, but it's not ideal.

I started thinking the MD5 could be stored as metadata with the chunks. That way you wouldn't have to rely on Amazon's ETag implementation which is complicated.  But then I realized you already have metadata - the chunk ID.  Is there a downside to computing the ID of the downloaded chunk, cross-checking it against the name, and retrying if they disagree?

**Comment by gilbertchen** [comment]
The chunk ID is the hash of the plaintext data, so it can't be used to verify the encrypted file before decryption.  The reason for this is for efficiency during backup -- the file lookup can be done before compression and encryption, and if the file exists there is no need to compress and encrypt the file:
https://github.com/gilbertchen/duplicacy/blob/80742ce2ba349c74e534613dbcc2604085cc9bcd/src/duplicacy_chunkuploader.go#L115-L135

I think here you can just modifiy `func (*ChunkDownloader) Download` to retry on decryption errors or mismatched chunk ids.

**Comment by macdanny** [comment]
This issue is resolved by ff27cec.

**Comment by gilbertchen** [comment]
This issue has been mentioned on **Duplicacy Forum**. There might be relevant details there:

https://forum.duplicacy.com/t/corrupted-chunks/4895/8

**Comment by gilbertchen** [comment]
This issue has been mentioned on **Duplicacy Forum**. There might be relevant details there:

https://forum.duplicacy.com/t/download-corrupted-error-during-restore/5088/3
