### ISSUE TITLE
chunk can't be found after pruning

### ISSUE THREAD

**Issue by anugupta** [gilbertchen/duplicacy#212]
After pruning a repository on B2, I'm getting an error 

`Chunk 03caa6fd79bcd3814805234c81ddf15e14fa73b98cd866bf0a903b1a32da8144 can't be found` 

when running `duplicacy copy -to b2`

```
duplicacy check -storage b2 -fossils -id <snapshot id>
Storage set to b2:/<storage name>
Listing all chunks
All chunks referenced by snapshot <snapshot id> at revision 1 exist
Chunk 03caa6fd79bcd3814805234c81ddf15e14fa73b98cd866bf0a903b1a32da8144 can't be found
```
There is another snapshot in that storage repository that seems to be working fine. Is this related to #182 ?

Is there any way of fixing this, or is the b2 repo broken and I need to recreate it?

**Comment by gilbertchen** [comment]
Does the chunk exist on the b2 storage?

You can also take a look at the .duplicacy/logs directory.  The prune command keeps logs there and you may be able to find out when the chunk was deleted.

I don't think this is related to #182, more likely to #98, which can happen if the -exclude switch is provided to the prune command while another backup job is in progress.

**Comment by anugupta** [comment]
The chunk no longer exists on b2.

These are the relevant lines from the logs

```
prune-log-20170925-104943:Marked fossil 03caa6fd79bcd3814805234c81ddf15e14fa73b98cd866bf0a903b1a32da8144
prune-log-20170925-105138:Marked fossil 03caa6fd79bcd3814805234c81ddf15e14fa73b98cd866bf0a903b1a32da8144
prune-log-20170925-140001:Deleted fossil 03caa6fd79bcd3814805234c81ddf15e14fa73b98cd866bf0a903b1a32da8144 (collection 1)
prune-log-20170925-141953:Deleted fossil 03caa6fd79bcd3814805234c81ddf15e14fa73b98cd866bf0a903b1a32da8144 (collection 1)
```

I'm assuming there are 2 entries for each step (marking and deleting) as local storage and b2 are being pruned.

This is how I'm pruning:

```
duplicacy prune -keep 30:180 -keep 7:30 -keep 1:7 && duplicacy prune -keep 30:180 -keep 7:30 -keep 1:7 -storage b2
```
Is this a valid way of pruning local and remote? Should I just prune locally and then `duplicacy copy -to b2` instead?

What's really concerning is that this seems to have killed by b2 storage for that snapshot - which isn't ideal. Is this b2 snapshot fixable?

**Comment by gilbertchen** [comment]
Can you list revisions on both local and b2 storage:
```
duplicacy list -a
duplicacy list -a -storage b2
```

And `duplicacy check` on the local storage doesn't give any error?  Do they have the same set of revisions?

Yes, it is possible to fix the b2 storage.  If you manually delete the revision that references the missing chunk from the b2 web page and run `duplicacy prune -exclusive -exhaustive` to clean up the storage (make sure no backups are running).

**Comment by anugupta** [comment]
`duplicacy list -a`

```
Storage set to /path/to/backup/storage/root
Snapshot v-prod revision 1 created at 2017-09-15 14:24 initial -hash
Snapshot v-prod revision 8 created at 2017-09-16 16:15 cron snapshot 
Snapshot v-prod revision 14 created at 2017-09-17 16:15 cron snapshot 
Snapshot v-prod revision 24 created at 2017-09-18 16:15 cron snapshot 
Snapshot v-prod revision 25 created at 2017-09-18 20:15 cron snapshot 
```
`duplicacy list -a -storage b2`
```
Storage set to b2://backup-bucket-name
Snapshot v-prod revision 1 created at 2017-09-15 14:24 initial -hash
Snapshot v-prod revision 2 created at 2017-09-15 16:15 cron snapshot 
Snapshot v-prod revision 8 created at 2017-09-16 16:15 cron snapshot 
Snapshot v-prod revision 14 created at 2017-09-17 16:15 cron snapshot 
Snapshot v-prod revision 23 created at 2017-09-18 12:15 cron snapshot 
Snapshot v-prod revision 24 created at 2017-09-18 16:15 cron snapshot 
Snapshot v-prod revision 25 created at 2017-09-18 20:15 cron snapshot 
```

So, b2 storage has revisions 2 and 23 that have been pruned and deleted from local storage
After revision 25, both local and b2 revision lists are the same (there are another 40 revisions). 

`duplicacy check` shows all local revisions correctly

`duplicacy check -storage b2` returns this:
```
Storage set to b2://backup-bucket-name
Listing all chunks
All chunks referenced by snapshot <snapshot id> at revision 1 exist
Chunk 03caa6fd79bcd3814805234c81ddf15e14fa73b98cd866bf0a903b1a32da8144 can't be found
```

**Comment by gilbertchen** [comment]
Does the log file `prune-log-20170925-104943` or `prune-log-20170925-105138` show that the revisions 2 and 5 were deleted from the b2 storage?

It could be that the prune command was interrupted after it deleted the chunks but before it deleted the revision 2 which still references the missing chunks.  In this case I think just deleting revisions 2 and 23 should be fine.  Run `duplicacy prune -exclusive -exhaustive -dry-run -storage b2` to make sure the be storage is clean.

**Comment by anugupta** [comment]
Yes, both log files show the deletion of revisions 2 and 5

```
Deleted snapshot v-prod at revision 2
...
Deleted snapshot v-prod at revision 5
```
Running `duplicacy prune -exclusive -exhaustive -dry-run -storage b2` returned
```
Found unreferenced fossil 0a4aae43e0dc76beef212f8893621c2b7fe9b70d3041f2eb4fb142d109018d91.fsl
Found unreferenced chunk 0e43c0d5788c1340e12a3f2de244fe82be2e8ffda4ed33ea74816dd4b5544c33
Found unreferenced fossil 0fd0aa829b981660705f18302acde46eb37842dec80d6e61bddd62768a4a8eba.fsl
Found unreferenced chunk 14f01ead9e4cffe4ff9681d92dd1467b1b3ecb6056081256910205cc64592e1a
Found unreferenced chunk 16c882449ee47c412d50243b23ebdd3d46960b2057d71a1ce7b06b9e71e0a452
Found unreferenced fossil 3e30ad3994e37401a0acc533974e5989bd60674d9c29ed285ac2cd95e0141ae1.fsl
Found unreferenced chunk 8965bc94389708ea7cb9016569dc2f2b441814eec7180c91f0b18cc862039246
Found unreferenced fossil cc117d7808ed8c26f8490bf6a35376c335c9ad3098a8f5561ee54c52fa6ae6fe.fsl
Found unreferenced fossil f1fa933312744dff31c81977cb73867ae1c6fad900bebffaf8fad66b36e11633.fsl
Found unreferenced fossil fbcb85ccb3e95a7b9f67f90709b841518c5aa0086359470e8fbf9c0d23143390.fsl
```

Repeated the command without `-dry-run` and everything seems fine now.

Really appreciate your time and help with this.

One final question - is it correct to prune both storages separately, or should I prune local storage and then use `duplicacy copy` to sync the 2 storages?

**Comment by gilbertchen** [comment]
`duplicacy copy` doesn't remove snapshots and their chunks so you'll have to prune both storages separately.
