### ISSUE TITLE
Option to encrypt hashes?

### ISSUE THREAD

**Issue by fracai** [gilbertchen/duplicacy#213]
As mentioned in #207:

> The chunk ID is the hash of the plaintext data, so it can't be used to verify the encrypted file before decryption. The reason for this is for efficiency during backup -- the file lookup can be done before compression and encryption, and if the file exists there is no need to compress and encrypt the file

However unlikely in practice, doesn't this present a security vulnerability? Especially with small files a hash might leak information regarding file content. To resolve this, the hash could be encrypted as well.

A prefix could be used to identify files with encrypted names ('_' for example). Or a flag in the config file.
Storage providers that support renaming could have chunks migrated.

**Comment by gilbertchen** [comment]
> The chunk ID is the hash of the plaintext data

What I said is inaccurate.  The chunk hash is the hash of the plaintext data.  The chunk ID is derived from the chunk hash and a secret ID key.  The chunk ID is used as the name of the chunk file so it is exposed.  However, the chunk hash is never exposed.

https://github.com/gilbertchen/duplicacy/blob/master/DESIGN.md#encryption explains the encryption scheme.

**Comment by fracai** [comment]
Got it, thanks. I think I'd even previously read the design document, recognized that the hash isn't actually exposed, and then forgotten it.
