### ISSUE TITLE
Ad-hoc style backups

### ISSUE THREAD

**Issue by rawtaz** [gilbertchen/duplicacy#225]
Currently I'm using https://github.com/restic/restic for backups, and it's just great. But I'm also looking at Duplicacy as a secondary backup tool.

However, it seems to me that Duplicacy isn't tailored for "ad-hoc" backups, in the sense that I can't just initalize the remote storage and then start backing up any folder I want to it the same way I do with restic.

For example, with restic I initialize the remote storage with `restic -r sftp://HOST/backup init` (for the SFTP backend), and then I can start backing up whatever files and folders I want to using e.g. `restic -r sftp://HOST/backup backup ~/work /any/other/folder`. Restic will store a cache on my local machine, but that's it - there's no need to initialize anything locally. I can be anywhere in the filesystem and call restic telling it to back up any path I want in the filesystem.

But with Duplicacy it seems I have to decide a local folder where I want the "repository" to be stored, and then I can run backups in/for that local folder/repository using the `backup` command (which doesn't seem to take files/folders as argument), but without being able to specify which folders I want to back up this and that backup run. I suppose that I can use excludes/includes to control which files and folders under this local repository are effectively backed up, but that seems a bit messy to me. I would rather just say what data I want to back up, when I'm backing up.

So is it possible to be more "ad-hoc" with Duplicacy, specifying data to be backed up when you actually back up? Without includes/excludes, can I specify what folders to back up on each run? Can i skip initializing a local repository entirely, considering I have no need for it (I'm happy to specify the target/remote repository, as well as what to back up, as well as the password on each backup run - the latter can be dealt with in restic by environment variables or a password file)?

I suppose I can initialize the local repository at / but that's not a folder my non-privileged user have access to, so it seems rather silly to have to do that. Also, initializing one local repository for each folder I want to back up is pretty silly as well, because I usually just back up the folders I have had some changes in that day (one day it's the Economy folder, the other day it's some development projects, another day some other project, etc).

EDIT: Some may wonder why I don't just back everything up every time, and it's pretty simple; If I only changed a couple of files in one place, it makes most sense to me to 

The issue #148 seems to be a similar discussion, albeit not entirely the same one.

**Comment by dgcom** [comment]
> Some may wonder why I don't just back everything up every time, and it's pretty simple; If I only changed a couple of files in one place, it makes most sense to me to

Why would you want human to decide what changed? This is less reliable than software, which will scan backup source for changes and make sure it will cover all the changes you might have missed (because you forgot or did not realize they have changed since last backup).

You can create repository folder anywhere you want and then softlink other folder there to keep things neatly in one place. 
Although I do not like this myself and would have preferred to be able to specify source either on command line or in special text file because relying on filesystem is a bit high maintenance...

**Comment by gilbertchen** [comment]
I also want to add that passing all the information needed for a backup as command line arguments, like the repository id, the storage url, etc, can be error-prone.  A typo in the repository id or the storage url may cause the backup to be treated as an initial backup or to be uploaded to a different location.

**Comment by tbain98** [comment]
Another disadvantage of the approach in question is what happens when it comes time to restore. How do you specify what you're restoring when the time comes? If you've backed up both /foo (and all its contents) and /foo/bar, what algorithm do you use to determine which versions of each file to use when it comes time to restore? I wonder if you would be as happy with your ad hoc Restic backup system if you actually had to use it to perform a full restore (especially if you had to roll back to some point in the past, as you would have to do if you had widespread file corruption that had gone unnoticed for a while).

@dgcom My proposal in #217 would give the flexibility you said you'd prefer in your final paragraph. And @rawtaz it would allow you to eliminate the issue of needing to write content to / as a non-root user.

**Comment by rawtaz** [comment]
@dgcom Sorry, I see my text was incomplete.

The background is that the system doesn't have AES-NI in the CPU, and this combined with FDE makes it all pretty slow. For that reason I only back up what I worked on, as it's too slow to go through e.g. all of `~`. It's worked fine to do it the "ad-hoc" way though, on this system, as I don't really need the all-covering backup approach - it's fine to just back up whatever I want, and do ad-hoc restores as well when needed.

Another case is when I'm on a very slow connection, and even if I only worked on some specific files that day, other files in my `~` often changed too (but they are not relevant to back up at that time). So in this case too I want to back up only the most relevant files that changed.

It's certainly not a problem to know what changed - I know that perfectly well, so it's not a matter of _deciding_ what has changed, it's just a matter of being able to back up only what I know has changed. And my files/data is separate enough so I won't end up having backed only parts of related files, that's no issue.

Yeah, symlinks is out of the question, too messy even if I could script it. Just shouldn't be needed.

I do have other systems as well where backing up e.g. the entire `~` would be just fine, so in that case using Duplicacy as it is would probably be fine, although the matter of putting the repo at `/` is still a slight issue. I guess the most sane thing would be to put it in `~` and then do the synlink charade for files outside of `~` that you want backed up.

**Comment by rawtaz** [comment]
@gilbertchen I can only speak for myself, but the things you mention are literally never an issue for me. I always reuse the previous command, and even if I had to retype the URL to the storage it's simple enough to not make a mistake (`sftp://host/folder` - that's all). Tab completing the things you want to back up is hardly a problem either. So personally I don't think this is an issue at all.

I don't know how Duplicacy works in this regard, but if I were to try backing up to a URL that has not been initialized on the storage of that URL, restic would tell me there's no repostory there (as I haven't run `init` with it).

If it's important, one can just put the repository in an environment variable, or use a script/alias that contains the base option(s) and lets you provide just the paths to back up as arguments.

**Comment by rawtaz** [comment]
@tbain98 That is actually a good point - Since every snapshot/backup I do will contain references only to the paths I asked to back up, if I wanted to do a full restore I would have to pick out the various folders from each individual snapshot, as there's no single snapshot that contains references to all of them. I don't think that's a big issue as the number of individual folders I back up isn't that great (ten, at the very most), but sure, it's a fair point.

Regarding algorithm, I'd use the Common Sense one, along with the timestamps of the snapshots - I'd just restore the files/folders I want from the latest or some earlier snapshot, as needed. The [snapshots](https://restic.readthedocs.io/en/stable/manual.html#list-all-snapshots) command in restic shows me what paths I backed up with every snapshot, and the FUSE mount gives me access to all the snapshots and their contents as a file tree I can browse like any filesystem, so if I wanted I could just inspect files for corruption right there while I pick what to restore and from which snapshot to restore it.

Regarding my ad-hoc restic backup system, it's not a restic issue - restic lets you "full-back up" `/` or `~` just as much as Duplicacy does. Currently I'm happy that restic lets me do both types of backups, but it would be great if Duplicacy would be a little more flexibly on the ad-hoc part too :)

In the use cases I have for doing this type of backup, I don't have much of a choice though, so it is what it is :)

**Comment by rawtaz** [comment]
Thanks for everyone's input.

I understand it's a somewhat odd thing to ask, presumably more or less everyone just backs up the top-most folder covering all paths they need to back up. But having arguments to the backup command, letting you specify what to back up, seems like something you'd expect from any backup software :) It seems intentional to not have it in Duplicacy, and that's fine, I'm was just curious to see if there was a way "around" it.

At this point the closest workaround seems to be symlinks or putting the local repository at a higher level in the filesystem and using excludes/includes to mimic the ad-hoc arguments I'm asking about.

**Comment by Fonant** [comment]
Thinking laterally, could your ad-hoc backups be to an intermediate location, which is then backed up as a single collection by Duplicacy? You could then use rsync to do ad-hoc backups, copying changes to the intermediate location, knowing that Duplicacy would be backing that up later automatically. Would solve problems of missing intermediate directories, etc.

**Comment by rawtaz** [comment]
Nice thinking! Technically they could, but it's not something I'd go for. It's not important enough to warrant duplicating many GBs of data and copying it multiple times. It's just too much of a workaround :)

**Comment by dgcom** [comment]
> presumably more or less everyone just backs up the top-most folder covering all paths they need to back up

I can't speak for everyone, but I don't backup everything, on the contrary - I am picky about my backup source (that's why I am not too fond of duplicacy approach).
However - once I pick my backup sources, I do not change them often - I prefer _consistent_ backups of specified file sets.

I understand all the limitations you have - but those are relatively unique (I am familiar with several different backup solutions and strategies). In my personal opinion, duplicacy design cannot easily cater to your specific requirements without significant changes, but I'd let project owners to speak on that.

**Comment by level323** [comment]
Hit-and-run comment (I'm on the run between two jobs): 

A one-time setup of a "repository" and a very small script that takes a filespec of the file(s)/dir you want to backup should get you the functionality you're after. The script simply creates a symlink (or symlinks) to the filespecs you supplied as arguments to your script. Those symlinks are created in the repository directory (duplicacy is designed to traverse symlinks located there) by the script.

It is really not complicated, and the work required is one-time only. From that point on, you've got the functionality you seek (as far as I can tell).

FWIW I don't find @gilbertchen's design (the repository config) is at all limiting for the common use cases of duplicacy, and because the use case you desire can be achieved via the aforementioned wrapper script and because there are some benefits to @gilbertchen's current design, I'm in favour of keeping the current design (albeit with some improvements being discussed in other tickets).

**Comment by rawtaz** [comment]
@dgcom Indeed it's quite a specific use case. The system in question is old. So in that regard, this is not an issue that I would expect anyone to find a fix for.

From another perspective I am however genuinely surprised that Duplicacy's backup command doesn't allow one to specify what to back up, but that's just another design approach I suppose, so I can't say much about that :) Initially when I started this thread I just wanted to get a confirmation and know if there was a way to do that nonetheless, as I was somewhat baffled :)

Given your last paragraph, I suppose it's not straight forward to make the backup command accept a list of items to back up that specific run. I haven't been able to try it yet since it [refuses to work with my ssh-agent](https://github.com/gilbertchen/duplicacy/issues/158) for some reason, but I will try it once that's figured out. Will probably run it on my newer system as a secondary backup to complement restic, using `~` as the repository.

**Comment by rawtaz** [comment]
@level323 Curious, what are the pros with the current design, in your opinion? What is it you like about it? I feel it's somewhat restrictive in that you have to do workarounds to simply tell it what you want to back up in cases where it deviates from the normal items you back up.

Yeah, could write a script for it. It would have to manage symlinks entirely though, and by that time I can just do it myself instead of writing a script, heh. It's definitely "workaroundable", just not something I care enough to do. It's a pretty ugly solution, having to symlink your items to back up. I wonder how it works when you restore that, would Duplicacy restore the symlinked items as regular folders, or would it restore the original folders outside of the repository location and recreate the symlinks, or something else?

**Comment by fracai** [comment]
There's a rule for backups: **3,2,1**.
- **3** copies (at least)
- **2** different forms (hard drive, DVD, tape, etc) (again, at least)
- **1** off site (drive at the home of a friend or relative, or bank, or cloud) (at least)

See this article for some elaboration: https://bizwest.com/2016/04/29/three-rules-data-backup-business/

And that article touches on this, but I'll codify it with another number:
- **0** effort (automation)

We're forgetful. Sure you manually backup your data as it changes, but how long will it be until you're rushing out the door and forget? Or put it off until you get back? Or until you finish some other task? And that's when you lose data.

Backups should be automated so you don't need to remember to perform them.

Personally, the include and exclude rules are enough for me to have a single backup set that I can run on a schedule. If I decide to include additional data I can modify those rules. Having to search multiple revisions to find the one that includes the required data sounds horrible. If you want data sets like that I'd at least make different repositories for each and still run them on a regular schedule. Unchanged files won't be backed up, Duplicacy is fast, and you could still run a manual backup. All of that applies to a single monolithic backup as well. I don't think AES really applies as encryption is performed after the changes are identified.

I think I recall that top-level symlinks are treated as if they were regular folders, so they'd be restored as such.

**Comment by rawtaz** [comment]
I would also like to add "use at least two different softwares/systems to back up your data", because if there's an issue with the one/single backup software you use, you can have as many copies you want and might still be screwed.

Yes, I see your point. But in this case it's a matter of being able to run the backups at all. Better to risk forgetting something at some point, than to not have (in this case secondary) backups at all.

Searching multiple revisions is a non-issue. Listing snapshots tells me exactly what folders/files I backed up that specific time.

Using multiple repositories? Uhm, no thanks! :) This is _one_ system, why on earth would I split the contents of it, that I'm backing up, into multiple repositories? One system, one repository (per backup system, of course). That's where I don't get the Duplicacy design, 

If I understand your suggestion I would then go into each (parent) folder I have changes in, make sure there's a Duplicacy repo there, and run the backup command. So if there's three items I'd like to back up, I go to three different places and run the backup command three times. That if anything is a good recipe for forgetting something or not having the time to run it before you run out the door due to some time constraint. At least if you compare it to just firing off one backup command and tab-completing those items on the command line. Sure, you can as we concluded use a script for it, but the thought of having multiple repositories for the same system is not ideal IMO.

Trust me, having the system decrypt and encrypt the disk accesses due to FDE, at the same time that it's processing stuff with e.g. Duplicacy and as part of that encrypting and decrypting a some stuff, there's a huge difference between having AES in the CPU and not having it.

Sounds good regarding the restoring of symlinked folders :)

Anyway, I feel like it's starting to sound like I'm complaining. I don't want to complain about Duplicacy, and I again thank everyone for their opinions, input, and suggestions!

**Comment by fracai** [comment]
No, the main point is to use automation so you aren't running backups manually at all. Automation so you can't forget. Then it doesn't matter if you're using multiple repositories or a single repo. I suggested multiple repos as a way to manage multiple locations. It's not my ideal solution. I'd have one repo rooted at the top level directory and just add locations by changing the include and exclude rules. But, I wouldn't add and subtract frequently. I'd adjust the locations as I get more data sources that I care about. Then I rely on the one, frequent, automated task to backup and prune everything. If encryption really is that much of an impact for you I can see how you might need to jump through different hoops.

**Comment by rawtaz** [comment]
The entire issue is about a changing set of items to back up more or less every time you run the backup. So automating that will just be about making it as simple as possible to specify what you want to back up on a specific occasion. The simplest way to do that is obviously to just say "backup X, Y and Z" right when you run the command, like I do now in restic, and that's what I was asking about - if it's doable in Duplicacy. You cannoy automate it to the point that you just say "run my backups", and it will magically know which items you want to back up this time. So with that said, while automating is a golden goal, it's not a very applicable aspect in this specific case, if you see what I mean.

**Comment by fracai** [comment]
> You cannot automate it to the point that you just say "run my backups", and it will magically know which items you want to back up this time.

I'd say this is possible in the general case. You specify the paths you care about and then let the backups occur on a fixed, frequent schedule. Have you measured what a full scan of all the data you care about would do to your CPU? To determine what needs to be backed up Duplicacy only needs to walk the file tree and check modification dates. That's about as "magical" as you can get. I can't see how this would be that stressful.

If the encryption is indeed that stressful in your case I can understand why you want to take a more active role in the backup.

**Comment by rawtaz** [comment]
Just how would Duplicacy know which items I would like to back up at a given time, if I haven't told it? That's simply impossible by all and any logic ;)

What you say, specifying the paths I care about, is exactly what I was asking about if it's possible in a straight forward and simple way (without using exclude/include and/or symlinks).

I haven't measured it with Duplicacy in particular, because I haven't even been able to initialize a repository with it, but previous experience and the sheer number of files I have in the "complete" set of data to be backed up has me know that it's too much to run over every time.

Yes, I can set it up the usual way and simply let the backups run for quite a bit longer than on my newer systems. And yes, I can do a workaround with scripts, includes/excludes, symlinks, etc. That is all established.

**Comment by rawtaz** [comment]
Closing this issue, as the original question has definitely been answered by now :)
