### ISSUE TITLE
Suggested location for Duplicity package

### ISSUE THREAD

**Issue by eraserpencil** [gilbertchen/duplicacy#226]
I am having trouble getting the executable following the Installation instructions. I am on Mac and have go installed via HOMEBREW.

When I set variables as 
`export GOPATH=$HOME/gocode`
`export PATH=$PATH:$GOPATH/bin`
`-bash: /usr/local/opt/gettext/bin:/usr/local/opt/gettext/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin: No such file or directory`

`go get -u github.com/gilbertchen/duplicacy/...` works and I get the `duplicacy` command.

But when I `export GOPATH=$HOME/go`, or set GOPATH to any other location and run `go get -u github.com/gilbertchen/duplicacy/...`, the duplicacy command no longer works.

I can't understand why and hope for clarification. I'd ultimately prefer not having a geocode folder in Home.

**Comment by gilbertchen** [comment]
Did you figure it out?  I think that is because the [latest commit](https://github.com/gilbertchen/keyring/commit/8855f5632086e51468cd7ce91056f8da69687ef6) to github.com/gilbertchen/keyring requires Xcode installed to build from source and your default GOPATH has an older version of it.

**Comment by eraserpencil** [comment]
Yup! That helped a lot! Thanks!
