### ISSUE TITLE
Complete system backup

### ISSUE THREAD

**Issue by eraserpencil** [gilbertchen/duplicacy#227]
Finally, got init working after a day of troubleshooting my storage URL. It is as it says in the docs, wasn't sure why I struggled with it. 

I understand that only one repository is backed up, with the option of having multiple storage locations. Is there a way to have multiple repositories backing up to one location? I am intending to use duplicacy as an online computer backup solution. Is there a way to achieve that?

**Comment by fracai** [comment]
You can indeed init multiple source repositories with the same destination. Just specify the same destination each time.

**Comment by eraserpencil** [comment]
> specify the same destination each time

Does this mean in my script I have to specify the repository, back up, re-initialise a new repository, back up? Or I have multiple initialised repositories and do the back up once.

What is the best manner of cloning an entire computer. I am on Mac OSX Sierra.

**Comment by fracai** [comment]
Nope. Manually init each repository and then your script would cd to each and backup. Each repository has it's own configuration after being initialized and needs to be backed up separately.

If you're backing up an entire computer I think you'd want a single repo at the root of the hard drive. There are lots of files that you wouldn't need to backup though. System files, caches, applications, etc. You might be fine just initing the Users folder, or even just your home folder. If you go with the computer root you may have to run the backup as root or set the pref-dir to be somewhere writeable by your user.

**Comment by eraserpencil** [comment]
Thank you for the help
