### ISSUE TITLE
'Cat' command adds newline, corrupting files when saved to disk.

### ISSUE THREAD

**Issue by cbop-dev** [gilbertchen/duplicacy#229]
When using the 'cat' command to save a file from the backup storage to the local disk, the resulting file always has 1 extra byte appended to it (and the byte is an ASCII  line-feed, '0A'). I think this happens on [this line in duplicacy_snapshotmanager.go](https://github.com/gilbertchen/duplicacy/blob/a342431b3c79d366d8a97004a9a61cbd335f8957/src/duplicacy_snapshotmanager.go#L1238): `fmt.Printf("%s\n", string(content))` 

Thus, 'cat' does not just 'cat', it also prints a new line. This should not happen: running `duplicacy cat path/to/file.mp3 > saved/location/for/file.mp3`  corrupts the binary file. Thus, `cat` is unusable for saving/copying a file to another location easily without using the "restore" command. 

If you just remove the `\n` from the `Printf` command this would be fixed.

**Comment by gilbertchen** [comment]
Fixed by https://github.com/gilbertchen/duplicacy/commit/9d38b49e42ea69502620300d22ae69c774f0a85e.

**Comment by cbop-dev** [comment]
Great, thanks!
