### ISSUE TITLE
Implement multithreaded prune

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#230]
This is a feature that has come out after the discussion in issue #208.
Since Gdrive is slow for pruning, it may be useful to implement the prune operation using multiple threads, just like backup/restore.

**Comment by trunet** [comment]
will this be implemented?

**Comment by TheBestPessimist** [comment]
ofc!

it's just a matter of when will gilbert have enough time for this.

**Comment by trunet** [comment]
being a paying customer, is there any way to prioritize this? I can't run my backups daily anymore, because the pruning is taking more than a day to run (using B2 as backend). I'm running weekly and prune takes 26 hours.

**Comment by trunet** [comment]
anyway, I just raised a support ticket with them.

**Comment by TheBestPessimist** [comment]
are you running exhaustive? because even on gdrive prune wasn't _that_ slow.

**Comment by trunet** [comment]
The correct figures are:
the B2 bucket now have ~1.7 million files and ~5 TB. The backup takes ~6 hours, the prune takes ~38 hours.

**Comment by nikut** [comment]
Very much second this. I have now been running a prune against B2 for close to 24 hours and it's still going. Granted, it's my own fault for first failing to exclude some unnecessary stuff in my initial backup and then deleting those particular revisions to save on the storage cost, so the amount of chunks to be deleted now is pretty massive (a few hundred gigs). Looking at the log, the deletion is progressing at roughly one chunk every two seconds. I imagine threading would speed it up dramatically.

**Comment by gilbertchen** [comment]
This is done by PR #441.

**Comment by taoeffect** [comment]
Should this issue be closed?

**Comment by jberryman** [comment]
Does anyone have any numbers for how long a prune operation takes on their data now? Slow pruning is one reason I'm trying to move from my current backup system
