### ISSUE TITLE
Document which temporary folders are used (if any)

### ISSUE THREAD

**Issue by vb0** [gilbertchen/duplicacy#233]
I am not yet familiar enough with duplicacy but I do know that with many other tools "chunks" (to use duplicacy naming) are first written to some kind of local temp folder. This can be of great concern not only because of space and performance but because in many cases the root/system filesystem is on small flash (sometimes it can't be even replaced easily) but also because flash has a limited number of write cycles and pushing multiple TBs from a place to another going through a temporary folder will generate TBs of writes on the temp folder.

I am not concerned much with temporary snapshots/"incomplete" file or any other similar database at this point. And of course it goes without saying that for example "restore" will write the files you want restored. But what other serious temporary writes are:

backup
restore
check -files

doing?

**Comment by gilbertchen** [comment]
First, Duplicacy doesn't write chunks to a local temporary folder before uploading them.  Rather, chunks are created on the fly while splitting files in memory and uploaded as soon as they are complete.

After a chunk has been uploaded, Duplicacy may leave a copy under the `.duplicacy/cache` directory if the chunk is a part of the snapshot file.  File chunks that make up the file contents are never cached.

As the last step of a backup command, it will clean the cache such that only metadata chunks that can be used to reconstruct the last snapshot file will remain in the cache while all others will be removed.  However, if there is an indication that a prune command has been run before (by check if the `.duplicacy/fossils` directory exists which contains the fossil collection files), then the backup command will not clean the cache.

The prune command will clean the cache too, but in the slightly different way -- in addition to the metadata chunks that make up the last snapshot file, it will also keep metadata chunks that store the chunk list for every snapshot.  The latter is needed for constructing the reference graph so it can be quickly determined if a chunk is referenced by any snapshot.

All other commands such as restore, list, and check will not clean the cache.  Every time they download a snapshot from the storage they will leave the metadata chunks in the cache.  As a result, the cache size can keep growing until a backup or prune command is run.

**Comment by vb0** [comment]
This is very good, thank you. I was really concerned with going through the system SSD for a whole multi-TB backup.
