### ISSUE TITLE
'-dry-run' With 'backup' Command Isn't Working

### ISSUE THREAD

**Issue by madranet** [gilbertchen/duplicacy#239]
[EDITED for clarity, after re-reading docs.]

Is there a way to do a 'dry run' wih the backup command to list what is going to be backed up.  I've tried the `-dry-run` flag, but it doesn't work as the docs suggest.

_Docs say:_
![2017-10-19_14-05-45](https://user-images.githubusercontent.com/669658/31772158-a47b04c6-b4d6-11e7-9d7b-5dd7f8035993.png)

_But..._
![2017-10-19_14-04-32](https://user-images.githubusercontent.com/669658/31772163-aa0fc23c-b4d6-11e7-95bd-205eb61d4510.png)

[Note: the output differs from the docs. `-dry-run` isn't included as an available option]

I'm just making my initial backup now, after really struggling to understand the filter syntax [I was hoping it would work the same as my Duplicity `exclude` file syntax] and, because `-dry-run` isn't working,  the only way I can tell if my rules are correct is to sit watching the output scroll past in my terminal and hope to spot something that should [or shouldn't] be there.... which ain't very user friendly!

**Comment by gilbertchen** [comment]
PR #180 was merged after the version 2.0.9 was released so you'll have to build from the latest source for this option to work.

**Comment by madranet** [comment]
Building from source worked. Thanks.
