### ISSUE TITLE
How to deal with 503 errors when doing a backup

### ISSUE THREAD

**Issue by ksalman** [gilbertchen/duplicacy#247]
I am evaluating duplicacy and have the latest cli version, 2.0.9. During an initial upload to B2 sometimes I get 503 error.

```
URL request 'https://pod-000-1092-13.backblaze.com/b2api/v1/b2_upload_file/0032f04703d14b195bf80d14/c001_v0001092_t0058' returned status code 503
URL request 'https://pod-000-1090-05.backblaze.com/b2api/v1/b2_upload_file/0032f04703d14b195bf80d14/c001_v0001090_t0044' returned status code 503
URL request 'https://pod-000-1093-02.backblaze.com/b2api/v1/b2_upload_file/0032f04703d14b195bf80d14/c001_v0001093_t0048' returned status code 503
URL request 'https://pod-000-1092-03.backblaze.com/b2api/v1/b2_upload_file/0032f04703d14b195bf80d14/c001_v0001092_t0044' returned status code 503
URL request 'https://pod-000-1091-13.backblaze.com/b2api/v1/b2_upload_file/0032f04703d14b195bf80d14/c001_v0001091_t0008' returned status code 503
URL request 'https://pod-000-1092-04.backblaze.com/b2api/v1/b2_upload_file/0032f04703d14b195bf80d14/c001_v0001092_t0042' returned status code 503
```

What are the implications of this? Do I need to, for example, do another backup after the initial backup to make sure everything is uploaded correctly, provided I don't get 503 errors on the second run?

**Comment by gilbertchen** [comment]
B2 upload servers return 503 errors all the time.  It is by design.  Every time Duplicacy gets a 503 error it will switch to a different upload server and upload the chunk again, so there is nothing to worry about here.

**Comment by ksalman** [comment]
Oh I see, okay. Thanks for the speedy reply.

**Comment by gilbertchen** [comment]
Hubic is different but our Hubic backend also retries on 503 errors.  As long as there isn't a `Maximum number of retries reached` error it should be fine.  However, as Hubic is [closed to new users](https://www.ovh.com/fr/fin-inscription-hubic/) we may stop supporting Hubic in the near feature.
