### ISSUE TITLE
history not working on remote sftp storage

### ISSUE THREAD

**Issue by markusweb** [gilbertchen/duplicacy#25]
i want to use duplicacy to do backups on an external server via sftp.
i can setup the repository and do backups. i can restore files from sftp.
sofar it seems to work. BUT history is not working

this is with a local repository
```
/opt/duplicacy list -a
Storage set to /data/backup/data/test/backup/
Snapshot seafile revision 1 created at 2016-11-03 17:04 -hash
Snapshot seafile revision 2 created at 2016-11-03 17:04

/opt/duplicacy history eins.txt
Storage set to /data/backup/data/test/backup/
      1:               6 2016-11-03 17:04:01 622cb3371c1a08096eaac564fb59acccda1fcdbe13a9dd10b486e6463c8c2525 eins.txt
      2:              11 2016-11-03 17:04:40 464e4dd16ebd5affe3a43ca8a4a9f623e96268cf8aba762fe5cec827902a268d eins.txt*
current:              11 2016-11-03 17:04:40                                                                  eins.txt
```

now the same with a remote repository via sftp

```
/opt/duplicacy list -a
Storage set to sftp://u4711@external.server.com/data
Enter SSH password:********************
Snapshot seafile revision 1 created at 2016-11-04 10:13 -hash
Snapshot seafile revision 2 created at 2016-11-04 10:14
Snapshot seafile revision 3 created at 2016-11-04 10:14

/opt/duplicacy history eins.txt
Storage set to sftp://u4711@external.server.com/data
Enter SSH password:********************
No file eins.txt found in snapshot seafile at revision 1

/opt/duplicacy history -r 3 eins.txt
Storage set to sftp://u4711@external.server.com/data
Enter SSH password:********************
      3:              11 2016-11-04 10:14:31 f950375066d74787f31cbd8f9f91c71819357cad243fb9d4a0d9ef4fa76709e0 eins.txt
current:              16 2016-11-04 10:17:50                                                                  eins.txt*

```

so history is not working, i can retrieve info to a special revision but not all history info. the behaviour between local and sftp storage and "history" is different.

i can restore the file to a special revsion. this is working.

markus

**Comment by gilbertchen** [comment]
I think when you created revision 1 on the sftp storage you didn't have the file eins.txt in your repository.  So the issue here really is, the history command should not bail out immediately when it can't find the file in one revision.  Instead, it should continue to check all other revisions.

**Comment by vibl** [comment]
@gilbertchen, are you saying that I can only see the history of files that I have added before the first backup but not the history of files that I have added since?

**Comment by gilbertchen** [comment]
No, I meant you'll have to specify the revision numbers in which the files exist.  For example, if `file1` only exist in revision 2, 3, and 5, then the command should be:

```
duplicacy history -r 2-3 -r 5 file1
```
If you don't specify any revision number it will start at revision 1 and bail out immediately:

```
duplicacy_main history file1
No file file1 found in snapshot test at revision 1
```

I'll fix this soon.
