### ISSUE TITLE
Backing up Proxmox with Duplicacy

### ISSUE THREAD

**Issue by Lillecarl** [gilbertchen/duplicacy#250]
Hi!

I'm looking for a way to implement duplicacy as backup tool for Proxmox. With possibly a few different modes.

The mode I'm the most interested in is backing up every vm in sequence like this:

1. Write vm backup to filesystem 
2. Call duplicacy to backup the directory
3. Delete the file VM backup

This will be run for all VM's, when this is done, since there will be one snapshot per vm backup, i'd like to squash them into one. This way duplicacy will have a reasonable snapshot history.

I'm interested in this approach because it allows me not to keep all vm backups on the machine at any time, which is nice when you're on limited storage and want to maximise available storage.

Reading up on how snapshots works, it look to my eyes as it should be a trivial thing to implement (Should default to use the latest chunks if there's file collisions i guess).

Best Regards
Carl :)

**Comment by gilbertchen** [comment]
While it is not hard to merge snapshots, I feel keeping them separate by vm is a better way to manage all the snapshots.  There is a special edition of Duplicacy, named [Vertical Backup](https://www.verticalbackup.com), that runs on ESXi and uses a `vm@host` format for the repository id.  Maybe you can do the same here?

**Comment by Lillecarl** [comment]
Yeah i've bought Vertical Backup :) Sadly i wasn't happy with the free VMware, so i'm looking back at Proxmox (The reason i tried VMware was Vertical Backup).

Proxmox writes all backup files to the same directory, there's script hookability in there though. See this demo script https://github.com/Blub/pve-manager/blob/master/vzdump-hook-script.pl

Sadly their .vma format for backing up is really lame, see https://pve.proxmox.com/wiki/VMA#Things_to_be_aware_of.

The out of order writing makes sure that deduplication is broken, so what i think i have to do is extract the .vma file, remove it, start backup.

It's probably possible to create separate duplicacy repos, but idk where to get started tbh.

If you have any smart idea's i'm all ears, but i understand this is actually out of scope for duplicacy to handle :)

Best Regards
Carl :)

**Comment by gilbertchen** [comment]
Do you know if there is a detailed spec on the vma format?  Do they write vma files in fixed-size blocks?  If so, even if blocks are out-of-order, you can still get deduplication by using the block size as the chunk size.

```
# initialization
mkdir -p /path/to/repo/vm1
cd /path/to/repo/vm1 && duplicacy init vm1@host storage_url
mkdir -p /path/to/repo/vm2
cd /path/to/repo/vm2 && duplicacy init vm2@host storage_url

# backup
# extract vm1 to /path/to/repo/vm1
cd /path/to/repo/vm1 && duplicacy backup -stats
# extract vm2 to /path/to/repo/vm2
cd /path/to/repo/vm2 && duplicacy backup -stats
```

**Comment by Lillecarl** [comment]
https://git.proxmox.com/?p=pve-qemu.git;a=blob;f=vma_spec.txt Seems like blocks are 4k? Seems very small, would make duplicacy rather inefficent wouldn't it?

Thanks for taking your time! :)

Best Regards
Carl

**Comment by Lillecarl** [comment]
@gilbertchen Considering the **wonderful** .vma format with 4k blocks, if i'm backing up a 120gb .vma image it'll be 30 million chunks.

Considering each chunk is a http request to the cloud provider, that's not going to be good at all.

Do you have any smart suggestion? I have an idea, but there's probably a pitfall or hard to implement.

Grouping chunks in tar archives of x mb, and storing a json along with the tar saying which chunks it contains (only in an extreme use case like this) and store them grouped, this way we can deduplicate on 4k but store on 4m.

If there are chunks removed they will ofc need to stay anyways, increasing overhead in storage on deletion, and increased complexity.

Just brainstorming, it'd be cool to integrate Duplicacy into Proxmox like Vertical Backups is integrated for VMware 😄 

I can tell you that the deduplicaton worked very well when hard settings the chunk size to 4096 ( duplicacy init -chunk-size 4096 -max-chunk-size 4096 -min-chunk-size 4096)

```
Backup for /var/lib/vz/dump at revision 3 completed
Files: 6 total, 330,154K bytes; 2 new, 110,051K bytes
File chunks: 82542 total, 330,154K bytes; 37 new, 144K bytes, 105K bytes uploaded
Metadata chunks: 1453 total, 5,805K bytes; 454 new, 1,809K bytes, 1,746K bytes uploaded
All chunks: 83995 total, 335,959K bytes; 491 new, 1,954K bytes, 1,851K bytes uploaded
Total running time: 00:00:26
```

Damn Proxmox Backups!

**Comment by Lillecarl** [comment]
I've made some progress
http://paste.debian.net/998924/
https://forum.proxmox.com/threads/configuring-backups-to-cloud-storage.34302/#post-190048 If you see a few posts down i started testing Duplicacy out, it seems like the cluster size of 65k is the max we can use to get dedup. It's a great improvement over 4k, but it's still going to make millions of http requests when initial backup is done.

**Comment by gilbertchen** [comment]
One option I can think of is to reorder the 4k blocks by their hashes inside the .vma file in-place, and at the same time create the json file to record their initial positions.  Then Duplicacy will be able to back up the new .vma file efficiently with the default settings.

Of course, sorting the 4k blocks using their on-disk positions would be the best, but is such information available?

**Comment by Lillecarl** [comment]
Well yes, since we're able to rebuild an image file and a config by extracting the .vma it's certainly possible. Though I'm just a hobbyist so i wouldn't know how to do it.

Here's a patch where proxmox's own "vma" tool is in:
https://git.proxmox.com/?p=pve-qemu.git;a=blob;f=debian/patches/pve/0028-adding-old-vma-files.patch;h=08cf5f7bb8230f54fed7dd577a531b6e878267a7;hb=HEAD

I guess this is "a bit" out of Duplicacys scope though, but it'd be nice if a "Vertical Backup, Proxmox edition" would just randomly appear! ;)

**Comment by gilbertchen** [comment]
Sorry I didn't have time to look into this.  I hope when I have more time to work on the backup of virtual machines I'll be able to find a solution.

**Comment by Lillecarl** [comment]
@gilbertchen Don't worry, i thought i'd close it as it's not more related to Proxmox integrated backup solution being shit rather than Duplicacy :)
