### ISSUE TITLE
Are regexp filters broken?

### ISSUE THREAD

**Issue by Ossssip** [gilbertchen/duplicacy#256]
Hi. I am trying to use duplicacy 2.0.9 on windows and linux with some filter patterns. The wildcard matching seems to be working fine, however when I try to use any regexp pattern I always get all my files excluded. At first I decided that there should be some mistake in my regexps (I am a novice with them). So I took the regexps from the user guide, like i:.* to include everything, and I am getting everything excluded. Here is excerpt of the -debug output: 
```
Loaded 1 include/exclude pattern(s)
Pattern: +i:.*
Listing 
Synchrotron Light Sources and Free-Electron Lasers.pdf is excluded
delete_all_my_jobs.sh is excluded
New folder/ is excluded
TDS/ is excluded
```
If I try to explicitly include pdf files (like it was done in the example), I am still getting everything excluded:
```
Loaded 2 include/exclude pattern(s)
Pattern: +i:(?i)\.(pdf|sh)$
Pattern: +i:.*
Listing 
Synchrotron Light Sources and Free-Electron Lasers.pdf is excluded
delete_all_my_jobs.sh is excluded
New folder/ is excluded
TDS/ is excluded

```
Am I stupid and missing something very essential?

**Comment by gilbertchen** [comment]
The regex support was added after version 2.0.9 was released.  If you build from the latest source it should work.

**Comment by Ossssip** [comment]
Thanks for the explanation!

**Comment by jt70471** [comment]
And even when you use a more recent build, the regex filter prefixes are "i:" and "e:" to include/exclude respectively. The +/- prefixes are for the pattern matching filters that duplicacy originally provided.
