### ISSUE TITLE
How to move storage?

### ISSUE THREAD

**Issue by thomasjsn** [gilbertchen/duplicacy#258]
If I need to move storage; can I just move the files and update the entry in `.duplicacy/preferences`?

**Comment by gilbertchen** [comment]
Yes, if you're moving between the same type of storages.  However, if you're moving from an sftp server to a cloud storage, then be aware that it can't be simply copied due to the differences in the chunk directory structures.  See #163 for details.

**Comment by thomasjsn** [comment]
I'm just moving within the same storage, thanks for the clarification.
