### ISSUE TITLE
Option to cache all chunks in storage at the beginning of a backup

### ISSUE THREAD

**Issue by jay1337** [gilbertchen/duplicacy#269]
It is very slow to check one by one if each chunk is already in the storage.
It would be far more efficient to list all chunks in the storage at the beginning of the backup process, consider them like they were already uploaded (ie cache them), and then run the normal backup process which won't send any request to the storage if the chunk is already there.

It could save a LOT of time after the first backup for big repositories with slow storages (hubic especially, since at the moment each skipped chunk requires to start a new https connexion).

What do you think about that ?

**Comment by gilbertchen** [comment]
Duplicacy is already doing this for the initial backup in most cases, unless you are running 2.0.9 or older AND the storage is a local drive, SFTP, or Dropbox.  Subsequent backups do not list all chunks -- that would be too time consuming when there are few file changes.  Instead, the chunks referenced by the last backup are assumed to exist in the storage so Duplicacy will never try to upload any of these chunks.

However, I agree that such an option may be useful even for subsequent backups under certain circumstances.  For example, after the initial backup you may add a lot of new files to the repository and these files may have already been backed up to the storage from a different computer.

**Comment by jay1337** [comment]
Ok.

So in fact it only costs a lot of time after:

- a failed first backup
- or, a failed new backup after big new files added

I agree that it's not a common use case (since there is now a retry mechanism to avoid failures :) ).
