### ISSUE TITLE
problems during copy

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#271]
1. in the [copy wiki](../wiki/copy), there is no description for the -threads option. also, from what i remember -threads wasn't for the upload threads, instead of download? i remember download is only 1 thread.
This is from the description in duplicacy cli:
```
z copy -to gdrive-test -threads 25 -stats
Incorrect Usage.

NAME:
   duplicacy copy - Copy snapshots between compatible storages

USAGE:
   duplicacy copy [command options]

OPTIONS:
   -id <snapshot id>            copy snapshots with the specified id instead of all snapshot ids
   -r <revision> [+]            copy snapshots with the specified revisions
   -from <storage name>         copy snapshots from the specified storage
   -to <storage name>           copy snapshots to the specified storage
   -download-limit-rate <kB/s>  the maximum download rate (in kilobytes/sec)
   -upload-limit-rate <kB/s>    the maximum upload rate (in kilobytes/sec)
   -threads <n>                 number of downloading threads
```
2. (i think it was asked somewhere) There should be multiple threads both for upload and download
3. There should be a `-stats` option

4. ```z copy -to gdrive-test -threads 25``` gives me the following error:
```
Chunk a582d9512768c264eaac4808d5061d51e68d25cd4cfc13ab4a74fdc354da0eda (262/4346) copied to the destination
Chunk f8d36ff57a7b28e958b8b648fd44f541ea7985ea4702c3829ab6f8c74d7045f4 (303/4346) copied to the destination
Failed to upload the chunk ce51bb9eec32755e1db1fea295ee3b3b7dd85563c92396a1027ec585fe36878b: Failed to create directory 'chunks/ce': chunks/ce is a file
```
Default is local disk (all preferences are presented in #270) .
Note that i have started and stopped the copy operation multiple times.

**Comment by gilbertchen** [comment]
If you check on the web UI, does `chunks/ce` appear to be a file?

I'll update the wiki page.

**Comment by TheBestPessimist** [comment]
frankly, i have no idea. gdrive web doesn't work (nor gdrive android app). here's what i have (do note that in "details area" it sais that i uploaded something, but i cannot see it!
![ihavenoidea](https://user-images.githubusercontent.com/4482210/33141488-faa5b92c-cfbb-11e7-95af-564a9079c570.PNG)
:

**Comment by TheBestPessimist** [comment]
Closing this as the issues presented are either fixed or new, more specific issues have been created.
