### ISSUE TITLE
check -files should delete the temporary chunks sooner

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#274]
I have started a ```check -files``` on gdrive, and at some point, duplicacy said that a chunk was missing and quit. Here's the log:
```

D:\backup_software_test\duplicacy repo>
D:\backup_software_test\duplicacy repo>z -log  check -tabular -files -storage gdrive-test1939
2017-11-23 14:39:39.361 INFO STORAGE_SET Storage set to gcd://duplicacy-test-storage-19-39
2017-11-23 14:39:42.150 INFO SNAPSHOT_CHECK Listing all chunks
2017-11-23 17:24:41.457 INFO SNAPSHOT_VERIFY All files in snapshot duplicacy-test-storage1939 at revision 1 have been successfully verified
2017-11-24 10:58:37.381 FATAL DOWNLOAD_CHUNK Chunk 8e38eae970305203d6e5c73b56f327979ad604ee7ba1f15facecbc9f5ffaefd0 can't be found

```

As you can see in the image, duplicacy left me in the cache folder with >100 GB of data (which i assume are chunks downloaded for checking. 

I don't think this is ok, and i believe that those chunks should be deleted waaay sooner (think that i have an 240 gb ssd, 20 gb free, and i start doing a full check. 20 gb will fill in no time!).

My request however raises another problem: you  must download each chunk multiple times, which is not good for time and bandwidth (gdrive is slow for example). in this case, in order not to re-download a chunk n-times (for multiple revisions) you could keep a map of the chunks already checked to be ok. If this map is too big, then maybe even keep a temp file on the disk which stored that info.

Is this possible? (the bug and the solution?)

Note: i won't delete the cache just yet, in case you want to check anything else, but please tell me when i can purge it.

**Comment by TheBestPessimist** [comment]
From [wiki/cache](../wiki/Cache) i see that ```check``` does not clean the cache, so at least part of what i said above is not valid. What i think it remains valid is that there' shouldn't be the need to store hundreds of GB (TB?) of data during the check command. That just feels wrong.

Wiki: 
```
Other commands, such as list, check, does not clean up the local cache at all, 
so the local cache may keep growing if many of these commands run consecutively.
However, once a backup or a prune command is invoked, the local cache should
shrink to its normal size.
```

**Comment by gilbertchen** [comment]
Maybe we should add a `-clean-cache` option to the list command.

**Comment by TheBestPessimist** [comment]
oh, i didn't upload the image. Here it is
![gdrive](https://user-images.githubusercontent.com/4482210/33242135-c463bd80-d2d8-11e7-9c83-462c58df9a7b.PNG)
I suppose that by list, you actually mean check.
I am unsure if clean cache would do, due to the following: let's say i have a huge revision, #333, which has 2 TB (external hdd backed to google).
My repo is created using symlinks  from different various folders (it actually is like that now!), but my tablet only has 240 gb ssd. If i chose to ```check -all -storage gdrive -files -r 333``` it will download at some point my huge revision locally. That is impossible since i don't have 2 TB of space.
Is my understanding correct?

**Comment by gilbertchen** [comment]
File chunks are never saved in the local cache.  Only metadata chunks needed to reconstruct the file list and the referenced chunk list are saved.  For one revision the total size of metadata chunks may be a few GBs, but if you run a check on all revisions then the local cache can reach 100GBs.

**Comment by TheBestPessimist** [comment]
Maybe i misunderstood 
something, but metadata chunks should store file properties, such as owner, permissions per user, file attributes and i don't know what else.
If my understanding is correct, then i think it's impossible to have more than 100GB of metadata, because my backup is 600 GB, 878 files (all video files) and 185 folders.
With those files i really think than the metadata should be even < 10 MB.
This is why i think that file chunks were downloaded.
![my data](https://user-images.githubusercontent.com/4482210/33254273-9127e3b0-d350-11e7-9247-bcdbf2217223.PNG)

**Comment by gilbertchen** [comment]
I found out where the problem was.  `RetrieveFile` uses the chunk downloader owned by the snapshot manager to download the file but this downloader is set to cache every chunk it downloads.  Therefore, the entire backup will be saved to the cache if you run `duplicacy check -files`.

This should be fixed by https://github.com/gilbertchen/duplicacy/commit/6f69aff712a6f7935d1316fa0ca01432942fae58.
 Could you please verify?

**Comment by TheBestPessimist** [comment]
Yes, now it doesn't seem to download data chunks. Horray :D.

On a different note though: 
From that commit i see that the modification could also break some other functionality which is dependent on the cache (maybe i'm wrong). So my question to you is: do you have any tests for this bug? Would they be difficult to implement?
In general it seems that you do a lot of development on the code, fix bugs, add new features, etc., yet it seems that the unit tests cover mostly the basic of the program functionality. 
For the bugs which were found and fixed, there don't seem to be added tests. Are you sure that this is good course of action?

Sorry if this is a rude remark, don't want it to sound so.

**Comment by gilbertchen** [comment]
One design rule is that file chunks will never be cached, so this fix should not affect other functionalities.  If it does, then there must be a different bug that this fix would expose.

Ideally every fix like this should be accompanied by a new test, but I want to strike a balance between code development and test coverage, as this is still an early stage project without abundant resources.  So what I have been trying to do is to maintain a small set of tests that cover the most fundamental functionalities (such as the correctness of backup).  The unit tests in fact are quite powerful in that they have caught many bugs in the past.  For example, for the recent work on the new nesting chunk structure I estimated that about half of the development time was spent on fixing bugs in the new implementation to make the tests pass.

That being said, I agree that 100% test coverage should be our long term goal and we will be there eventually.

**Comment by TheBestPessimist** [comment]
In this case, should we just close this issue?

**Comment by gilbertchen** [comment]
Yes, I'm going to close it.
