### ISSUE TITLE
 googleapi: Error 403: The specified parent is not a folder., parentNotAFolder

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#278]
There seems to be a weird error which keeps killing my upload, and i can't figure out why:
```
2017-11-29 10:52:06.025 INFO GCD_RETRY [15] Maximum number of retries reached (backoff: 64, attempts: 15)
2017-11-29 10:52:06.025 ERROR UPLOAD_CHUNK Failed to upload the chunk 0bac277419dfaae0f6b02a67758a08d7a88615c09312405ab8b12392566459fe: googleapi: Error 403: The specified parent is not a folder., parentNotAFolder
2017-11-29 10:52:06.036 INFO INCOMPLETE_SAVE Incomplete snapshot saved to D:\backup_software_test\duplicacy repo/.duplicacy/incomplete
```

This is what i did:

```
z init -e testRepo-id "D:\gdrive\duplicacy-test-storage"

z -d add -copy default -bit-identical -e gdrive testRepo-id gcd://duplicacy-test-storage

z -d -log backup -storage gdrive -stats -threads 32
```

In the storage i see that the folder 'chunks\0b' does not actually exist.
In the full log attached, you can see that the message appears for multiple threads, but for the other ones, i cannot see what they are trying to upload unfortunately, because it is not shown in the log, only for the thread which killed the upload.

Is this the case that all the threads are waiting for thread ```#15``` to create the folder, and nobody is doing anything? (why aren't the other threads just trying to create the folder and that's all?)

Another problem is that i don't see the error in the [gdrive API page](https://developers.google.com/drive/v3/web/handle-errors).

[full log.txt](https://github.com/gilbertchen/duplicacy/files/1513136/full.log.txt)

**Comment by gilbertchen** [comment]
I found Google Drive to be the weirdest storage -- if multiple threads try to create the same directory/file, you may end up with multiple different directories/files with the same name.  This will completely break lock-free deduplication.  Therefore, a lock is used to make sure that only one thread can create the directory at a time.

An easy solution is to create all subdirectories during the initialization of the storage.  However, this becomes less feasible when the nesting level is 2 or 3.

**Comment by TheBestPessimist** [comment]
Firstly, are you using the latest version of the google ~everything~ library, maybe they fixed this?
Secondly, should we raise a bug on google forums? Where, what exactly should we say?

**Comment by gilbertchen** [comment]
I'll write a simple tool to create all subdirectories in order to reproduce the issue.  This tool can also be used as a workaround if the issue persists.

**Comment by TheBestPessimist** [comment]
I have read some more about this (but didn't write in this issue) and it seems that google is just weird, as you said, and has problems.

**Comment by TheBestPessimist** [comment]
I suppose the tool is a good idea, but maybe it should wait until 2.1.0 appears to the horizon?

Meanwhile, as a temp-fix i will just fork your project, and create a branch which has the number of retries increased. I hope that will be satisfactory.

**Comment by TheBestPessimist** [comment]
After you fixed with https://github.com/gilbertchen/duplicacy/commit/801433340aebec56eb67c985947bdf1d0c4b4636 the bug in #292 it seems that this one is also fixed. I'll close the issue for now and reopen it/create a new issue if `notAFolder` happens again.
