### ISSUE TITLE
Empty folders possibly not being recorded in snapshots

### ISSUE THREAD

**Issue by thrnz** [gilbertchen/duplicacy#28]
I've noticed that empty folders don't show in a snapshot's files list. Is this intended behavior, or a possible bug?

Steps to reproduce: 
* Include an empty folder in a repository and run a backup
* List the files in the most recent revision, either from the command line or GUI.
* Note the absence of the empty folder

Using 1.1.4 CLI on Windows 10 x64

**Comment by gilbertchen** [comment]
Yes, this is a side effect of how files are saved in the snapshot.  When a file entry is added to the snapshot, one entry is added too for each of its parent directories if there isn't one already.

**Comment by thrnz** [comment]
Would it be possible to have Duplicacy identify and add empty folders to snapshots in a future version?

I could maybe work around it using pre- and post-backup scripts (either recording empty folders separately, or populating them with a temp file), although it would be more simple and efficient if Duplicacy handled them directly.

**Comment by gilbertchen** [comment]
I'll add this to my todo list, but it will be of low priority -- most likely when there is something else to fix in the backup code.

**Comment by thrnz** [comment]
Thanks.

**Comment by tbain98** [comment]
+1 for this. Git does the same thing, which is very frustrating. It's not a deal-breaker for me, but it would definitely be nice to have so I don't have to worry about it.

**Comment by gilbertchen** [comment]
With https://github.com/gilbertchen/duplicacy/commit/22ddc04698077fc297ae7408991405fc4aac0fad Duplicacy should now be able restore empty directories.

Empty directories were in fact recorded in snapshots.  If you run `duplicacy cat -r revision` without providing a file it will print the snapshot file and you'll find that empty directories are listed. `duplicacy list --files` only list files, not directories.
