### ISSUE TITLE
Have to enter GCD token and password for each backup

### ISSUE THREAD

**Issue by libots** [gilbertchen/duplicacy#281]
Every time I run Duplicacy in Linux (Debian 8.8), I have to enter my Google drive token and repository password. Running with `-d list`, I get the following readout:

```
Reading the environment variable DUPLICACY_GCD_TOKEN
Failed to get the value from the keyring: keyring/dbus: Error connecting to dbus session, not registering SecretService provider: dbus: DBUS_SESSION_BUS_ADDRESS not set
```

The same message occurs when reading the environment variable `DUPLICACY_PASSWORD`.

I don't have root access to this server, so I'm limited in what I can do with it. The error is persisting with the latest release binary (2.0.10).

**Comment by gilbertchen** [comment]
you can set the environment variable DUPLICACY_GCD_TOKEN as:
```
export DUPLICACY_GCD_TOKEN=/path/to/token/file
```

The same for DUPLICACY_PASSWORD.

Of source, storing them in keyring is more secure, but that requires you to set up GNOME keyring.

**Comment by Lillecarl** [comment]
https://github.com/gilbertchen/duplicacy/wiki/Managing-Passwords#saving-credentials-to-duplicacy-config-file You can also store it in the repo config like this:
duplicacy set -key gcd_token -value yourtokenhere
