### ISSUE TITLE
Restore of git repository doesn't restore fully

### ISSUE THREAD

**Issue by jkram** [gilbertchen/duplicacy#286]
When restoring a git repository from a previous version, using overwrite and delete options of the restore CLI, the git repository does not get reset to the previous version. Tags and other refs in the git repo that should not be in the restored git repository are still there. I could attempt to provide exact steps to reproduce, but it goes something like this:

Back up git repo
git update or get fetch gets new tags and refs into git repo
Restore git repo from previous backup (backup doesn't/shouldn't have refs/tags), with overwrite and delete
Note that the new tags/refs from git update/fetch are still there in restored git repo

I am evaluating duplicacy and really appreciate the product so far. I ran across this by accident. I could be doing something wrong, but don't know what it could be. I've tried things with -hash option also.

**Comment by gilbertchen** [comment]
I couldn't reproduce this.  In my test, I created a tag `v1`, ran a backup, and created another tag `v2`.  This is the output from `restore -r 1`:

```
Storage set to /Users/gchen/DUPLICACY_TEST_ZONE/TEST_STORAGE
Restoring /Users/gchen/DUPLICACY_TEST_ZONE/TEST_REPO to revision 1
Downloaded file1 (15)
Downloaded .git/COMMIT_EDITMSG (15)
Downloaded .git/logs/HEAD (166)
Downloaded .git/logs/refs/heads/master (166)
Deleted .git/refs/tags/v2
Deleted .git/objects/db/6826bab1a905c3938fb1113d0ca974015c429e
Deleted .git/objects/db/
Deleted .git/objects/81/03137f1a9fa7ce66ea0dceaf0aaa32474bbd11
Deleted .git/objects/81/
Deleted .git/objects/75/40d256a6ec446b0dfce75377e7bb798a63df1a
Deleted .git/objects/75/
Deleted .git/objects/42/76a507e920c9a49105f5494bb692384312a765
Deleted .git/objects/42/
Restored /Users/gchen/DUPLICACY_TEST_ZONE/TEST_REPO to revision 1
```

As you can see the tag `v2` was correctly deleted.

**Comment by jkram** [comment]
I tried it again and could not reproduce this time. Most likely I am confused on what was in the snapshot id that I restored, and the order I did things with the backup, git remote update, and restore.... I apologize for submitting this issue. Thanks for looking at it, and thanks for the nice backup tool.
