### ISSUE TITLE
gdrive: Failed to create directory 'chunks/69': chunks/69 is a file

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#292]
aaaaaaand another one with gdrive:

```
2017-12-07 18:51:22.600 ERROR UPLOAD_CHUNK Failed to upload the chunk 6975b99139873e12ab10a80b890b495ff94dcf337a023c1795d71c6be7aa5a7b: Failed to create directory 'chunks/69': chunks/69 is a file
2017-12-07 18:51:22.625 INFO INCOMPLETE_SAVE Incomplete snapshot saved to D:\backup_software_test\duplicacy repo/.duplicacy/incomplete

```

**Comment by TheBestPessimist** [comment]
Also, i have seen this multiple times since v2.0.10 i think:
![untitled files](https://user-images.githubusercontent.com/4482210/33728809-5a8d74c8-db84-11e7-8a83-49be9b4f791e.PNG)
Duplicacy keeps creating some `Untitled` and 0 bytes in size.

**Comment by gilbertchen** [comment]
Is `chunks/69` really a file if you check in through the web UI?

**Comment by TheBestPessimist** [comment]
It doesn't exist in gdrive. 
This happened (the error) multiple times yesterday, for different chunks/folders.
Not sure if the "untitled" files are related to the missing/uncreated folders. i haven;t counted properly.

**Comment by gilbertchen** [comment]
This is a Duplicacy bug:

```
	file := &drive.File{
		Name:     name,
		MimeType: "application/vnd.google-apps.folder",
		Parents:  []string{parentID},
	}

	for {
		file, err = storage.service.Files.Create(file).Fields("id").Do()
		if retry, err := storage.shouldRetry(threadIndex, err); err == nil && !retry {
```

The struct `file` is initialized correctly for the first call to `Files.Create`.  But if an error occurs, on the retry `file` will be the object returned by the failed call which only have the `id` field.  The MimeType field is nil, so the second call will create a file instead of a directory.  The Parents fields is also missing, and this is why you can't find that file.

I'll work on a fix and other improvements tonight.

**Comment by gilbertchen** [comment]
The fix is here: https://github.com/gilbertchen/duplicacy/commit/801433340aebec56eb67c985947bdf1d0c4b4636

**Comment by TheBestPessimist** [comment]
I wanted to submit a PR for the changes related to `GCDFileMimeType ` and `GCDDirectoryMimeType`. I didn't like them as strings the least.

**Comment by TheBestPessimist** [comment]
After testing for 2 hours of upload with 64 threads, it seems that this bug is fixed.
Thanks gchen!
