### ISSUE TITLE
Cannot set path for Google Cloud Storage (GCS) token file.

### ISSUE THREAD

**Issue by rhass** [gilbertchen/duplicacy#305]
It seems there currently is no way to set the path to the token file for GCS (not to be confused with the GCD consumer product). This make automated backups to Google Cloud Storage very clunky as other scripting has to handle answering the prompts.

**Comment by gilbertchen** [comment]
It is DUPLICACY_GCS_TOKEN.  I just added a row for it in the [wiki page](https://github.com/gilbertchen/duplicacy/wiki/Managing-Passwords).

**Comment by rhass** [comment]
@gilbertchen :+1: Thanks!
