### ISSUE TITLE
Repo "Initialized" [sic] but Storage "Not Initialized" [sic]

### ISSUE THREAD

**Issue by madranet** [gilbertchen/duplicacy#307]
I'm trying to access a backup I've successfully been able to backup and restore to, in the past. I'm using Amazon S3 for storage. So I `cd` to the directory in question and:

```
$ cd /path/to/archive/directory
$:  duplicacy list -a
Storage set to s3://eu-west-1@amazon.com/name.of.my.archive
Enter storage password: *************
The storage has not been initialized
```

OK. So the storage has somehow becom uninitialised.  Let initialise it then:

```
$: duplicacy init -encrypt archivename s3://eu-west-1@amazon.com/name.of.my.archive
The repository /path/to/archive/directory has already been initialized
```

I'm seeing this on both the archives I have set up in Duplicacy.  when I enter their passwords I'm told they're not initialised. When I try to [re] initialise them, I'm told they're already initialised. What's going on? I'm also confused by the difference between initialising the "Storage" and initialising the "Repository"?

**Comment by madranet** [comment]
Well, for some insane reason, both this and [the other issue I posted about today](https://github.com/gilbertchen/duplicacy/issues/308) where fixed simply by upgrading from version 2,0,9 and running 2,0,10 built from source.

???

**Comment by gilbertchen** [comment]
Initializing the repository means creating the `.duplicacy/preferences` file.  Initializing the storage means creating the `config` file.  You just need to run `rm -rf .duplicacy` before you can run the init command again.
