### ISSUE TITLE
Failed to download the configuration file from the storage: Failed to retrieve the config file: Unsupported encryption version 1

### ISSUE THREAD

**Issue by madranet** [gilbertchen/duplicacy#308]
As per the title, what does this error mean?

I'm trying to restore from a backup for someone whose laptop has died after a liquid spillage. So I'm attempting to retrieve the backup onto another computer. As per the docs I've made and CD'd to a new directory and am trying to init an empty repo there so I can restore. However I can't get it to work:

```
$: mkdir restore && cd restore
$: duplicacy init -encrypt backup s3://eu-west-1@amazon.com/their.backup.bucket
$: Enter S3 Access Key ID: XXXXXXXXXXX
$: Enter S3 Secret Access Key: XXXXXXXXXXX
$: Enter storage password for s3://eu-west-1@amazon.com/their.backup.bucket:*********
$: Failed to download the configuration file from the storage: Failed to retrieve the config file: Unsupported encryption version 1
```
I get this error every time. 

Now, what's muddying the waters somewhat is that, because the person in question's laptop has died, they're not entirely sure which of their passwords they used to protect the backup in the first place. We know roughly what it is, but aren't sure which variant of it was used, so I'm having work through all the many permutations, which is extremely time consuming.

So, what I want to know really is does this error mean I'm entering the wrong password? [in which case, that's OK, I can just keep working through the permutations til we get it, or does it mean somethig else? [in which case, I'm wasting my time working through their known password variants].

**Comment by madranet** [comment]
Well, for some insane reason, both this and [the other issue I posted about today](https://github.com/gilbertchen/duplicacy/issues/307) where fixed simply by upgrading from version 2,0,9 and running 2,0,10 built from source.

???

**Comment by gilbertchen** [comment]
This is because the storage was initialized with version 2.0.10, and version 2.0.9 can't decrypt the `config` file created by 2.0.10.

**Comment by willodactyl** [comment]
I hope it's ok to post in a closed thread here. I created an offsite (b2) storage from linux with 2.0.10 and am now receiving this same error trying to 'duplicacy add' that storage destination from Windows because it is using 2.0.9.

Could you release an updated Windows command line binary? Currently duplicacy.com only seems to link to an installer for 2.0.9. I've never used Go so compiling from source isn't super easy for me.

**Comment by willodactyl** [comment]
Sorry, nevermind. I found it here https://github.com/gilbertchen/duplicacy/releases
