### ISSUE TITLE
Fossilization incurs additional costs on Wasabi

### ISSUE THREAD

**Issue by markfeit** [gilbertchen/duplicacy#322]
(This is mostly a placeholder; I may work on this myself as an excuse to learn Go.  A more-detailed explanation has been added to the [Storage Backends](https://github.com/gilbertchen/duplicacy/wiki/Storage-Backends) page on the wiki.)

S3 lacks support for renaming objects and instead accomplishes it with a copy and delete.  When used with Wasabi, this incurs additional costs because Wasabi's billing model charges for a minimum of 90 days of storage for any created object, and copies create new objects with new 90-day clocks.

Wasabi's API has a rename operation that can be performed at no cost and leaves the object in its original state with respect to billing.  Separate code for Wasabi that incorporates this should be developed.

**Comment by gilbertchen** [comment]
Thanks for the information.  I wasn't aware of this.  I think you just need to add a new parameter to the `S3Storage` struct to indicate if there is a rename api.  And then add a new storage url prefix `wasabi://` for which the parameter will be `true` but `false` for the regular `s3://` storage.

**Comment by markfeit** [comment]
There are a couple of reasons why I don't think it's going to be that simple, but feel free to correct me if I'm missing something.

First, AWS doesn't have rename, so there's no standard API for it.  Wasabi borrows WebDAV's `MOVE` verb, but there's no guarantee that's going to be the same on other services that have an API of their own.

Second, there's no support for it in [aws-sdk-go](https://github.com/aws/aws-sdk-go).  As much as I'd like to use as much of the existing S3 code as I can, it doesn't look like it would be easy to make the SDK do it without a fork of the whole thing.  Amazon would probably not be inclined to take a pull request that helps out a competitor.

The subset of the SDK used by Duplicacy is small enough that it might be worth doing a standalone module as was done for B2 and either make it Wasabi-only or give it a switch as you suggested and use it for everything S3-ish.

**Comment by gilbertchen** [comment]
Then a Wasabi-only storage backend would make sense. 

But which S3 client library are you going to use?  Or are you thinking of calling the API directly just like how B2Storage is implemented?  I know Wasabi is using the [minio server](https://github.com/minio/minio) internally, and there is a minio client library too (which however doesn't seem to support the MOVE/RENAME method).

**Comment by markfeit** [comment]
I think the right solution may be to take a hybrid approach and develop just enough code to handle a standalone rename and maintain/call a `S3Storage` for everything else. That should help keep the size of the executable down since anything I'd need to call is likely to have been used by S3.

Whatever Wasabi is using, they can do a rename internally the hard way at a low, predictable cost because they know for sure the copy will always be followed by a delete.  They can't guarantee that a customer will do that because a copy could be a legitimate copy.

**Comment by markfeit** [comment]
My change for this was pulled back in March.  Closing.
