### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by adrianmihalko** [gilbertchen/duplicacy#326]
Hi,

Can you implement an email notification feature like in verticalbackup?

We can also provide the time in the hh:mm format to schedule a daily backup job.

To set up email notifications, first run the email command:

`vertical email smtp.gmail.com 587 username password from@gmail.com to@gmail.com`

Then when we can run the backup command with the --email option. An email will be send to to@gmail.com after the backup is finished.

`vertical backup vm-ubuntu --email`

**Comment by adrianmihalko** [comment]
One more question.

I am backing up /home/madrian/ directory (here I have the .duplicacy folder). At this moment I run duplicacy backup from this directory (/home/madrian/). How can I run backup for this folder from another directory (example from script at /home/madrian/scripts/duplicacy.sh)?

**Comment by Technifocal** [comment]
I assume you're using the CLI version, both of these seem to be possible as is.

For the email, simply add a `.duplicacy/scripts/post-backup` script to send the email, or schedule it within the script that calls it (`duplicacy backup && sendSuccessMail || sendFailureMail`). You will, obviously, need to use another tool to actually send the mail. I personally use healthcheck.io to email me if duplicacy doesn't run within 24 hours of its hourly backup schedule.

For the call-from-another-script, simply `cd /home/madrian` before calling duplicacy.

**Comment by adrianmihalko** [comment]
You are right, thank you for the tip. :)
