### ISSUE TITLE
Chunk rename failed because chunk already exists

### ISSUE THREAD

**Issue by kairisku** [gilbertchen/duplicacy#343]
I am running duplicacy on a Linux box using local disk as storage (which is actually an NFS mount on a NAS). 

A backup run just failed with the following error when renaming the temporary chunks to their final names:

```
Uploaded chunk 11306 size 2809396, 45.09MB/s 00:02:13 72.8%
Uploaded chunk 11308 size 840441, 45.09MB/s 00:02:13 72.8%
Uploaded chunk 11307 size 4194304, 45.10MB/s 00:02:13 72.8%
Uploaded chunk 11309 size 758127, 45.11MB/s 00:02:13 72.8%
Failed to upload the chunk e72ed8723c5826ccb50e41b95cf5b6249d18a4da481f04773ca9d66413706fe8: rename /p/nas/Duplicacy/chunks/e7/2ed8723c5826ccb50e41b95cf5b6249d18a4da481f04773ca9d66413706fe8.dvwhzxvz.tmp /p/nas/Duplicacy/chunks/e7/2ed8723c5826ccb50e41b95cf5b6249d18a4da481f04773ca9d66413706fe8: no such file or directory
Failed to upload the chunk 5da0f50d7f0abde066c8c0bb39362a4bd5929e9f91cdc564707979f0f56bc7ba: rename /p/nas/Duplicacy/chunks/5d/a0f50d7f0abde066c8c0bb39362a4bd5929e9f91cdc564707979f0f56bc7ba.sgaetgrj.tmp /p/nas/Duplicacy/chunks/5d/a0f50d7f0abde066c8c0bb39362a4bd5929e9f91cdc564707979f0f56bc7ba: no such file or directory

```
But when I look at the stored chunks, it seems like the rename was indeed successful, because the final chunk names are there:

```
stat /p/nas/Duplicacy/chunks/e7/2ed8723c5826ccb50e41b95cf5b6249d18a4da481f04773ca9d66413706fe8
  File: `/p/nas/Duplicacy/chunks/e7/2ed8723c5826ccb50e41b95cf5b6249d18a4da481f04773ca9d66413706fe8'
  Size: 171236          Blocks: 336        IO Block: 32768  regular file
Device: 17h/23d Inode: 118819611   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-30 13:15:36.681835151 +0200
Modify: 2018-01-30 13:15:36.694834988 +0200
Change: 2018-01-30 13:15:39.000000000 +0200

stat /p/nas/Duplicacy/chunks/5d/a0f50d7f0abde066c8c0bb39362a4bd5929e9f91cdc564707979f0f56bc7ba
  File: `/p/nas/Duplicacy/chunks/5d/a0f50d7f0abde066c8c0bb39362a4bd5929e9f91cdc564707979f0f56bc7ba'
  Size: 773666          Blocks: 1512       IO Block: 32768  regular file
Device: 17h/23d Inode: 118950219   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-30 13:15:36.684835114 +0200
Modify: 2018-01-30 13:15:36.719834675 +0200
Change: 2018-01-30 13:15:39.000000000 +0200

```

The timestamps of the final chunks are fresh, i.e. they seem to have been created just as the backup run failed. I cannot find evidence of NFS-related errors in either the Linux or the NAS box. There were no other duplicacy processes running at that time. 

Strange! Any possible explanations?

**Comment by gilbertchen** [comment]
This looks like an NFS error to me, because there were two errors with different chunks, meaning 2 threads having the same problem at the same time.  Maybe a temporary network issue caused that?

**Comment by kairisku** [comment]
Yes, it seems to be an NFS error. Found this really old ticket that describes it pretty well:
https://bugzilla.redhat.com/show_bug.cgi?id=185056

Although I use NFS over TCP, I used shorter timeout values tuned for UDP instead of trusting TCP's own retransmission mechanism. I have now tweaked the NFS client parameters and hope it helps.
