### ISSUE TITLE
Wiki suggestion: multiple storages prune info

### ISSUE THREAD

**Issue by williamgs** [gilbertchen/duplicacy#347]
Thank you for adding this page
https://github.com/gilbertchen/duplicacy/wiki/Back-up-to-multiple-storages

I was about to add the following footnote to the wiki, but I realized I'm a little unsure of the behavior and can't test it right now.

> It is worth mentioning that the [[copy]] command is non-destructive, so pruned data from one storage will not be automatically pruned on the copy.

This is true, right? I personally use the same local and offsite retention policies for prune, but I think other situations should be clarified, For this example `duplicacy copy -from onsite -to offsite`

- if onsite prune is equal to offsite prune. this is perfectly fine
- if onsite prune is more aggressive than offsite prune, this is fine? (not sure why anyone would do this)
- if onsite prune is less aggressive than offsite prune, this would be a bad idea (inefficient to keep copying data that will be immediately pruned).

Maybe a `copy --delete` could be useful? I'm not sure. The current behavior isn't broken because users can manually specify revisions during copy and prune, but it would be pretty hard to automate one of those asymmetric copy situations mentioned above.

It would at least be good to mention that `copy` doesn't delete anything, so remote storage will grow unless you prune there too. (Unless I'm totally wrong)

**Comment by gilbertchen** [comment]
> It is worth mentioning that the [[copy]] command is non-destructive, so pruned data from one storage will not be automatically pruned on the copy.

Yes, this is right.

> if onsite prune is less aggressive than offsite prune, this would be a bad idea (inefficient to keep copying data that will be immediately pruned).

This is an issue.  If you don't specify revision numbers in the copy command Duplicacy will copy over every revision not present in the offsite storage, including those that have been pruned.  As you said, this makes scripting harder, but you may be able to work around this problem by using a combination of tags and -keep policies.

> It would at least be good to mention that copy doesn't delete anything, so remote storage will grow unless you prune there too. (Unless I'm totally wrong)

Agreed.

**Comment by williamgs** [comment]
Thanks again for the quick response. I've updated the wiki page, so I'm closing this issue. I didn't update the copy or prune pages because it seems more relevant under use cases than command reference.

Perhaps a feature request should be added for 

- `copy --delete` 
- `copy -t <tag>`

But personally I haven't used tags and am happy to run prune for each storage.
