### ISSUE TITLE
init command failure (with a DigitalOcean object storage bucket)

### ISSUE THREAD

**Issue by mdrakedo** [gilbertchen/duplicacy#348]
I'm receiving a similar error to the one reported by Kidswiss in #85. I'm trying to run the `init` command with an object storage bucket from DigitalOcean. My command is written as follows:

```
duplicacy init /duplicacy-testing/ s3://us-east-1@nyc3.digitalocean.com/mybucket
```

which returns the following output:

```
Failed to download the configuration file from the storage: RequestError: send request failed
caused by: Head https://mybucket.nyc3.digitalocean.com/config: dial tcp: lookup mybucket.nyc3.digitalocean.com on 67.207.67.3:53: no such host
```

Using `s3c://...` returns the same, albeit after a longer wait. Do you have any suggestions for how to resolve this error?

**Comment by gilbertchen** [comment]
The storage url should be `s3://nyc3@nyc3.digitaloceanspaces.com/mybucket`.

Also, non-aalphanumeric characters other than `_` and `-` may lead to some issues.  `duplicacy-test` should be good.

**Comment by mdrakedo** [comment]
That did it, thank you!
