### ISSUE TITLE
Performance when Backing up to a USB3.0 HDD

### ISSUE THREAD

**Issue by jonreeves** [gilbertchen/duplicacy#349]
I've been doing some trials over the last few days, attempting to backup about 7TB of data from one USB to another. Both drives are USB3.0 and both seem to get about 50-100MB speed to them when doing normal Windows Explorer style copies (I'm aware this might not be accurately reported because of write caching).

What I've noticed with Duplicacy is that performance starts up at about 100MB/s and then declines quickly to the 70s and 50s, but after about 9 hours settles at about 20MB/s. I didn't think too much about it at first, but today (while its still running now) decided to poke into why?

The first weirdness I noticed was that the Disk usage in "Task Manager" would be at about 20-30MB/s but then after about 5mins goto 0 for a few seconds and then start back up again. The process is using about 4% CPU and 752MB of RAM.

I checked out what is going on in "Resource Monitor" and its seems like Duplicacy is hammering the drive with multiple writes at the same time causing the Queue Depth to be continuously maxed out. If I look over the live Disk Activity of the Destination Drive, it has about maybe 50 `.tmp` writes ongoing at once. At the point when the writes drop to 0MB/s the tmps all finish one by one and then the process starts up again.

I'm using `-threads ` but it seems like Duplicacy is writing more than one file at a time. Does it just decide to in parallel when it knows the destination is local `D:\Backups` ? If this is the case it probably needs changing because it absolutely punishes HDDs and results in a far less efficient transfer of data (I'm sure everyone has had multiple copies going to drives at the same time before, and had to pause them because of it slowing down the total progress).

I'm reluctant to stop now I'm 2TB in, but was curious if the process could be mitigated by using `samba://d:/backups` instead of `D:\backups`, or will Duplicacy know its still local and rain down on it?

Is what I'm observing unexpected for local backups (or is this some OS related write cache issue)? Is my suggestion about using samba likely to make a difference?

**edit**

The other option that occurred to me, was to run Minio locally and force the uploads to go via that, I'm tempted to cancel, but will wait to see what responses I get.

**Comment by gilbertchen** [comment]
> What I've noticed with Duplicacy is that performance starts up at about 100MB/s and then declines quickly to the 70s and 50s, but after about 9 hours settles at about 20MB/s. I didn't think too much about it at first, but today (while its still running now) decided to poke into why?

The speed numbers at the beginning can be misleading if there are many skipped chunks that have already been uploaded before.  These numbers just mean the processing speed, not the actual upload speed.

> I'm using -threads but it seems like Duplicacy is writing more than one file at a time

For local disk storages using multiple threads will only lead to worse performance.  Here is an example: https://duplicacy.com/issue?id=5670666258874368

**Comment by jonreeves** [comment]
Sorry I meant to say I'm not using `-threads`, purposely didn't set the -threads because of being local storage.

**Comment by gilbertchen** [comment]
Then I guess 20MB/s is probably normal if copy can do 50-100MB/s.  Duplicacy needs to run 1 rolling hash, 1 chunk hash, 1 file hash, and compression/encryption.

The best way to find out if there is any issue is to run a benchmark test with a randomly generated file:

```
mkdir /path/to/test/repository
cd /path/to/test/repository
duplicacy init repository_id local_storage
dd if=/dev/urandom of=1G bs=1m count=1024
duplicacy backup -stats
```

**Comment by jonreeves** [comment]
So I decided to terminate the backup and see what happens when I run the same command to the same storage but with the preferences updated to `samba://....`. First of all, I'm seeing fluctuations between 60-130MB/s reported in "Resource Monitor" as opposed to the 5-30MB/s before, but more noticeable is that the Queue Length remains under 1.00, normally about 0.64... instead of 5.00 that it was constantly at before. However the source disk is now between 3.00-5.00 most of the time (before it was < 1.00). So I guess that's good. So far its never froze and returned to 0MB/s for any period of time (like it was before).

This might be something that changes over time, because I didn't check at the start of the previous backup attempt what the Queue Length or MB/s was via the "Resource Monitor". Perhaps the drive slows down as more files are written to the folders (although with all the previous files still there, it should still be slow if that was the case).

I'll check back in 12 hours or so and see what state its in then, but performance has at least doubled in terms of real disk speed (I'm not relying on Duplicacy's reported speed because its obviously its skipping over existing items now).

Is it possible that `samba://` would write/behave differently to the `D:\Backups` or is it more likely to be some other factor?

@gilbertchen I'll see what happens with this run because its now claiming only 19hours and has only hit 500 skips out of 13000 chunks uploaded so far. So I suspect the estimate will only get quicker. If it slows down again in 12 hours I'll kill it and do what you suggested with a random data and see what I get.

**Side note and maybe useful Tip for others**
I use the samba prefix for relative paths `samba://../Backups` if you happen to be running Duplicacy on a portable drive or something, it helps cause the drive letter can change in windows.

**Comment by gilbertchen** [comment]
This is a clever use of `samba://`.  I never thought it can be used this way.

But I don't know what made the performance differences.  The only different between a samba storage and a local disk is that the samba storage has the snapshot cache enabled while the local disk has it disabled.  If you look at the code in `duplicacy_storage.go` you can see both are implemented by `FileStorage` and should follow the same code path.

The snapshot cache should have no effect in your case, since you're still uploading file chunks which are not saved to the snapshot cache.  Only snapshot chunks, which are generated at the end of the backup, will be saved to the snapshot cache.

**Comment by jonreeves** [comment]
> This is a clever use of samba://. I never thought it can be used this way.

Yeah initially I tried "..\Backups" then a few attempts at a UNC for the same, but Duplicacy rejected it. I was gonna file a Feature Request and then I saw the `samba://` prefix in the wiki so gave it a try.

> If you look at the code in duplicacy_storage.go you can see both are implemented by FileStorage and should follow the same code path.

So performance wise it inevitably ended up saturating the Queue Length at some point in the night and slowed down again to bursts of writes with waits inbetween, resulting in a 19-21MB/s outcome. It seems like the disk gets behind on whatever it has to do to close the file write in the filesystem, and the drive locks up while that finishes.

Its an NTFS drive and both `Indexing` and `Write Caching` is off (I'm not sure if that would help, considering its tons of files between 1MB and 16MB).

It does appear - as you say - to more likely be a limitation of the spinny drive after writing lots of smaller files over time. I don't know if its going to get worse as more files are in each nested chunk folder. Right now I'm seeing a little over 2000 in most of them, but I have a long way to go in the backup.

Because this backup to USB is just the seed for a `copy` to B2, I didn't want to tinker with making 2 nested levels of chunks as it sounded like that would introduce a ton more API hits.

I'll keep this thread open for the moment to feedback if making any other changes to anything else in the process helps the USB Drive perform quicker. But I'll close it after, because I believe the behavior is probably normal.

**Comment by jonreeves** [comment]
So the backup finished and ended up leveling out at 12MB/s by the end.

I'm going to backup another USB drive to the same destination soon, and will observe if it continues to decrease as more chunks are written, but it does seem that its just the HDD not playing nice with writing lots of small files in one go. I don't know if NTFS is slower in this respect to HFS but its worth keeping in mind for those thinking about backing up locally to a USB or a NAS that has spinny drives.

**Chunksize**

Increasing the Chunksize might be the best option. I took one of my main sources that I want to backup which has `3.8TB` of data and I had a look at which file types use up the most space and what their average/max size is. They really vary quite a bit, but 76% of that source has an average filesize of `16.81MB` so it would seem to make sense to go with a bigger chunksize.

The interesting thing I'm still kind of struggling to get my head around is how chunksize will affect files that change more frequently... For example my `Top 30 File Types` that use up the most space in that source, account for `97.3%` of the raw data. But they are also the files that **never** change. They literally never get modified. More of them are added though. All the smaller files that make up the remaining few percent change all the time. They are the `.js .php .html .css .doc etc...` files or the `.xmp` for image editing.

The issue is, these files often live alongside the big files and there in lies the problem. I don't know the affect of going with a bigger chunksize yet (I will test this soon), but other tests I've done show that changes in these smaller files cause offsets or reordering among the big ones, and that makes the storage balloon in size. #334. 

Hopefully the work @fracai has done will help with this #248.
