### ISSUE TITLE
Chunks randomly resurrected

### ISSUE THREAD

**Issue by Ithilion** [gilbertchen/duplicacy#354]
```
Two back to back backup/prune

C:\.duplicacy\logs\prune-log-20180205-044140:
Marked fossil 1ec891a4382e6449f064e371bb0cad8a504333ac9901ff205738aefa1d961a42

(from my backup logfile, during the second prune job)
2018-02-05 05:55:08.942 INFO FOSSIL_RECREATE The chunk 1ec891a4382e6449f064e371bb0cad8a504333ac9901ff205738aefa1d961a42 already exists

C:\.duplicacy\logs\prune-log-20180205-055153:
Resurrected fossil 1ec891a4382e6449f064e371bb0cad8a504333ac9901ff205738aefa1d961a42 (collection 1)
```
I've observed this behavior with a few (less than 20) chunks. Is this intended? What does it mean? These are the only instances where this chunk is referenced in my logfiles.

**Comment by gilbertchen** [comment]
This is evidence of [Lock-Free Deduplication](https://github.com/gilbertchen/duplicacy/wiki/Lock-Free-Deduplication) in action.  The prune command thought that chunk is unreferenced, without knowing the existence of the backup referencing it.  And later when it see the backup it was able to turn the fossil back into a chunk.
