### ISSUE TITLE
prune with tag and keep behave unexpectedly

### ISSUE THREAD

**Issue by williamgs** [gilbertchen/duplicacy#357]
Testing tagged backups and pruning. Using Duplicacy 2.0.10, I have backups tagged with either:

- `duplicacy backup -t "auto"` for scheduled backups, or 
- `duplicacy backup -t "manual"` for specific backups I might want to retain for some reason

```
D:\temp\duplicacy\repos\repo1>duplicacy list
Storage set to D:\temp\duplicacy\storage\storage1
Snapshot test-repo1 revision 1 created at 2017-12-02 02:27 manual -hash
Snapshot test-repo1 revision 2 created at 2017-12-13 16:14 auto
Snapshot test-repo1 revision 3 created at 2017-12-25 06:01 auto
Snapshot test-repo1 revision 4 created at 2018-01-05 19:47 auto
Snapshot test-repo1 revision 5 created at 2018-01-17 09:34 auto
Snapshot test-repo1 revision 6 created at 2018-01-28 23:21 manual
```

If I want to explicitly delete **all** of the "auto" or "manual" backups, prune works as expected:
```
D:\temp\duplicacy\repos\repo1>duplicacy prune -exclusive -t auto -dry-run
Storage set to D:\temp\duplicacy\storage\storage1
Deleting snapshot test-repo1 at revision 2
Deleting snapshot test-repo1 at revision 3
Deleting snapshot test-repo1 at revision 4
Deleting snapshot test-repo1 at revision 5

D:\temp\duplicacy\repos\repo1>duplicacy prune -exclusive -t manual -dry-run
Storage set to D:\temp\duplicacy\storage\storage1
Deleting snapshot test-repo1 at revision 1
Deleting snapshot test-repo1 at revision 6
```

But if I'd like to use a retention policy (with `-keep`) to prune only those tags, the behavior is inverted. The documentation for `prune -t <tag>` says "delete snapshots with the specified tags", but it is in fact deleting snapshots _without_ the specified tag.
```
D:\temp\duplicacy\repos\repo1>duplicacy prune -exclusive -t auto -keep 0:7 -dry-run
Storage set to D:\temp\duplicacy\storage\storage1
Keep no snapshots older than 7 days
Deleting snapshot test-repo1 at revision 1
Deleting snapshot test-repo1 at revision 6

D:\temp\duplicacy\repos\repo1>duplicacy prune -exclusive -t manual -keep 0:7 -dry-run
Storage set to D:\temp\duplicacy\storage\storage1
Keep no snapshots older than 7 days
Deleting snapshot test-repo1 at revision 2
Deleting snapshot test-repo1 at revision 3
Deleting snapshot test-repo1 at revision 4
Deleting snapshot test-repo1 at revision 5
```

Is this by design? I see how a command with both "keep this" and "delete this" simultaneously could be confusing, but the documentation doesn't mention different behavior for tags when using keep. I suppose the behavior does allow exactly what I want, it's just the syntax and/or documentation that leads to confusion.

**Comment by gilbertchen** [comment]
This is a bug.  I just checked in https://github.com/gilbertchen/duplicacy/commit/e07226bd621dcf03b15193e60ecbcb9efd3e797c that fixed it.

**Comment by williamgs** [comment]
Thanks!
