### ISSUE TITLE
Restore is very slow

### ISSUE THREAD

**Issue by Technifocal** [gilbertchen/duplicacy#362]
Hi, I'm attempting to restore a specific revision of my entire dataset using the command:

`duplicacy --debug restore -r 126 --stats --threads 8 --overwrite`

The backend is B2 and initially saturates my downstream at 70Mbit/s, but very quickly slows to a crawl (240Kbit/s). I would rather not provide a log due to the filenames being included, however, if required I can sanitize the output. The general output is:

```
Storage set to b2://BUCKETNAME/
Reading the environment variable DUPLICACY_B2_ID
Reading b2_id from preferences
Reading the environment variable DUPLICACY_B2_KEY
Reading b2_key from preferences
Reading the environment variable DUPLICACY_B2_ID
Reading b2_id from preferences
Reading the environment variable DUPLICACY_B2_KEY
Reading b2_key from preferences
Reading the environment variable DUPLICACY_PASSWORD
Reading password from preferences
There are 0 compiled regular expressions stored
Using 16384 iterations for key derivation
URL request 'https://f001.backblazeb2.com/file/BUCKETNAME/nesting' returned status code 404
URL request 'https://f001.backblazeb2.com/file/BUCKETNAME/nesting' returned status code 404
b2_download_file_by_name did not return headers
Chunk read levels: [1], write level: 1
Compression level: 100
Average chunk size: 16777216
Maximum chunk size: 67108864
Minimum chunk size: 4194304
Chunk seed: REDACTED
Reading the environment variable DUPLICACY_PASSWORD
Reading password from preferences
top: /path/to/duplicacy/restore, revision: 126, in-place: true, quick: true, delete: false
Loaded file snapshots/ID/126 from the snapshot cache
Chunk 9fcb56bf8f298f125b5816234761611218f3a3ed25f65fa1bab099a4e60d2eaa has been loaded from the snapshot cache
Fetching chunk 8f6007e682909f1057ab25120a25946593014ffcfda61a1a68389d7a642781d8
Chunk 8f6007e682909f1057ab25120a25946593014ffcfda61a1a68389d7a642781d8 has been loaded from the snapshot cache
Fetching chunk a65a003beb9195cedb297121049c0a6d691f7289ef7b8031bde2639f5c11bd2e
Chunk a65a003beb9195cedb297121049c0a6d691f7289ef7b8031bde2639f5c11bd2e has been loaded from the snapshot cache
Listing 
Failed to read the symlink: stat /path/to/duplicacy/restore/.steampath: no such file or directory
Listing a/directory/
```

Followed by a listing of a bunch of files, then:

```
Restoring /path/to/duplicacy/restore to revision 126
```

Finally followed by multiple of the following lines:

```
Downloading /path/to/a/few/files
Prefetching /path/to/a/few/files chunk ${chunk}
Updating /path/to/a/few/files in place
```

Then:

```
Downloaded chunk 11 size 4898339, 957KB/s 00:18:40 0.4%
Downloaded chunk 9 size 27013049, 2.17MB/s 00:07:50 2.8%
Downloaded chunk 1 size 35420726, 4.59MB/s 00:03:36 6.1%
Chunk 8ac30f267754907fb50ba3bd8b1f2490adac7803c47f2d6894e5e416a3188fa9 is unchanged
Chunk a0c449061e1a0c4b56a906a6673d654204cf16f5f7f35182306ee60fd0abf907 is unchanged
Chunk cbe0738bc32b56d4988698c5c9898842fc66b6ddeb33880bfff5b277cc3c29f0 is unchanged
Chunk 1dfef4d5744f63b42417e097526dffb5d22327521244d58eaec22b72f042ea5c is unchanged
Chunk 0717cd14d3711a881fc5bc2f972d9080ae7060f2d968f8c8ad03b076ba8de2cc is unchanged
Chunk e9a6ce65b6349b0ae297a29463ee887b6c9d4e8094a69dcef26f963be6f8015d is unchanged
Chunk e3a56881f2fce43f61ee6887342795ca349d4dcfdf28edb5f7abb1d79a594d88 is unchanged
Downloaded chunk 10 size 20191670, 4.17MB/s 00:03:52 7.9%
```

And then my network drops from 70Mbit/s to a fluctuating 240Kbit - 8Mbit/s (But most of the time on the lower end of that spectrum). At this point I ctrl+c the operation after a few minutes of being stagnant.

Am I doing something wrong here? Is there any reason why my download suddenly drops to near-zero?
 If you need any more information, or the full sanitize output, feel free to ask.

Thanks.

EDIT:
Just a quick update, if I restore with `--threads` not specified, it seems to last for much longer (albeit, I didn't leave it the full process of the restore). The download is obviously not as fast (Averaging 16-32Mbit/s, with down periods of no network traffic (I assume processing the downloaded chunk)), thus not preferable.

**Comment by Technifocal** [comment]
New update, running the same command on a newer backup (with threads) runs as expected (a few periods of 2.4Mbit/s, unsure why, and rarely maxing my net, but a lot of the time spent at 28Mbit/s+).:

```
Files: 4198 total, 1662.88M bytes
Downloaded 4181 file, 1662.86M bytes, 174 chunks
Total running time: 00:09:14
```

After letting the single threaded download run some more, it reported:

`Chunk ba623bdabc4086d4efc90f5f3fee4870860459bb32dbab6cb2f34d53915e82b0 can't be found`

For starters, it seems like that isn't reported when doing a multithreaded restore (Just seems to freeze). Second of all, why can't that chunk be found? greping my `.duplicacy/logs` directory for that chunk returns:

```
$ grep -ir 'ba623bdabc4086d4efc90f5f3fee4870860459bb32dbab6cb2f34d53915e82b0' .duplicacy                                                                                                                       
.duplicacy/logs/prune-log-20180112-002031:Marked fossil ba623bdabc4086d4efc90f5f3fee4870860459bb32dbab6cb2f34d53915e82b0
.duplicacy/logs/prune-log-20180113-085516:Resurrected fossil ba623bdabc4086d4efc90f5f3fee4870860459bb32dbab6cb2f34d53915e82b0 (collection 3)
```

Checking b2 it also doesn't seem to exist there:
![2018-02-17-234534_695x256_scrot](https://user-images.githubusercontent.com/20205745/36346764-b4abde40-143c-11e8-9fe7-853eb426718f.png)

The only computer backing up (or pruning) is this one, and the command it uses is:

`duplicacy prune --all --keep 0:31 --keep 7:14 --keep 1:7`

This was one of my oldest backups, so I can't be 100% sure I'm not the cause of that, but I know for a fact I've never deleted any files directly from B2, nor run `prune` with `--exclusive`, so I have no idea how/why that could have occurred. Check also returns an error:

```
$ duplicacy check --tabular
Storage set to b2://BUCKETNAME/
Listing all chunks
Chunk ba623bdabc4086d4efc90f5f3fee4870860459bb32dbab6cb2f34d53915e82b0 referenced by snapshot ID at revision 126 does not exist
Some chunks referenced by snapshot ID at revision 126 are missing
```

**Comment by gilbertchen** [comment]
I wonder if the [lifecycle setting](https://www.backblaze.com/b2/docs/lifecycle_rules.html) of your bucket is set to `Keep only the last version of the file`.  If so, the version that corresponds to the original chunk would be deleted 1 day after the chunk was marked a fossil, so when the fossil got resurrected, it was the "hide marker" that got deleted and the original chunk file would never get recovered.

**Comment by tophee** [comment]
@gilbertchen So if duplicacy is using B2's hide marker, does this mean that duplicacy is working differently on different storages?

**Comment by Technifocal** [comment]
@gilbertchen It was indeed set to "Keep only the last version of the file". Since this obviously is incompatible with Duplicacy, I have since changed it.

Would it be worth Duplicacy automatically setting "keep all versions of files" whenever it backs up, if it's not already that?

**Comment by gilbertchen** [comment]
@tophee All Duplicacy wants is a rename/move operation.  Most cloud storages provide either move or copy+delete, but B2 does not support move or copy.  Fortunately their people figured out that the hide marker is equivalent to a move operation and that is how the B2 backend is implemented.

@Technifocal it should at least throw an error if the "keep all versions of files" option isn't set.  I think there is a B2 api to check the lifecycle setting of a bucket.

**Comment by tophee** [comment]
How ironic: you build a software with minimalist requirements regarding commands supported by the backend, and then at least one backend still manages to not support even these...

So are you saying that although B2 doesn't really support move, it nevertheless accepts a move command and treats it as hide or is duplicati actually sending different commands to backblaze than it does to other backends?

In any case, I suppose that would be relevant information to put into https://github.com/gilbertchen/duplicacy/wiki/Storage-Backends

**Comment by jt70471** [comment]
I use the have versioning for B2 turned off and I don't have any issues at all. Why would we have different experiences?

**Comment by tophee** [comment]
> Why would we have different experiences?

As I understood it, the setting will only be a problem in certain situations, namely when a fossil needs to be resurrected (and if this happens more than 24 hours after it was "fossilized"). So if you're _not using the `prune` command_, you won't have a problem. And, I believe, if you _only have one repository_, there will never be the need to resurrect a fossil.

**Comment by jt70471** [comment]
That's interesting, but I actually run prune hourly on 4 different repositories using 3 different storage locations, each done hourly. I do, via my scripts, ensure that prune only runs/executes on one system and that only one is running at a time.

Do you by chance have multiple prune's running at the same time against the same repositories?

**Comment by gilbertchen** [comment]
@jt70471 that is a very rare case but it could happen to you too.  Suppose that an old backup to be deleted by the prune command contains the only copy of a file.  But before the prune command renames the chunks that compose the file, a new backup from another repository (still unknown to the prune command) happens to include the same file but doesn't upload all the chunks since they are already in the storage.  The prune command goes ahead to rename all the chunks (or hide the chunks using B2's hide markers) without realizing that they are needed by another backup (which is still in progress at this time so the final snapshot file has not been uploaded).

Sorry I gave the incorrect information in #168.  I wasn't aware that an old version hidden by a hide marker can be automatically removed when the lifecycle is set to `Keep only the last version of the file`.

**Comment by Technifocal** [comment]
As this issue was fixed (It related to a missing chunk, as described by `duplicacy check`) and it was my fault for misconfiguring B2, I have since closed this issue.

**Comment by beeblebrox** [comment]
@gilbertchen I have files that change frequently in my backups and I was hoping enforcing the prune operations each run would save me usage charges.  After reading this, it sounds like I will need to always keep the version or risk a bad backup, but won't that result in the b2 bucket forever growing even with prunes?

**Comment by beeblebrox** [comment]
I answered my own question by looking at the code.  Fossils are handled special in the b2 storage driver's DeleteFile so it will, in fact, delete the file and not leave it dangling in the bucket.  

Since I've just started using b2 for the last couple of days I'll keep an eye out for usage, just in case.

+1 For the suggestion to update the b2 backend page. I also changed my settings for the b2 bucket when I set it up to keep only the last version of the file.

**Comment by gilbertchen** [comment]
According to B2 doc (https://www.backblaze.com/b2/docs/lifecycle_rules.html):

> Keep all versions of the file (default) removes all lifecycle rules from the bucket, and keeps all versions of all files until you explicitly delete them.

So I think when a file is explicitly deleted it will be removed from the bucket.

**Comment by gilbertchen** [comment]
This issue has been mentioned on **Duplicacy Forum**. There might be relevant details there:

https://forum.duplicacy.com/t/backblaze-b2-bucket-size-does-not-match-storage-size/6836/6

**Comment by gilbertchen** [comment]
This issue has been mentioned on **Duplicacy Forum**. There might be relevant details there:

https://forum.duplicacy.com/t/b2-pruning-not-deleting-a-lot-of-old-revisions/8552/8
