### ISSUE TITLE
Duplicacy cannot backup one directory when the access to a sub-directory is denied

### ISSUE THREAD

**Issue by xulongwu4** [gilbertchen/duplicacy#367]
I created a full backup for my desktop using duplicacy 2.0.10. I ran duplicacy as root and expected it to backup every directory which are not included in the exclude pattern. At the end of the backup it complains the it cannot list my home directory even though it does not have any inappropriate permission settings.

- The version of duplicacy
2.0.10

- The linux version I use:
Solus 3

- How I run duplicacy:
I first created a repo under the root directory: `/`.
Then I ran the following script as root: `sudo ./duplicacy-snapshot.sh`
```
#!/bin/bash

### Content of duplicacy-snapshot.sh ###

PROGRAM=duplicacy

ID=desktop

# The path to the storage
REPOSITORY=gcd://duplicacy

TODAY=$(date -I)

LOGDIR=/LaCie/data/snapshot/log

if [ ! -d $LOGDIR ]; then
    mkdir -p $LOGDIR
fi

logfile=$LOGDIR/duplicacy-$TODAY.log

touch $logfile
rm $logfile
touch $logfile

GLOBAL_OPTIONS="-verbose -background"
BACKUP_OPTIONS="-t ${ID}-${TODAY} -stats -threads 4"
PRUNE_OPTIONS="-id $ID -keep 0:60 -keep 7:14"

echo -e '-------- Start backing up ... --------' >> $logfile 2>&1
cd /
$PROGRAM $GLOBAL_OPTIONS backup $BACKUP_OPTIONS >> $logfile 2>&1

echo -e '\n-------------------------------------------------------------\n' >> $logfile

$PROGRAM $GLOBAL_OPTIONS prune $PRUNE_OPTIONS >> $logfile 2>&1
$PROGRAM $GLOBAL_OPTIONS prune >> $logfile 2>&1

echo -e '\n-------------------------------------------------------------\n' >> $logfile
```
The contents of my `filters` file:
```
-proc/
-run/
-tmp/
-mnt/
-*/.farm_out/
-*.iso
-*/lost+found/
-*/.local/share/Steam/steamapps/
-home/username/apps/
-home/username/tmp/
-home/username/pCloudDrive/
-home/username/.pcloud/
-home/username/.PlayOnLinux/
-data/software/
-data/tmp/
-*/.gnome/
-*/.mozilla/
-*/.thumbnails/
-*/Dropbox*/
-var/tmp/
-*.Trash*/
-home/username/mnt/
-*tmp/
```

The error message in the log file:
```
### Other log messages ###
Subdirectory home/username/ cannot be listed
### Other log messages ###

Backup for / at revision 1 completed
Files: 5296101 total, 1204G bytes; 5296101 new, 1204G bytes
File chunks: 249809 total, 1204G bytes; 97498 new, 511,289M bytes, 308,308M bytes uploaded
Metadata chunks: 364 total, 1,772M bytes; 364 new, 1,772M bytes, 467,768K bytes uploaded
All chunks: 250173 total, 1206G bytes; 97862 new, 513,062M bytes, 308,765M bytes uploaded
Total running time: 11:47:37
1 directory and 1053 files were not included due to access errors
```

The permission of my home directory:
```
drwxr-xr-x 64 username username 4.0K Feb 27 12:31 username
```

As root, I can list my home directory with no problems.

When I tried to restore files in my home directory, I got an empty directory. Restoring another directory not in my home directory worked as expected.

**Comment by gilbertchen** [comment]
This is strange.  For a sanity check, can you add a line `ls /home/username` to make sure the script is run as root?

Or run the backup command directly with the -dry-run option?

**Comment by xulongwu4** [comment]
Thanks for your quick reply. I tried with the -dry-run option and added the `ls` statement. I can see all my files in the home directory got listed correctly by the root account.

I did a bit debug here and I think I probably found the cause of this issue. I am using a cloud service called "pcloud". When this application is running, it automatically creates (mounts) a directory under `/home/username/pCloudDrive` and this directory is only accessible to the current user. The following is the output if I run `ls /home/username` as root:
```
oulongwu@gigabyte-aero15 ~ $ sudo ls -lthr
ls: cannot access 'pCloudDrive': Permission denied
total 60K
d????????? ? ?        ?           ?            ?  pCloudDrive
drwxr-xr-x 2 oulongwu oulongwu 4.0K Dec  6 01:03  Videos
drwxr-xr-x 2 oulongwu oulongwu 4.0K Dec  6 01:03  Templates
drwxr-xr-x 2 oulongwu oulongwu 4.0K Dec  6 01:03  Public
drwxr-xr-x 2 oulongwu oulongwu 4.0K Dec  6 01:03  Music
drwxr-xr-x 2 oulongwu oulongwu 4.0K Dec  6 01:03  Desktop
drwxrwxr-x 4 oulongwu oulongwu 4.0K Dec 10 15:11  software
drwxrwxr-x 4 oulongwu oulongwu 4.0K Dec 10 15:13  apps
drwxrwxr-x 3 oulongwu oulongwu 4.0K Dec 13 08:52  mnt
drwxrwxr-x 5 oulongwu oulongwu 4.0K Dec 25 14:35 'VirtualBox VMs'
drwxrwxr-x 2 oulongwu oulongwu 4.0K Dec 28 13:53  scripts
drwxrwxr-x 2 oulongwu oulongwu 4.0K Jan 18 22:45  travel
drwxr-xr-x 3 oulongwu oulongwu 4.0K Jan 20 10:16  Pictures
drwxr-xr-x 5 oulongwu oulongwu 4.0K Feb 19 08:54  Downloads
drwxrwxr-x 9 oulongwu oulongwu 4.0K Feb 26 23:51  tmp
drwxr-xr-x 5 oulongwu oulongwu 4.0K Feb 27 08:02  Documents
```

As can be seen, the root account cannot access the pCloudDrive folder. In addition, in the log file generated by duplicacy, I see the following error message:
```
Failed to list subdirectory: lstat /home/oulongwu/pCloudDrive: permission denied
```
indicating that this folder was not read by duplicacy.

I tried quitting the pcloud application and ran duplicacy with the previous script. The files in my home directory got backed up correctly. Thus I am pretty sure this application is what caused the issue.

However, I don't understand why the existence of this directory can hinder the backup process of all the other folders in my home directory. First of all, this folder is included in my exclude pattern as shown previously. I expect it to be ignored by duplicacy. Second, I am using some other software for local backup as well, including restic. I also ran it as root. It backs up my home directory correctly. Thus I don't expect this cloud service would break down the backup of my home directory. If you need more information please let me know.

**Comment by gilbertchen** [comment]
Here is the code that reads the list of files under a directory:

https://github.com/gilbertchen/duplicacy/blob/e07226bd621dcf03b15193e60ecbcb9efd3e797c/src/duplicacy_entry.go#L447-L450

So if there is any error reading the directory it will return the error immediately.  I don't think it is better to continue processing whatever is returned in `files` in this case, because according to the [doc](https://golang.org/pkg/os/#File.Readdir), ReadDir may stop at the entry that causes the error and ignore the rest, which means some entries may not be included depending on the read order and this may go unnoticed.

Of course the logically correct way is that ReadDir should ignore an error associated with an entry that is being excluded.  However, this requires a new ReadDir implementation that takes a list of excluded patterns.

**Comment by xulongwu4** [comment]
Thanks for your explanation. I think it makes sense to ignore the folder in this case. I will close this issue then.
