### ISSUE TITLE
check command yields inconsistent results

### ISSUE THREAD

**Issue by tophee** [gilbertchen/duplicacy#369]
I suppose there is a bug here somewhere:

~~~~
PS D:\> duplicacy check
Storage set to P:\Backup\Duplicacy\
Listing all chunks
Chunk 56690a4b01e0c2a4c97371a8423de8392a5c5e6ac1a6110a01ecab14dde8d809 can't be found
PS D:\> duplicacy check -a
Storage set to P:\Backup\Duplicacy\
Listing all chunks
All chunks referenced by snapshot ext_MEETGO at revision 1 exist
Chunk 92286e3aa7f0f80465bf2d0071ff860e11e00762acc805dc92fe826058b346d3 referenced by snapshot ALPHA_C at revision 1 does not exist
Chunk c7b8097f6ee78d5a0232807acfd6d709d10d522c083498afd319d8065541e1df referenced by snapshot ALPHA_C at revision 1 does not exist
Chunk 2128bc0dbc7ccd479d9eebd881906a7c491c8cbe223daa29d238fb26ca33dd64 referenced by snapshot ALPHA_C at revision 1 does not exist
Chunk 2bc95fb5f7c7e289e7615a1fa9edba2b5052b3f25c67891dabca614d1d5d1538 referenced by snapshot ALPHA_C at revision 1 does not exist
Some chunks referenced by snapshot ALPHA_C at revision 1 are missing
PS D:\>
~~~~

Note how the chunk reported missing with `duplicacy check` is not missing with `duplicacy check -a`.

**Comment by gilbertchen** [comment]
Are you still having this issue?  Is this a pcloud drive?

**Comment by tophee** [comment]
>Are you still having this issue?

No, can't reproduce it now.

>Is this a pcloud drive?

Yes. And I suppose we'll have to write that strange behaviour off on their account (i.e. the bug in their app that makes it not show some files even though they are available via the web interface). Though I'm not sure how that alone can explain duplicacy's strange behaviour:

If the output in the OP was the only time this occurred, one could explain it by assuming that between the execution of the two commands, the pcloud app changed which files it shows. But I tried the sequence of `duplicacy check` and `duplicacy check -a` several times, with the same results so we can rule out the possibility that the pcloud app made different files available at different times. 

The only possible explanation that I can see is that it made different files available depending on how they were accessed (i.e. with which command). Does duplicacy query files differently in the two versions of the check command?

**Comment by TheBestPessimist** [comment]
Pinging this: is the behavior still happening? Or maybe we could close the issue if it is not.

**Comment by tophee** [comment]
No, this was most likely due to pcloud.

**Comment by TheBestPessimist** [comment]
(that was a ping to gchen since only he or op can do it :D)
