### ISSUE TITLE
Storages are not compatible for the copy operation

### ISSUE THREAD

**Issue by dave-fl** [gilbertchen/duplicacy#372]
After reading through the quick start my assumption is that a best practice seems to be to backup on site and off site.

So I've setup a repository to backup to local storage along with an off site storage using Backblaze B2.  Given that I plan on putting my data onto Backblaze I'd like to encrypt.

After running setup I ran

` duplicacy copy -from default -to offsite`

which resulted in the error: Two storages are not compatiable for the copy operation

I've tried with both my onsite storage having a password and not having a password.  Is this option supported with encryption and what is the suggested approach here?

**Comment by dave-fl** [comment]
You can close this, seems like I must make the local storage encrypted and then use the copy option

**Comment by gilbertchen** [comment]
It should be ok.  The `-bit-identical` option is only needed if you want to use rclone to sync the two storages.

**Comment by dave-fl** [comment]
Closing
