### ISSUE TITLE
Duplicacy almost stops uploading files after some time

### ISSUE THREAD

**Issue by christophetd** [gilbertchen/duplicacy#379]
I've been running a 80 GB backup to Backblaze B2 for approx 48 hours. At first, the speed was correct, but over the last 12-24 hours it has been very bad and is now close to 0. Here's what the network traffic looks like:

![image](https://user-images.githubusercontent.com/136675/37427489-e4d6db74-27c9-11e8-89b5-8dd7da447e8f.png)

(this only shows the last 60 seconds, but it's been consistently like that. Upload traffic is in blue)

The duplicacy process hasn't crashed or anything, and the output shows something like:

```
Packed file1
Packed file2
Packed file3
[...]
```

And is very slow but not stuck. The `duplicacy` process hardly uses memory or CPU:

![image](https://user-images.githubusercontent.com/136675/37427665-66031834-27ca-11e8-9627-dd676ba3876f.png)

(~1.8 % memory and ~0 % CPU)

Using `iotop` shows that the process also does very little (almost 0) disk I/O. A `strace` on the process (`strace -p PID -f`) shows that the process makes a lot of call to `getrandom` and `write` syscalls:

```
[pid   689] getrandom("S\255F\364O@\200\361\0\23"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200S\255F\364O"..., 4149) = 4149
[pid   689] getrandom("\26\22!\243KY\240\347\235;"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\26\22!\243K"..., 4149) = 4149
[pid   689] getrandom("\204\225$\262k\6\36d\275\200"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\204\225$\262k"..., 4149) = 4149
[pid   689] getrandom("o\275ca\300&\34\215\253X"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200o\275ca\300"..., 4149) = 4149
[pid   689] getrandom("\376uR\27{\2\313t\277\320"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\376uR\27{"..., 4149) = 4149
[pid   689] getrandom("\221\4\257\237C-)\0368\202"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\221\4\257\237C"..., 4149) = 4149
[pid   689] getrandom("\347\211)\33\225\253\3\275\266\343"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\347\211)\33\225"..., 4149) = 4149
[pid   689] getrandom("L*\16\342Y,.\201\230\367"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200L*\16\342Y"..., 4149) = 4149
[pid   689] getrandom("\10\275\370\t$\334\21{(\f"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\10\275\370\t$"..., 4149) = 4149
[pid   689] getrandom("\332\367v\342\201]g\t\357\21"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\332\367v\342\201"..., 4149) = 4149
[pid   689] getrandom("M\37\240\231;\22\357\377\214\364"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200M\37\240\231;"..., 4149) = 4149
[pid   689] getrandom("\367zw\211\242\245\236\333\241\211"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\367zw\211\242"..., 4149) = 4149
[pid   689] getrandom("\342\3462:9e\261$\224\241"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\342\3462:9"..., 4149) = 4149
[pid   689] getrandom("\201wo\325\r?Qo\10\n"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\201wo\325\r"..., 4149) = 4149
[pid   689] getrandom("\202A/\23\320\203\306\371\371="..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200\202A/\23\320"..., 4149) = 4149
[pid   689] getrandom("U\21\352\"\333\263\340\364\345\234"..., 16, 0) = 16
[pid   689] write(8, "\27\3\3\0200U\21\352\"\333"..., 4149) = 1823
[pid   689] write(8, "i\360\7\345YH\301\344*O"..., 2326) = -1 EAGAIN (Resource temporarily unavailable)
[pid   689] epoll_wait(4, [], 128, 0)   = 0
[pid   689] epoll_wait(4,  <unfinished ...>
[pid 30051] <... select resumed> )      = 0 (Timeout)
[pid 30051] futex(0x1312618, FUTEX_WAIT, 0, {tv_sec=60, tv_nsec=0}
.. etc
```

Note that the the calls to `futex` seem to block for several dozens of second and timeout.

Any idea on what's going on? It seems to me that duplicacy seems to be blocked by something else, but I have no clue why. I've tried closing any other program running and made sure nothing else is using the directory duplicacy is backing up, but to no avail.

OS: Ubuntu 17.10, 12 GB RAM, i7-3740QM

Thanks!

**Comment by christophetd** [comment]
I should also mention that my upload speed should be around 5-10 Mbps

**Comment by gilbertchen** [comment]
How many threads are you using?  If you use only one thread then the B2 upload server that you connect to may become very slow.

If you can find a way to close that particular socket that Duplicacy should connect to a different B2 upload server.

Otherwise, rerun the backup as `duplicacy -profile 127.0.0.1:6060 backup -stats -threads 4` and then you will be able to profile the program if the same issue happens again.

**Comment by christophetd** [comment]
Looks like this solves the issue. Thanks!
