### ISSUE TITLE
Backing up to two cloud storages with no local storage

### ISSUE THREAD

**Issue by RX14** [gilbertchen/duplicacy#382]
I'd like to backup to two cloud storage backends without having a local storage backend. The advice for having consistent backups is to use `copy`, but that would involve downloading all the chunks from one storage and uploading them to another.

Would it make sense to do something like this?
```
duplicacy backup -storage backblaze
duplicacy backup -storage wasabi -t tempoary
duplicacy copy -from backblaze -to wasabi
duplicacy prune -t tempoary
```

Would this only download a minimal amount of chunks from `backblaze`? Would this produce different revisions on the two storages? Should I perform the tempoary backup with a different snapshot id to avoid conflicting revision IDs?

Thanks for the software, loving it so far.

**Comment by wscott** [comment]
I am a bit confused. What problem are you hoping to solve compared to just back up to both destinations independently? What advantage is there to having the backup snapshots match? really.

If there is some bug in duplicacy that causes a backup to be corrupted then it could be related to the timing of prunes or transmission errors or bit flips while reading.  If the backup is in parallel then some of those cases may not repeat.

Downsides in independent backups:
- two copies of the cache data (not that big)
- need to scan disk twice? duplicacy is already so fast at that and the disk metadata will already be in memory

Even the case of doing a local backup and then copying to the remove is not obviously superior in my mind. Perhaps someone can explain what I am not getting or share some benchmarks.

**Comment by RX14** [comment]
It's not about speed it's about consistency and being absolutely certain you have the same data on both cloud storages.

**Comment by jeffaco** [comment]
@wscott I regularly back up my data to multiple independent cloud storage destinations. If something "goes wrong" (i.e. Backblaze drops a chunk, or whatever), then I have an alternate that I can look at.

In my case, I back up from one machine. But @RX14 suggestion is valid, particularly if I want to make the copy from some other machine, potentially in a faster network (or whatever).

**Comment by RX14** [comment]
I tried this and had to change the ID of the wasabi (second) backend to a tempoary ID or `copy` would error out saying the revision number already existed. Fair enough.

It's probably not worth doing this for anything but a first backup, and do the typical `copy` operation for incrementals.

**Comment by gilbertchen** [comment]
@RX14, I think you can add the wasabi storage twice, each time with a different repository id, and one is for direct backup and the other for copy:

```
duplicacy init backblaze b2://bucket
duplicacy add -copy backblaze wasabi1 wasabi1 wasabi://bucket
duplicacy add wasabi2 wasabi2 wasabi://bucket
duplicacy backup -storage backblaze
duplicacy backup -storage wasabi1
duplicacy copy -from backblaze -to wasabi2
```

This has the advantage of backing up to your wasabi account directly (to avoid unnecessary download from b2), and at the time time still having consistent backups on both storages.  If there are no file changes between two backups, then the copy command will not download any chunks from backblaze.

**Comment by RX14** [comment]
@gilbertchen yep, thanks. Should I add this to the wiki?

**Comment by gilbertchen** [comment]
@RX14 Please do!  Everyone is welcome to edit any page!

**Comment by RX14** [comment]
I've tried this on my actual large backup and it worked really well. I'll add this to the wiki.
