### ISSUE TITLE
Mountable snapshots?

### ISSUE THREAD

**Issue by christophetd** [gilbertchen/duplicacy#383]
Hi, 

While comparing duplicacy and restic, I found that restic has a very handy [feature](https://restic.readthedocs.io/en/latest/050_restore.html#restore-using-mount) which is the ability to mount any snapshot as a FUSE filesystem.

Are there any plans for such a feature with duplicacy?

Thanks!

(P.S. - I'm sticking to Duplicacy anyway, which for my use-cases seems to perform 20% better than restic :+1: )

**Comment by gilbertchen** [comment]
This feature has been requested before: #7.  I don't know how much work it is, but will look into it in a month.

**Comment by TheBestPessimist** [comment]
Could this be marked as duplicate of #7  and closed then?

**Comment by christophetd** [comment]
Closing to stay focused on #7. Thanks!
