### ISSUE TITLE
Can Duplicacy CLI have a -comment qualifier?

### ISSUE THREAD

**Issue by jeffaco** [gilbertchen/duplicacy#384]
I'm looking at scripting `duplicacy` on my Mac system.

Some basics:
1. I have several different repositories that I wish to back up (about 3 of them).
2. I just don't entirely trust cloud storage providers, so I have each backup on two independent cloud storage providers.
3. I want _independent_ backups to run concurrently (here, _independent_ means that they are backing up completely different repositories).

I have the regular set of tools available to me via bash scripting (what I'm most comfortable with given my Linux/UNIX background) like ps, grep, awk, etc.

I have no easy way to determine, using my set of tools, what repository is being backed up by `duplicacy`, so I'm having a problem implementing my scripting. It's trivial if I want no concurrent `duplicacy` jobs, but jobs on two independent repositories are completely safe to run.

Could `duplicacy` have a `-comment` qualifier that can contain any text I want? I'm thinking something like `duplicacy -comment officeDB backup -threads 2`? I like the idea of -comment being at the top level (not just for backup) so I could avoid concurrent operations of all sorts for a repository operations (prune, etc).

Thoughts?

The idea here: Parse this and completely ignore it.

Is there another way to achieve what I'm trying to do?

**Comment by gilbertchen** [comment]
Nice idea.  I think you can use the `-tag` option for the backup command if you don't use it already, but there isn't anything similar for other commands.

**Comment by jeffaco** [comment]
If I use the `-tag` option, that refers to a particular revision. Can I use the same tag, over and over, such that it would be assigned to multiple revisions? If not, then I don't think this would work.

I haven't done much with the Go language yet, but I'm thinking of learning it. Are you open to PRs if/when I get to start learning Go?

**Comment by gilbertchen** [comment]
The same tag can be applied to more than one revision, but unlike `-comment` it does have the side effect of being stored in the snapshot files.

Yes, I'll appreciate it if you can add this option.

**Comment by jeffaco** [comment]
I have a commit that, I believe, implements this. Easier than I thought! However, as a 'go' newbie, I'm not sure how to build Duplicacy and, much to my surprise, there wasn't a peep about it on the README.md page.

I have a GO workspace directory tree (`go/bin`, `go/src`, `go/package`). Under `go/src`, I have the duplicacy repository. But if I cd to there, I get:

```
$ go build
can't load package: package duplicacy: no Go files in /Users/jeff/local/gowork/src/duplicacy
$ 
```

As a guess, I went into the `duplicacy` folder (where the main module is) and tried there:

```
$ go build
duplicacy_main.go:23:2: cannot find package "github.com/gilbertchen/cli" in any of:
	/usr/local/go/src/github.com/gilbertchen/cli (from $GOROOT)
	/Users/jeff/local/gowork/src/github.com/gilbertchen/cli (from $GOPATH)
duplicacy_main.go:27:2: cannot find package "github.com/gilbertchen/duplicacy/src" in any of:
	/usr/local/go/src/github.com/gilbertchen/duplicacy/src (from $GOROOT)
	/Users/jeff/local/gowork/src/github.com/gilbertchen/duplicacy/src (from $GOPATH)
$ 
```

Can you give me basic guidelines of how to build Duplicacy? Once I test, I'll submit a PR for my changes to support this. Thanks so much!

**Comment by gilbertchen** [comment]
This is the wiki page on installation: https://github.com/gilbertchen/duplicacy/wiki/Installation

Specifically there is a section on how to build from a fork.

**Comment by jeffaco** [comment]
Closing this issue since `-comment` has been added to duplicacy.
