### ISSUE TITLE
Backup of Veracrypt container

### ISSUE THREAD

**Issue by sergeevabc** [gilbertchen/duplicacy#393]
Dear Gilbert,

Found [this][1] while looking for an advice on a proper Duplicacy setup to backup [Veracrypt][2] container. It is said 1M chunk size is a way to go, which is obviously set via ```duplicacy init -c 1M test d:\test```, but is there a switch to choose fixed property instead of variable?

Now let me share some observations. 

```
Container is 1G, chunk size set to 1M.
829 File(s)  1 078 014 488 bytes     initial backup
845 File(s)  1 097 660 165 bytes     3 small files (~15K) added to container
855 File(s)  1 109 801 342 bytes     1 small file deleted

Container is 1G, chunk size is not set (default is used, which is 4M now).
216 File(s)  1 077 970 306 bytes     initial backup
225 File(s)  1 108 179 370 bytes     3 small files (~15K) added to container
234 File(s)  1 138 388 402 bytes     1 small file deleted
```

Minor changes, notable backup growth.
What would you say? Perhaps there is another strategy to try?

[1]: https://duplicacy.com/issue?id=5705591590748160
[2]: https://www.veracrypt.fr/en/Home.html

**Comment by dcflachs** [comment]
> Perhaps there is another strategy to try?
Best option would be to mount the volume and backup the files inside. My understanding is that the structure of veracrypt containers just doesnt play well with de-duplication. Small changes to files within the container do not necessarily equate to small changes in the encrypted file that is the container.

**Comment by gilbertchen** [comment]
The recommended settings for backing up a veracrypt volume is `duplicacy init -c 1M -max 1M -min 1M test d:\test`.  This enables the fixed-size chunking algorithm which should perform better than the default variable-size chunking algorithm for files that are always updated in-place.

**Comment by sergeevabc** [comment]
Let’s try @gilbertchen’s advice and see the figures.

```
Container is 1G, chunk size is set to 1M, fixed.
1030 File(s)  1 078 022 286 bytes     initial backup
1037 File(s)  1 082 292 261 bytes     3 small files (~15K) added to container
1044 File(s)  1 086 562 262 bytes     1 small file deleted
```

And if someone is interested in @dcflachs’s approach, here is the report as well.
```
Folder in Veracrypt’s container: 1297 File(s), 879 265 178 bytes
Routine is initialized as follows: duplicacy init -e z:\ d:\test (so chunk size is 4M, variable)

181 File(s)    519 715 674 bytes     initial backup
186 File(s)    519 898 950 bytes     3 small files (~15K) added to container
188 File(s)    520 037 096 bytes     1 small file deleted
```

**Comment by TowerBR** [comment]
@dcflachs, the problem with mounting and backing up files is that if you're using Veracrypt, it's because you have files to protect, and you may not want these files opened during the backup procedure.

@sergeevabc , I did some tests comparing performance with fixed and variable chunks, one of them is this one:

[backup_software_testing/test_04_Evernote_Duplicacy.md](https://github.com/TowerBR/backup_software_testing/blob/master/test_04_Evernote_Duplicacy.md)

I know it is not a Veracrypt file, but it is an Evernote database, which behaves similarly: small parts changed from a large file.

Although I did not get to document Test #11 of the list (which would be with a Veracrypt file), today I back up some files of this type, and I can tell you that for small changes Duplicacy generates something between a few hundred KB and a few Mb:

```
2018-03-31 23:38:59.907 INFO BACKUP_STATS All chunks: 3451 total, 3,448M bytes; 1 new, 225K bytes, 186K bytes uploaded
```
```
2018-03-29 19:13:14.255 INFO BACKUP_STATS All chunks: 3452 total, 3,448M bytes; 13 new, 11,490K bytes, 11,495K bytes uploaded
```

(This file above has ~ 3.5Gb and has minor daily modifications)

**Comment by dcflachs** [comment]
I do understand the reasons one would use veracrypt, as I am a user myself. In my experience I have found that no deduplicating backup software is particularly effective when it comes to backing up veracrypt containers. Further since the container must be opened to make changes to its contents, it would seem to me that a backup could be performed while mounted. I dont mean to dissuade further discussion on the topic, and please correct me if you have information to the contrary.

**Comment by sergeevabc** [comment]
@TowerBR, thanks for your input, Please, be aware that your graphs might be a bit confusing, because you talk of Duplicacy there, but measure things with RClone, another backup tool. 

> You have files to protect and you may not want these files opened during the backup procedure.

This scenario is out of my threat model:
- if I am not able to mount a container, then no changes are introduced, than nothing to backup
- encrypted containers are not backed up along with other data as a part of some recurring routine

If someone needs to backup encrypted data with a low overhead, then [CPPCryptFS][1] is the way to go. It is an encrypted overlay filesystem written in Go, which mounts folder as a virtual disk and encrypts its contents per file on-the-fly, so you get something resembling a folder with Duplicacy-encrypted data. I found two possible drawbacks:
- you needs to install a driver, so CPPCryptFS, being a single file, is not portable
- you could hardly restore a specific file with Duplicacy, because it would have an encrypted name

Actually, the latter point is true for Veracrypt as well, i.e. you have to restore large container first.
In the end, I believe @dcflachs’s approach is the most balanced so far.

[1]: https://github.com/bailey27/cppcryptfs

**Comment by gilbertchen** [comment]
I may have a different expectation, but isn't this good enough:

> Container is 1G, chunk size is set to 1M, fixed.
> 
> 1030 File(s)  1 078 022 286 bytes     initial backup
> 1037 File(s)  1 082 292 261 bytes     3 small files (~15K) added to container
> 1044 File(s)  1 086 562 262 bytes     1 small file deleted

**Comment by sergeevabc** [comment]
@gilbertchen, in this thread we have recollected possible approaches for backing up encrypted files and, no doubt, you have been doing a great job on improving Duplicacy, which is why all of them come with benefits.

**Comment by TowerBR** [comment]
@dcflachs , Sorry, don't get me wrong. I was just showing a way to back up Veracrypt containers. As I back up automatically and when I'm not logged in, Veracrypt volumes are not mounted, so I don't use the strategy you presented (per file).

I do automatic daily backups of some of these Veracrypt containers, and I'm very pleased with the result (thanks Gilbert!).

As the backup job add a few Mb a day, it's quite comfortable in terms of storage space (Dropbox) and upload.

**Comment by TowerBR** [comment]
>Please, be aware that your graphs might be a bit confusing, because you talk of Duplicacy 
> there, but measure things with RClone, another backup tool.

It is just a form of cross control of the "experiment", using another tool to measure occupied spaces.
