### ISSUE TITLE
Script for cron (run task in background)

### ISSUE THREAD

**Issue by sttyru** [gilbertchen/duplicacy#400]
Hello!

I need to backup of some directory by schedule. I created scripts with the next content:

```
#!/bin/bash
fdate4fs=$(date +"%Y%m%d_%H%M%S")
# Configuration of the storage and another settings
source /usr/local/etc/dup_export
target=$1
#
(cd $2 && exec duplicacy -background -log backup > /var/log/duplicacy/$target_$fdate4fs.log)
exit 0;
## Example: ./job.sh io /io
```
If I run the script in the shell (with root permissions) operation is success, but if I trying to schedule the task with the cron (with root-privileges too) output log-file is an empty and no new files was created at the target storage (GDrive).

`/usr/local/etc/dup_export` contains correctly variables and settings. I tested a task in foreground not once.

What I should do for fix my script?

**Comment by gilbertchen** [comment]
I would guess the Duplicacy executable isn't in the PATH when the cron job is running?  Maybe using the absolute path to the Duplicacy executable will work.

**Comment by sttyru** [comment]
Hi.

You know, you're right. :)

Thank you!

_Sorry for my newbie's question._
