### ISSUE TITLE
Snapshot storage efficiency 

### ISSUE THREAD

**Issue by dcflachs** [gilbertchen/duplicacy#404]
I have been acquainting myself with various backup solutions recently including duplicacy and duplicati. If i understand correctly both programs use JSON "files" to store their "snapshots". I noticed that for files with many chunks duplicati uses a secondary binary format to store chunk hash lists, which are then referenced by the JSON "snapshot" file (described in their [Core Algorithm](https://github.com/duplicati/duplicati/wiki/Developer-Documentation)) It is my understanding that duplicacy uses pure JSON. Is a similar strategy for chunk hash storage something worth considering for duplicacy? Does anyone have a notion as to whether it might improve snapshot storage efficiency without adversely effecting backup/restore time/complexity?

**Comment by gilbertchen** [comment]
Storing the chunk list in binary form would certainly save some space, but not much.  For a 1TB backup  with the default 4M average chunk size, the saving is about 1Tb/4M * 32 bytes which is about 8M bytes.  Besides, this chunk list is also deduplicated in Duplicacy so the actual saving would be even smaller.  So I think it is not worth the added complexity.
