### ISSUE TITLE
"Failed to download the chunk … INTERNAL_ERROR" during restore

### ISSUE THREAD

**Issue by s4y** [gilbertchen/duplicacy#407]
I'm trying to restore (using v2.1.0 on Arch Linux), and running into this situation:

```
Storage set to gcd://[snip]
Loaded 10 include/exclude pattern(s)
Skipped non-regular file [snip]
Restoring / to revision 1925
Downloaded chunk 713 size 5811567, 114KB/s 4 days 19:37:19 0.0%
Downloaded chunk 716 size 5082102, 190KB/s 2 days 21:04:37 0.0%
Failed to download the chunk [long_hash]: stream error: stream ID 61; INTERNAL_ERROR
```

If I retry, it always fails on the same chunk. What can I do next to troubleshoot, get past this, or (other)?

**Comment by s4y** [comment]
Eep. I cannot — I get a network error. I'll try to look into this, but if I can't get that chunk, what's the right way to proceed to get back as much data as I can?

**Comment by gilbertchen** [comment]
If you can't download that file on the Google Drive website, I'm sure Google will be very interested in know why and should be able to help you get back that file.

If you just want to restore your data as much as possible for now, you can first run `duplicacy -d restore -r revision` which will show which files that chunk belongs to and then use an exclude pattern to skip the affected files:

```
duplicacy restore -r revision -- -relative/path/to/affected/files
```

**Comment by s4y** [comment]
Sweet. I’m working on the Google part and, in the mean time, finding the troubled file with `-d` and excluding it let me move forward. Thank you!

I don’t *think* there’s anything left on this bug, but feel free to reopen if there is.

**Comment by s4y** [comment]
(…and I’m considering how to add redundancy to my backup strategy going forward. Another cloud provider? A tape library? Time will tell.)
