### ISSUE TITLE
What license to use for a derived tool?

### ISSUE THREAD

**Issue by christophetd** [gilbertchen/duplicacy#408]
Hi, 

I wrote a small duplicacy wrapper to easily setup automated backups: https://github.com/christophetd/duplicacy-autobackup

I included a disclaimer regarding duplicacy's license:

> ## Disclaimer
> 
> This project uses [Duplicacy](https://github.com/gilbertchen/duplicacy), which is free for personal use but requires [purchasing a licence](https://duplicacy.com/buy.html) for non-trial commercial use. See the detailed terms [here](https://github.com/gilbertchen/duplicacy/blob/master/LICENSE.md).

Does that look fine to you? Let me know if you have any concerns!

**Comment by gilbertchen** [comment]
I think a wrapper isn't a derived work so you have the freedom to choose any license.  This is similar to the situation where a tool calling GPL'ed software as a separate process should not be regarded as a derived work and therefore should not be bound by GPL.

Feel free to add a link to this page: https://github.com/gilbertchen/duplicacy/wiki/Scripts-and-utilities-index

**Comment by christophetd** [comment]
Thanks for the reply. I added a page to the wiki. Cheers!
