### ISSUE TITLE
Filters Include/Exclude Pattern

### ISSUE THREAD

**Issue by markusweb** [gilbertchen/duplicacy#410]
where do i put the file for include/eclude patterns? i can use eg

`-foo/bar/
+foo/*`

to exclude the foo-bar-folder. but where do i put the file with this filter?

markus

**Comment by TheBestPessimist** [comment]
You place it inside the folder named `.duplicacy` (notice the `.`), inside the file `filters` (no extension).
=> `.duplicacy/filters`

Also, each rule must be placed on a different line:
correct: 
```
-foo/bar/ 
+foo/*
```

incorrect:
`-foo/bar/ +foo/*`

**Comment by greendog99** [comment]
Also, the ordering of the filters matters. This is explained (as is the file location) in https://github.com/gilbertchen/duplicacy/wiki/Include-Exclude-Patterns
