### ISSUE TITLE
Unclear Include Exclude Patterns documentation for Windows drive letters

### ISSUE THREAD

**Issue by DreamFlasher** [gilbertchen/duplicacy#418]
If my repository is D:\ how are my exclude patterns supposed to look like? Say I want to exclude the Downloads folder. Which of the three is correct:

```
-D:/Downloads/
-Downloads/
-/Downloads/
```

Apart from that it would have been helpful to write in the beginning that these patterns go in a file named filter -- not at the far end.

**Comment by tophee** [comment]
The paths in the filters file are relative to the repository path. So I think `D:\Downloads\` wont work and neither will `-/Downloads/`.
`-Downloads/` is correct.

Check out the wiki manual at https://github.com/gilbertchen/duplicacy/wiki/Include-Exclude-Patterns

**Comment by DreamFlasher** [comment]
Thank you. I read the documentation multiple times before posting this and searched for tickets and found some that show that actually a lot of people have problems understanding this. I assume most of us are not stupid, so I still believe that either the documentation needs a rewrite or the feature.

**Comment by DreamFlasher** [comment]
@tophee I updated the wiki, which solves this issue.
