### ISSUE TITLE
How I can exclude node_modules

### ISSUE THREAD

**Issue by zer09** [gilbertchen/duplicacy#422]
Hello good day, how I can exclude node_modules directory?

I have this in my filters
```
+node/*
e:(?i).*node_modules.*
```

but running the dry run I can still see ```LIST_ENTRIES Listing node/somedirectory/node_modules/```

thanks

**Comment by TheBestPessimist** [comment]
Can you mix regex and non-regex ignores at the same time? didn't know you could.

**Comment by zer09** [comment]
I am sorry I don't about that,  I just found duplicacy a few days ago. But what is the correct to do that?
BTW that regex above, I just copied it from the examples and tried to edit.

**Comment by TheBestPessimist** [comment]
Maybe this works?
```
+node/*
-node/*/node_modules/
```

**Comment by zer09** [comment]
tried it but, it is still listing the node_modules

![screenshot from 2018-05-04 16-31-54](https://user-images.githubusercontent.com/780780/39619045-eaad6d8a-4fb8-11e8-95de-ea1b3459f951.png)

**Comment by gilbertchen** [comment]
The order matters, so this should work:
```
-node/*/node_modules/
+node/*
```

You can mix regex and wildcard patterns, so this should work too:
```
e:(?i).*node_modules.*
+node/*
```

**Comment by zer09** [comment]
Thanks you so much
