### ISSUE TITLE
Discourse forum

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#427]
This has been mentioned a few times on the duplicacy website, so i though i could add it here as well.

I would mention the issues, but there's no search in there :oh-darn:.

In case @gilbertchen is interested, i have a testing discourse running on my own pc [here](https://chat.tbp.land/), with some interesting plugins, and it only took me 30 minutes to get it up and running along with LetsEncrypt certificate and https only.

My pc is not always on though, so you may or may not need to check the website from time to time 😵, however the [discourse meta](https://meta.discourse.com) is always available and has a lot helpful folks (including, of course the discourse creators -- they're really nice!).

I have also seen @tophee hanging around on meta, and i also assume he knows discourse better than i do.

If @gilbertchen wants, i'd be willing to have a go at configuring, at least for testing, a discourse instance (and eventually try and see how sso works with duplicacy's own website).

**Comment by tophee** [comment]
>I would mention the issues

Here they are:

https://duplicacy.com/issue?id=5696101055201280

https://duplicacy.com/issue?id=5753627847163904

> it only took me 30 minutes to get it up and running

Wow, not bad. I know that they advertise the install instructions as taking only 30 minutes, but I have set up 3 forums so far and although I got significantly faster each time, I think it always took longer than that. One explanation might be that if you just set up a test instance, it's easier to just go ahead and try stuff out, but I wanted to get everything right...

**Comment by TheBestPessimist** [comment]
i don't have multicontainer (web, nginx, postgress)
, just one container, with a bunch of plugins, settings and ssl. 
It's my first install ever, but i think that now i could do it in as_long_as_it_takes_to_download_everything. The installer is really streamlined, at least in discourse V 2.0.

**Comment by gilbertchen** [comment]
If there is an easy way to delegate the account signup and login management to the current Google App Engine app then I'll move to Discourse.

**Comment by TheBestPessimist** [comment]
Well, that SSO: Single Sign On.
Now, i don't know how you login on your current website, but here we can find some resources:
- [Configuring Google login for Discourse](https://meta.discourse.org/t/configuring-google-login-for-discourse/15858)
- [Official Single-Sign-On for Discourse (sso)](https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045)

**Comment by TowerBR** [comment]
Just an "up" to prevent this idea from dying. As shown in the @tophee  links, I've commented on this before.

In addition to the facilities of access, search, etc., an optimized forum constitutes a rich knowledge base, which feeds on its own. And it lowers the demands of support ...

**Comment by TheBestPessimist** [comment]
By 

>  And it lowers the demands of support ...

I understand that people will still ask the _same damn questions_ every single time, but in this case they will be simply pointed to a post in the wiki category with all the explications and details needed. 

It is so much easier to just do this instead of trying to remember every response each time, and then type it!

**Comment by gilbertchen** [comment]
I'll tackle this problem in about 2 weeks.

**Comment by TheBestPessimist** [comment]
From my point of view, there's no need to handle this alone, I'll gladly try and help with as much as i can. Both with syadmin tasks and also with forum admin (since there's a lot of customization possible, and you might want some of it)

**Comment by gilbertchen** [comment]
I'll certainly need some help here.  We can start with the login part.  If I implement a redirect url on duplicacy.com that can handle the SSO request as described in https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045, would you be able to incorporate that in your test site?

**Comment by TheBestPessimist** [comment]
Since my site allows for "facebook/google/whatever/social login" and sso doesn't work with that -- I'll have to create a new test site for you and configure that one. First i gotta see how to do that (2 sites on the same machine).
I'll hopefully try to do this tonight (timezone = UTC+2), after work.

**Comment by TheBestPessimist** [comment]
Ah, of course @gilbertchen if you already have an available VPS (1 core, 1gb ram, 10gb ssd) with ubuntu installed, we could straight install there and test with it (and in this case you'll also see how installing/modifing stuff works)

**Comment by tophee** [comment]
@gilbertchen What I'd recommend is that you simply start by setting up a discourse instance (either on an existing server or you spin up a new VPS at one of the many providers (Note that the specs that TheBestPessimist mentions above only work if you have run nothing else but discourse on that server. They are the absolute minimum and require that you set up a Swap partition). When setting up discourse, you will need to know under which (sub-)domain it will be accessible, so it makes sense to use the "real" one from the start (e.g. forum.duplicacy.com or community.duplicacy.com). It you set it up as test.duplicacy.com, you'll only run into problems when trying to change it later.

The definitive instructions to follow are here: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

Once you have that setup completed, we can take the next step and figure out the best way to login. Everything is still possible at that point.

**Comment by TheBestPessimist** [comment]
Having the vps from the beginning would be helpful indeed. 
About the specs though: wouldn't a 1gb ram vm be enough for our testing? Afterwards the vm specs can be increased w/o many problems depending on what needs arise.

For my vm i have 2 gb ram and 1 cpu core and i think it moves fast enough for me and 5 other people's needs.

**Comment by TheBestPessimist** [comment]
I have the test forum ready (though, as tophee said, we can use the final one right from the start).
Just tell me when we will start testing and i'll switch it on!

**Comment by gilbertchen** [comment]
https://forum.duplicacy.com is alive!

I've done the login part.  Now you can use your account registered on duplicacy.com to log in.  What is left is to import existing posts on duplicacy.com to Discourse.  Can anyone help me with that?

**Comment by TheBestPessimist** [comment]
Nice! Congratulations.

**Comment by TowerBR** [comment]
Nice! Thanks a lot!

**Comment by TheBestPessimist** [comment]
Ladies and gents, @gilbertchen has done it.

Closing this as fixed ^_^
