### ISSUE TITLE
Not prompted for password during backup

### ISSUE THREAD

**Issue by haakom** [gilbertchen/duplicacy#432]
I'm not being prompted for storage password when doing backups to encrypted storages. Am I misinterpreting how things should work?

Expected behavior:
- Enter: duplicacy backup -storage $storage -threads $num threads 
- duplicacy promts me for password to open storage to check for differences and establish what needs          to be backed up.
- Enter storage password
- Backup starts

What actually happens:
- Enter: duplicacy backup -storage $storage -threads $num threads 
- Backup starts without prompting for password

**Comment by TheBestPessimist** [comment]
As long as the backup works, there's no problem.

If you ran duplicacy commands 2 times, the password is already saved as a environment variable, that's why you're probably not asked for the password again.

**Comment by haakom** [comment]
That is certainly possible. However, it also happens even after I've turned the computer completely off as well. I even tried using BleachBit to wipe all the temporary stuff and rebooted after that. Still happens...

**Comment by gboudreau** [comment]
Duplicacy tries to remember your password using your platform default secure keystore: Keychain on Mac, gnome-keyring on Linux, Data Protection API on Windows.  
Ref: https://github.com/gilbertchen/duplicacy/wiki/Managing-Passwords
