### ISSUE TITLE
Permission denied SSH FX PERMISSION DENIED

### ISSUE THREAD

**Issue by ccdanieldb** [gilbertchen/duplicacy#444]
Hello,
 I get a ("Permission denied" (SSH_FX_PERMISSION_DENIED)) error when trying to run the init command.  Please see below for the output.  I also logged on to the server I am trying to push the backup to with sftp to show that I could log on.  

root@duplicacy0:/mnt/YI export # /root/go/bin/duplicacy init -e stuff sftp://pi@10.0.1.203//media/
Enter SSH password:
Enter storage password for sftp://pi@10.0.1.203//media/:
Re-enter storage password:
Failed to configure the storage: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
root@duplicacy0:/mnt/YI export # sftp pi@10.0.1.203
pi@10.0.1.203's password: 
Connected to 10.0.1.203.
sftp> ls
sftp> cd /
sftp> ls
bin         boot        dev         etc         home        lib         lost+found  media       mnt         opt         proc        root        run         sbin        
srv         sys         tmp         usr         var         
sftp>

**Comment by TheBestPessimist** [comment]
check if user pi has access to the folder media, and can read/write there, not just ls on root.
create a text file with nano in media and see if that works.

From what i know, which isn't much SSH_FX_PERMISSION_DENIED means that you don't have access to the folder on the remote pc.

**Comment by ccdanieldb** [comment]
You are correct.  The below works just fine.  I need to fine out how permissions work in FreeNAS.  

Thanks again for your help.  

/root/go/bin/duplicacy init -e Stuff sftp://pi@10.0.1.203//home/pi/test/
