### ISSUE TITLE
Support for Wasabi us-west-1 region

### ISSUE THREAD

**Issue by plasticrake** [gilbertchen/duplicacy#471]
I am able to create and use a bucket created on `us-east-1`, but I can't use a bucket created on the new `us-west-1` region

Duplicacy: 2.1.1
Mac OSX: 10.13.6

`duplicacy init test wasabi://us-west-1@s3.wasabisys.com/west-bucket-name`
```
Failed to download the configuration file from the storage: BadRequest: Bad Request
	status code: 400, request id: ***, host id: ***
```

I also tried specifying us-east-1 on a us-west-1 bucket:
`duplicacy init test wasabi://us-east-1@s3.wasabisys.com/west-bucket-name`
```
Failed to configure the storage: AccessDenied: Access Denied
	status code: 403, request id: ***, host id: ***
```

**Comment by gilbertchen** [comment]
The endpoint for the `us-west-1` region is `s3.us-west-1.wasabisys.com`, so the command should be:

```
duplicacy init test wasabi://us-west-1@s3.us-west-1.wasabisys.com/west-bucket-name
```

See this article for details: https://wasabi-support.zendesk.com/hc/en-us/articles/360005022391-How-do-I-access-different-Wasabi-storage-regions-from-my-storage-app-

**Comment by plasticrake** [comment]
Thanks @gilbertchen 🤦‍♂️ 

It was confusing as I can access the bucket using cyberduck @ s3.wasabisys.com just fine. Didn't know the URL would be different.

Would if be helpful if I updated the wiki with this info? https://github.com/gilbertchen/duplicacy/wiki/Storage-Backends

**Comment by TheBestPessimist** [comment]
Go for it @plasticrake !

**Comment by plasticrake** [comment]
I updated the wiki. Thanks!
