### ISSUE TITLE
Add "size of cache directory" to comparison table

### ISSUE THREAD

**Issue by roweryan** [gilbertchen/duplicacy#48]
duplicity is unusable if you have a lot of data, it uses too much space to store copies of indexes, whereas obnam does not. Maybe you could write about how duplicacy handles this.

**Comment by gilbertchen** [comment]
In designing Duplicacy we pay attention to the cache usage and tried not to use too much cache.  When Duplicacy is used for backup only, the only thing stored in the local cache is the last snapshot file (a snapshot file contains a list of files and a list of referenced chunks so should be much smaller than the total size occupied by the backup).  When Duplicacy is used to run the prune command, it may save the list of referenced chunks for each known snapshot (but not the file list) in the cache.  Everything in the cache is also deduplicated to minimize the cache space used.

**Comment by gilbertchen** [comment]
I added to the User Guide a [section](https://github.com/gilbertchen/duplicacy/blob/master/GUIDE.md#cache)  about cache management in Duplicacy.  It is difficult to compare that with other software though, as they rarely talk about how the local cache is organized in their documentation.

Recently we did a [performance study of 4 backup tools](https://github.com/gilbertchen/backup-tools-comparison).  If you're interested you can run the experiments and compare the cache usage.
