### ISSUE TITLE
Restart initial backup after crash: wrong speed reported

### ISSUE THREAD

**Issue by gboudreau** [gilbertchen/duplicacy#492]
- Start initial backup (see #491 for details)
- Crash (or maybe just stop the backup at some point using `Ctrl-C`; again see #491)
- Re-start the initial backup:
```
# duplicacy -log backup -stats -threads 1 -hash
```

The transfer speed reported by duplicacy is wrong; I think it counts the data it skips (because it's already uploaded) as transferred, and thus at the beginning, it thinks it transferred a lot of data in a small amount of time, and as upload continues, the speed reported decreases.

**Comment by TheBestPessimist** [comment]
That's exactly what happens.

This issue is a duplicate of: https://github.com/gilbertchen/duplicacy/issues/128. Could you add a comment there (or maybe +1 the OP) and close this one?

**Comment by gboudreau** [comment]
Totally; sorry for the dupe.
