### ISSUE TITLE
Files get deleted from a revision if they can't be accessed for permissions reasons

### ISSUE THREAD

**Issue by jturcotte** [gilbertchen/duplicacy#493]
I'm trying out duplicacy on macOS, trying to backup two users from the same machine.
I've setup the repository in /Users and used filters to just include directories I want to back up in both accounts. I don't want to mess up with permissions so I just assumed that I'll run `duplicacy backup` with sudo

It works quite nice, but the issue is that once I forgot to run the command with sudo, and instead of getting an error telling me it can't access some directories not excluded by the filter, duplicacy just assumed that the files disappeared, and removed them from that revision.

I don't know if it would make sense to abort and return an error when any of the walked directories can't be entered, but a warning telling me to check permissions before pruning the previous revision would have saved me from having to reupload pruned chunks to my offsite storage. Especially if the denied permissions would result in files being deleted from the snapshot.

**Comment by jturcotte** [comment]
Here is a more concrete example, you do see that "1 directory" was "not included", but you don't get any info that this resulted into a destructive outcome. Personally I would prefer the snapshot of those files to retain their last state (which is more likely than them being deleted behind that curtain) than seeing them all go away from my backup almost silently. If that wouldn't cause undesirable side effects, a more explicit warning and a non-zero return value would be ideal. Otherwise some kind of report "X files added, Y files modified, Z files deleted" could also make this kind of situation more convenient to detect.

It's already not very easy to know which file is actually backed up, it's the total number of chunks listed in the `copy` command which got reduced by 25% that raised the alarm in my case. But users might run this in some cron job, it could take a while before they notice.

```
> mkdir backup
> mkdir test
> cd test
> mkdir secret
> touch secret/mine
> duplicacy init test $PWD/../backup/
[PWD]/test will be backed up to [PWD]/test/../backup/ with id test
> duplicacy backup 
Storage set to [PWD]/test/../backup/
No previous backup found
Indexing [PWD]/test
Packed secret/mine (0)
Backup for [PWD]/test at revision 1 completed
> chmod 700 secret
> sudo chown root:staff secret
> duplicacy backup 
Storage set to [PWD]/test/../backup/
Last backup at revision 1 found
Indexing [PWD]/test
Failed to list subdirectory: open [PWD]/test/secret: permission denied
Subdirectory secret/ cannot be listed
Backup for [PWD]/test at revision 2 completed
1 directory was not included due to access errors
> echo backup return code: $?
backup return code: 0
> duplicacy diff -r 1 -r 2
Storage set to [PWD]/test/../backup/
- 0 2018-09-13 00:17:53 0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8 secret/mine
```

I tried `duplicacy -v -debug backup`, but I can't find anything usuful in the output for this situation either.

**Comment by jturcotte** [comment]
Returning a non-zero return code is what I usually expect of a program dealing with permission denied issues, but I understand that this could be annoying in other situations since I didn't explicitly say that the secret directory was important to me.

Is there a way I could print the diff of the last backup with its previous revision in my script without having to parse too much command output? This would give me the overview I'm looking for.

**Comment by TheBestPessimist** [comment]
Not sure here, but from the guide above try the commands: diff, cat or history

**Comment by jturcotte** [comment]
Alright, thanks for your help. It seems like you're satisfied with the current behavior, so I'll close the issue.
