### ISSUE TITLE
Regression: v2.1.1 brings back Azure upload chunk / connection timed out errors

### ISSUE THREAD

**Issue by jeffaco** [gilbertchen/duplicacy#507]
In issue #361, I reported problems. These were fixed in Duplicacy `v2.1.0f`. Some of the errors were apparently in the Azure Go communications code, as I understand it.

These issues appear to be back in Duplicacy `v2.1.1`, unfortunately. Please see the following log file:

First:

```
Uploaded chunk 75838 size 3097840, 14.51MB/s 12:35:55 35.3%
Uploaded chunk 75829 size 11451571, 14.51MB/s 12:35:53 35.3%
Uploaded chunk 75839 size 1345790, 14.51MB/s 12:35:52 35.3%
Failed to upload the chunk 5fdeabae43817238cba56cc2f1c2a5b4248f70b20b9a20de1af84770cb1789b8: Put <path>: write tcp 192.168.1.125:59208->52.191.176.36:443: write: broken pipe
Incomplete snapshot saved to <path>/.duplicacy/incomplete
```

After a while, upon restarting:

```
Uploaded chunk 140240 size 4130921, 19.64MB/s 04:50:35 66.3%
Uploaded chunk 140243 size 4148569, 19.64MB/s 04:50:35 66.3%
Failed to upload the chunk 3d110de3c9ddf3ebff1e1dd70e21af6fd1db2e4f06bdc4f0b0b8cb7cb43a0e86: Put <path>: write tcp 192.168.1.125:61306->52.191.176.36:443: write: broken pipe
Incomplete snapshot saved to <path>/.duplicacy/incomplete
```

And then, yet again:

```
Uploaded chunk 886 size 5205746, 10.75MB/s 08:43:07 1.3%
Uploaded chunk 889 size 2481916, 10.75MB/s 08:42:51 1.3%
Failed to upload the chunk bc76b25b7ad83e38a49afa46840ff6e163b2ee243439d7dd5612f4c25a3974b4: Put <path>: net/http: HTTP/1.x transport connection broken: write tcp 192.168.1.125:49478->52.191.176.36:443: write: broken pipe
Uploaded chunk 890 size 2892104, 10.76MB/s 08:42:32 1.3%
Uploaded chunk 891 size 2692402, 10.74MB/s 08:43:28 1.3%
Incomplete snapshot saved to <path>/.duplicacy/incomplete
```

I think that `broken pipe` should be an error that is retried, as was in `v2.1.0f`. Can this be taken care of?

**Comment by gilbertchen** [comment]
I believe the change for v2.1.0f was meant for a temporary fix and I may have forgot about it when releasing 2.1.1.  I'll try to get it in 2.1.2.

**Comment by jeffaco** [comment]
Status of this fix please? I don't believe it made it into `2.1.2`, did it? Do you have plans to try and get this into `2.1.3`?

**Comment by gilbertchen** [comment]
I did look at it before releasing 2.1.2 and realized that the fix was in 2.1.1 but somehow it didn't catch the `broken pipe` error.  My plan is to add retrying to the chunk uploader which would be a cleaner and more general fix.  And it should be in 2.1.3.

**Comment by jeffaco** [comment]
That's great, thanks so much for getting back to me!

**Comment by jeffaco** [comment]
I noted that release `v2.2.0` was just uploaded.

I'm still waiting for a release of `duplicacy` that has this problem resolved. Does `v2.2.0` contain the fixes for `broken pipe` errors when uploading?

Thanks for your input, I very much appreciate it.

**Comment by ljani** [comment]
I'm still seeing something similar with `v2.3.0` and Azure:

```
Failed to upload the chunk 9711c...: Put https://x.blob.core.windows.net/duplicacy/chunks/97/11c...: net/http: HTTP/1.x transport connection broken: write tcp 192.168.1.2:54521->20.38.103.68:443: wsasend: An existing connection was forcibly closed by the remote host.
```
