### ISSUE TITLE
using rclone as a backend for duplicacy

### ISSUE THREAD

**Issue by untoreh** [gilbertchen/duplicacy#521]
I am trying to use rclone as a duplicacy backend through webdav.
```
rclone serve webdav ./ --addr=domain:443 --cert domain.crt --key domain.key  --user dup --pass dup
```

```
dup -d add rclone test webdav://dup@davs.wadmin.ga/main # or //main 
```

and I get 
```
Failed to load the WebDAV storage at webdav://dup@domain/main/: Storage path /main/ does not exist
```
of course the `/main` path does exist in the cwd.

**Comment by gilbertchen** [comment]
I haven't tried running Duplicacy with rclone this way, but I'll take a look.

**Comment by untoreh** [comment]
for the intent of using rclone as a bridge, `sftp` works really well, and it is probably better than webdav
