### ISSUE TITLE
SFTP Cannot connect to Synology DSM

### ISSUE THREAD

**Issue by IpsmLorem** [gilbertchen/duplicacy#527]
Hi.
Duplicacy 2.1.2 cannot connect with SFTP to Synology DSM (DiskStation NAS):

`Failed to load the SFTP storage at sftp://user@nas.home/duplicacy: ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [aes128-cbc 3des-cbc aes192-cbc aes256-cbc]
`.
Is there a way to change cypher suite ?

**Comment by gilbertchen** [comment]
Unfortunately there isn't.  Which version of DSM are you running?

It may be possible to change the supported ciphers on Synology.  Or if you can compile from the source then it is easy to change the ciphers.  We're already doing this for HiDrive:

https://github.com/gilbertchen/duplicacy/blob/bebd7c4b7767a09c6906240e0d196268cbcdc4f2/src/duplicacy_sftpstorage.go#L60-L62

**Comment by IpsmLorem** [comment]
Latest DSM 6.2. It uses worse cypher suites and very few one :/

**Comment by deekue** [comment]
This is a workaround, but I run SFTP in a Docker container to avoid using the odd SSH in Synology's DSM.  

https://github.com/deekue/duplicacy-docker-sftp

**Comment by IpsmLorem** [comment]
There is a way to change the ciphers into the DSM UI. I'll try that.

**Comment by IpsmLorem** [comment]
I can confirm, it works by changing the SSH cypher suite to high :)
Issue closed

**Comment by leerspace** [comment]
@IpsmLorem are you running into this issue? https://forum.duplicacy.com/t/chunk-uploading-error-with-synology/1622/2

**Comment by IpsmLorem** [comment]
> @IpsmLorem are you running into this Synology issue? https://forum.duplicacy.com/t/chunk-uploading-error-with-synology/1622/2

Damn, you're right !
I fall in this pit. Thank you very much.
