### ISSUE TITLE
Support for storing chunks on separate storage backend from other metadata?

### ISSUE THREAD

**Issue by zedkyuu** [gilbertchen/duplicacy#537]
I did a test run of Duplicacy on OVH Public Cloud Archive and found that it expects to load the config and snapshot data from the storage backend. Cloud Archive has the concept of "freezing" where a file that is uploaded is unavailable for download except after the expiration of an "unfreeze" period initiated by the user. The idea being that the file could be stashed somewhere with high access latency, like tape. (I've seen unfreeze times as high as 10 hours; in this test, the config file that was created was immediately inaccessible and required a 4 hour unfreeze time.) Obviously, this would cause big problems when you try to backup.

OVH suggests using a "multibackend" feature with Duplicity, where the metadata gets stored on their Public Cloud Storage product (with immediate availability of files) while the data gets stored on Cloud Archive: https://docs.ovh.com/gb/en/storage/pca/duplicity/

Supporting this here would be really useful, I think. A secondary item would be to have Duplicacy wait for files to be unfrozen (I believe trying to access them starts the timer), but I haven't tested this out yet.

**Comment by gilbertchen** [comment]
This is almost impossible without redesigning the chunk structure.  There are two types of chunks, file chunks and metadata chunks.  And currently there is no way to separate them.

**Comment by zedkyuu** [comment]
Gotcha. The unfreezing thing is probably also a blocker to this working on OVH, too.
