### ISSUE TITLE
Backup empty folders?

### ISSUE THREAD

**Issue by noizo** [gilbertchen/duplicacy#54]
Hi.

I've come acros a problem.
While backing up with duplicacy to s3, PostgreSQL PG-DATA folder have sonme empty folders in it,
`pg_notify` for example.

I've noticed that duplicacy don't do anything with empty folders.
It just won't backup them.
In such scenario i'm unable to restore Postgres to working state.
```UTC [18091] FATAL:  could not open directory "pg_notify": No such file or directory```

Is there any trigger to enable empty folder backup, or it is a bug?

**Comment by noizo** [comment]
There's also possibility, that restore comand won't restore them

**Comment by noizo** [comment]
This is related to #28

**Comment by noizo** [comment]
As a workaround i had to `find . -type d -empty -execdir touch {}/.keep \;` in postgres PG-DATA directory

**Comment by gilbertchen** [comment]
With https://github.com/gilbertchen/duplicacy/commit/22ddc04698077fc297ae7408991405fc4aac0fad Duplicacy should now be able to restore empty directories.
