### ISSUE TITLE
Add ability to specify repository directory at backup time

### ISSUE THREAD

**Issue by zedkyuu** [gilbertchen/duplicacy#548]
This would permit backing up from ZFS snapshot directories. Right now, the only repository directory option I see is on init.

**Comment by TheBestPessimist** [comment]
not sure how zfs snapshot works but-> can't you make the snapshot in the same folder everytime?
And init the repository there?

**Comment by zedkyuu** [comment]
Unfortunately, it doesn't work that way. You can access arbitrary snapshots via the .zfs/snapshot directory, as described here: https://docs.oracle.com/cd/E19253-01/819-5461/gbiqe/index.html

You can also roll back to a single snapshot, which becomes visible in the main directory, but that doesn't fit the use case very well: use ZFS snapshots as a local kind of backup mechanism, and then have Duplicacy back up from a snapshot directory so that it's unaffected by subsequent writes.

**Comment by TheBestPessimist** [comment]
Then you can use a symlink to the latest zfs snapshot when you backup with duplicacy

**Comment by zedkyuu** [comment]
Initting duplicacy to point to the new snapshot directory seems to work, too. (I didn't try it in place, but tried it in a brand new directory, and it's fine.) It's a little wonky (I'd need to reinit for every single new backup) but it works.
