### ISSUE TITLE
Build from source missing Github repository 'duplicacy'

### ISSUE THREAD

**Issue by madcatsu** [gilbertchen/duplicacy#55]
**Steps to reproduce:**
1. From CLI, `git clone https://github.com/gilbertchen/duplicacy-cli.git ./`
2. From CLI, `go get`

**Error details:**
```
# cd .; git clone https://github.com/gilbertchen/duplicacy /Users/madcatsu/go/src/github.com/gilbertchen/duplicacy
Cloning into '/Users/madcatsu/go/src/github.com/gilbertchen/duplicacy'...
remote: Repository not found.
fatal: repository 'https://github.com/gilbertchen/duplicacy/' not found
package github.com/gilbertchen/duplicacy: exit status 128
```

**Expected result(s):**
`go get` should import required Go deps.

**Comment by gilbertchen** [comment]
The following command should work:
```
git clone https://github.com/gilbertchen/duplicacy-cli.git ~/go/src/github.com/gilbertchen/duplicacy
cd ~/go/src/github.com/gilbertchen/duplicacy/src
go get
go build main/duplicacy_main.go
```

Note that the github repository is named `duplicacy-cli` but when building Duplicacy it expects the directory name to be `duplicacy`

**Comment by madcatsu** [comment]
Thanks, I've tried this which results in the following message now:

`main/duplicacy_main.go:20:5: no buildable Go source files in /Users/madcatsu/go/src/github.com/gilbertchen/duplicacy`

**Comment by paullesiak** [comment]
Try the following change to `main/duplicacy_main.go`:

```
diff --git a/src/main/duplicacy_main.go b/src/main/duplicacy_main.go
index cc87143..1795598 100644
--- a/src/main/duplicacy_main.go
+++ b/src/main/duplicacy_main.go
@@ -17,7 +17,7 @@ import (
 
     "github.com/gilbertchen/cli"
 
-    "github.com/gilbertchen/duplicacy"
+    "github.com/gilbertchen/duplicacy/src"
 )
 
 const (
```

You'll probably need to clone git clone https://github.com/gilbertchen/cli.git into `~/go/src/github.com/gilbertchen` as well (I had to on OS X)

**Comment by madcatsu** [comment]
Thanks, working now. Are you planning on merging that into your next point release? I'm creating an Alpine Linux Docker container for Duplicacy CLI and it would be handy not to have to include a patch.

For some reason (perhaps a separate issue I don't completely comprehend yet), the Duplicacy binary fails to run on Alpine Linux natively (perhaps an issue with glibc vs musl), hence building from source.

**Comment by paullesiak** [comment]
@madcatsu I'm not the project owner -- I think @gilbertchen is better suited to answer (I just started playing with duplicacy today)

**Comment by madcatsu** [comment]
Sorry @paullesiak , I completely missed that the issue comment regarding the diff was yours :)

**Comment by gilbertchen** [comment]
@paullesiak thanks for the fix.  I've updated `src/main/duplicacy_main.go` in the repository.

**Comment by gilbertchen** [comment]
I've renamed the repository to `duplicacy` instead of `duplicacy-cli`.  The source files have also been moved to the top directory.  The build instructions have been updated accordingly:

```
git clone https://github.com/gilbertchen/duplicacy.git
cd duplicacy
go get ./...
go build main/duplicacy_main.go
```
