### ISSUE TITLE
Divide by Zero error on -add command

### ISSUE THREAD

**Issue by bifkit** [gilbertchen/duplicacy#551]
OS: Windows Server 2012
Version: 2.1.2

After successfully initializing a new repository on an external drive:

`PS D:\ServerFolders> duplicacy init -encrypt -storage-name usbdrive serverfolders h:\duplicacy_backup
Enter storage password for h:\duplicacy_backup:*************
Re-enter storage password:*************
D:\ServerFolders will be backed up to h:\duplicacy_backup with id serverfolders`

I then attempt to add remote storage:

`PS D:\ServerFolders> duplicacy add -encrypt -copy usbdrive dreamobjects serverfolders s3://us-east-1@uc-server-backup.objects-us-east-1.dream.io
Enter S3 Access Key ID:ThisIsNotForYou
Enter S3 Secret Access Key:ThisIsAlsoNotForYou
Enter storage password for s3://us-east-1@again-not-for-you.objects-us-east-1.dream.io:*************
Re-enter storage password:*************
Enter storage password for h:\duplicacy_backup:*************
runtime error: integer divide by zero
goroutine 1 [running]:
runtime/debug.Stack(0x26, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/gilbertchen/duplicacy/src.CatchLogException()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:183 +0x190
panic(0xc6e180, 0x12c9980)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/gilbertchen/duplicacy/src.(*S3Storage).UploadFile(0xc042255dc0, 0x0, 0xd86d53, 0x6, 0xc04236e000, 0x24a, 0x2b
2, 0x0, 0x40f)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_s3storage.go:228 +0x4c8
github.com/gilbertchen/duplicacy/src.UploadConfig(0xe654e0, 0xc042255dc0, 0xc04224c6e0, 0xc04202f970, 0xd, 0x4000, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_config.go:456 +0x465
github.com/gilbertchen/duplicacy/src.ConfigStorage(0xe654e0, 0xc042255dc0, 0x4000, 0x64, 0x400000, 0x1000000, 0x100000,
0xc04202f970, 0xd, 0xc0420c6370, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_config.go:499 +0x19b
main.configRepository(0xc042185d40, 0xc042185d00)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:438 +0x884
main.addStorage(0xc042185d40)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:218 +0x37
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.Command.Run(0xd84bb6, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0
xdb6f3b, 0x40, 0x0, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/command.go:160 +
0x7f1
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.(*App).Run(0xc042185b00, 0xc0420a6000, 0x8, 0x8, 0x0,
 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/app.go:179 +0x86
b
main.main()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2008 +0x5853`

I'm not sure what I'm doing wrong here. Do I need to run the initial backup once before I can add a copy command to that repository?

**Comment by gilbertchen** [comment]
This is a bug, but you can avoid this bug by specifying the storage url as `s3://region@amazon.com/bucket/path`.

**Comment by gilbertchen** [comment]
Fixed by https://github.com/gilbertchen/duplicacy/commit/43a5ffe0116b753180b76adb182e0fd9df5a722b

**Comment by bifkit** [comment]
I tried again with the latest version and got a new error:

`Failed to download the configuration file from the storage: InvalidParameter: 1 validation error(s) found. - minimum field size of 1, HeadObjectInput.Bucket.`

**Comment by bifkit** [comment]
Closing this issue, as the initial error has been resolved.
