### ISSUE TITLE
Feature Request: Add speed statistics to backup command

### ISSUE THREAD

**Issue by KnightAR** [gilbertchen/duplicacy#567]
This is somewhat related to #472 as I would like to add additional statistics to the backup command. Most commands that do I/O or Network based traffic has some way to display a verbose of the speed of the current command. For example:

Processing: 5% completed (5gb/100gb, 20MB/s, Net: 10MB/s), Est: 10 minutes

Something where I could see the % of the command, how fast the command is processing the data, and how fast data is being transferred to cloud or local disk. It would be nice to know this information to know how the backup is preforming (if its stalled or very slow you won't waste your time and know that you need to investigate).

I would make it a separate argument sort of like how the -stats command is.

**Comment by KnightAR** [comment]
Note: I know that -stats gives you speed and % but I don't need the command spam about if its skipping or uploading what part. Just a summary of the overall process.

**Comment by TheBestPessimist** [comment]
Please close this issue and create the feature request on the [Duplicacy Forum](https://forum.duplicacy.com/). We want to minimize github usage as much as possible.
