### ISSUE TITLE
Show duplicates?

### ISSUE THREAD

**Issue by OJFord** [gilbertchen/duplicacy#569]
I understand that duplicacy de-duplicates (even across repos) in the stored snapshots.

Within a single backup, is it possible to use this to show duplicate files?

**Comment by TheBestPessimist** [comment]
Please close this issue and create the feature request on the [Duplicacy Forum](https://forum.duplicacy.com/). We want to minimize github usage as much as possible.

**Comment by OJFord** [comment]
Well, to be honest I'm not keen to register on an nth forum, but sure, I'll close.
