### ISSUE TITLE
Box.com native API support

### ISSUE THREAD

**Issue by archon810** [gilbertchen/duplicacy#573]
https://github.com/gilbertchen/duplicacy/blob/master/README.md mentions Box.com via WebDAV and points to this page. However, Box.com deprecated WebDAV support in January of this year https://community.box.com/t5/Upload-and-Download-Files-and/WebDAV-with-Box/ta-p/310.

1. The README should be updated to remove Box.com references.
1. Can a proper Box.com API support be added? Box offers unlimited storage and transfers and is a very desirable storage endpoint.

Thanks.

**Comment by archon810** [comment]
For comparison/inspiration:

1. Box.com support in Duplicati https://forum.duplicati.com/t/setting-up-box-com/1154.
1. Box.com support in rclone: https://rclone.org/box/.

**Comment by TheBestPessimist** [comment]
Please close this issue and create the feature request on the [Duplicacy Forum](https://forum.duplicacy.com/). We want to minimize github usage as much as possible.

**Comment by archon810** [comment]
Yup, one was opened here https://forum.duplicacy.com/t/support-box-com-via-api-not-webdav/2502.

It's still very odd to me that the team wants to track bugs and feature requests on a forum and not a bug tracker integrated with the code. Seems backwards.

**Comment by tophee** [comment]
> It's still very odd to me that the team wants to track bugs and feature requests on a forum and not a bug tracker integrated with the code. Seems backwards.

The advantage is that everything is in one place and easily searchable.
