### ISSUE TITLE
Enhancement: move all source files to a folder for better UX on repo page

### ISSUE THREAD

**Issue by ivanstegic** [gilbertchen/duplicacy#59]
When you first visit the repo page, you're greeted with a very, very long list of files, and then what this project is about:

![repohome](https://user-images.githubusercontent.com/509217/26887373-7c92faae-4b6d-11e7-9507-a398338ea56a.png)

It would be so much better for someone visiting the repo home to see an explanation of the project right away. Just moving the code itself to another top level folder would fix this easily. Would you consider that please?

It would be great to see something like this instead:

![repohome2](https://user-images.githubusercontent.com/509217/26887526-d84729c4-4b6d-11e7-993e-f5334795ae24.png)

**Comment by gilbertchen** [comment]
Thanks for the suggest.  I moved all *.go file into a `src` directory.
