### ISSUE TITLE
Azure storage (GUI) - Next disabled

### ISSUE THREAD

**Issue by kierenj** [gilbertchen/duplicacy#60]
I've selected Azure storage, entered an account name, container name and access key - but the "Next" button is disabled.  I've tried swapping out account names and containers for URLs, but the button remains disabled.  Can you provide any guidance?

**Comment by gilbertchen** [comment]
It is a bug in the GUI version and I'll upload an update later today.

**Comment by gilbertchen** [comment]
This has been fixed in GUI version 2.0.1 (available on duplicacy.com)
