### ISSUE TITLE
[macOS] version numbers of 1.3 release broken

### ISSUE THREAD

**Issue by core-code** [gilbertchen/duplicacy#600]
i've downloaded version 1.3 but it claims to be version 1.2.1

the CFBundleVersion and CFBundleShortVersionString entries of this release have not been properly updated

<img width="452" alt="Screenshot 2020-06-11 at 17 35 46" src="https://user-images.githubusercontent.com/1261954/84406827-58f01180-ac0a-11ea-80e7-f3cf89ec9c59.png">
<img width="712" alt="Screenshot 2020-06-11 at 17 35 33" src="https://user-images.githubusercontent.com/1261954/84406832-5ab9d500-ac0a-11ea-8125-eab62ac32955.png">
<img width="264" alt="Screenshot 2020-06-11 at 17 35 28" src="https://user-images.githubusercontent.com/1261954/84406834-5ab9d500-ac0a-11ea-8f05-ffcc0dc05e2e.png">

**Comment by gilbertchen** [comment]
This was caused by a bug in the build script.

Version 1.3.1 should get it right:

https://acrosync.com/duplicacy-web/duplicacy_web_osx_x64_1.3.1.dmg

1.3.1 has no code changes other than that.

Thank you for including Duplicacy in Homebrew.

**Comment by core-code** [comment]
thanks for the quick fix here!
