### ISSUE TITLE
Local file storage, Windows: choosing root path on a drive causes error

### ISSUE THREAD

**Issue by kierenj** [gilbertchen/duplicacy#63]
Created a repository.  Selected Local disk.  Selected the root of my D:\ drive.

Received an error popup:
`ERROR Unrecognizable storage URL: D:"`

Click OK, left with dialog:

`Failed to retrieve storage information`

**Comment by gilbertchen** [comment]
This is another bug -- the minimum storage url should be 3 not greater than 4.

Any other folder should work.

**Comment by gilbertchen** [comment]
This is also fixed in the GUI version 2.0.1 (available on duplicacy.com).
