### ISSUE TITLE
init errors on S3-compatible service Wasabi

### ISSUE THREAD

**Issue by forkwhilefork** [gilbertchen/duplicacy#69]
I tried to init a storage repository on the S3-compatible storage service Wasabi. Here is what happened:

duplicacy init snapshot-name s3://s3.wasabisys.com/bucket-name
Enter S3 Access Key ID:<key>
Enter S3 Secret Access Key:<key>
Failed to configure the storage: AWS authentication requires a valid Date or x-amz-date header

I was able to connect successfully with a different client, so I know the keys are good (plus I get a different error if I use bogus keys). I took a packet capture of the working client authenticating (after turning TLS off) and I see the "x-amz-date" header being sent with the value of the current time in RFC1123 format. I tried taking a capture of Duplicacy authenticating, but I didn't see a way to turn off TLS, so I can't really see the traffic. I did look at the code at https://github.com/gilbertchen/amz/s3 and noticed that it adds a "Date" header rather than an "x-amz-date" header, so maybe that's it?

I am happy to assist in troubleshooting, I'm just not sure how to proceed. Thank you.

**Comment by gilbertchen** [comment]
The S3 storage backend is based on https://github.com/goamz/goamz.  The signing code is https://github.com/goamz/goamz/blob/master/aws/sign.go.  There is a `requestTime` function that adds the x-amz-data header if it doesn't exist.  I didn't find anything obviously wrong with a quick look, but will dive into that later.

**Comment by forkwhilefork** [comment]
Okay, thanks. I also spoke to Wasabi support and linked them this issue, so hopefully they will be involved in the troubleshooting as well.

**Comment by gilbertchen** [comment]
What I found out that is that the `AWS authentication requires a valid Date or x-amz-date header` error was returned when Duplicacy was trying to upload a config file.  However, there was another request before that which checked if this file existed, but this request failed with "403 Forbidden", so I doubt if it was an issue of the x-amz-date header.

I also tries to rename the Date header to  x-amz-date but still got the same error.

**Comment by gilbertchen** [comment]
https://github.com/goamz/goamz signs http requests [Amazon Signature Version 2](https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html), which states the Date or x-amz-date header should be in one of the formats defined in RFC RFC 2616, including the RFC 1123 format.  However, the Go implementation of the RFC 1123 date format incorrectly uses the suffix of 'UTC' instead of 'GMT' (see https://github.com/golang/go/issues/13781).  Changing 'UTC' to 'GMT' does seem to resolve the issue.

However, I'm not sure if that is the right fix.  Another S3 client library, https://github.com/minio/minio-go, seems to be more active and well-maintained.  Plus, it supports Amzon Signature Version4 by default and works with Wasabi without changes.  Maybe we should switch to that one instead.

**Comment by forkwhilefork** [comment]
Seems like switching might be a good idea. Other than depending on someone else's code, is there a downside to using the other library?

**Comment by gilbertchen** [comment]
The S3 storage backend has been rewritten using the [official S3 client library](https://github.com/aws/aws-sdk-go).  This should have been the first choice but I remember the reason to go with goamz was that goamz supported V2 signing which was required by Google Cloud Storage for the S3 compatibility mode.  Now that we have a new Google Cloud Storage backend based on the official Google client, it makes no sense to keep goamz (and V2 signing).

The new backend also worked with Wasabi without any issues in my tests.

**Comment by forkwhilefork** [comment]
Awesome! Thank you.

**Comment by gilbertchen** [comment]
Forgot to mention that with the new S3 backend you'll need to specify the region:
```
duplicacy_main init test s3://us-east-1@s3.wasabisys.com/duplicacy-test
```
