### ISSUE TITLE
Restoring directory structure as of a specific date

### ISSUE THREAD

**Issue by bealsaj** [gilbertchen/duplicacy#72]
Hi there.  I have been testing the product using the CLI.  I have a use case where I want to restore a repository's directory structure (really a recursive sub-directory of the repository) to what it looks like at a specific date, to a separate directory.  Assuming we are doing a nightly backup, additions and deletions to files and folders in the directory will be happening over many snapshot revisions.

From what I can tell thus far, I can restore a specific revision with the -r option, however that only seems to restore those files that were created (or added) during that backup, not all of the files that were present (current state) of the directory structure for a specific point in time.   I don't see any option from within the CLI to restore to a different directory.  Using the GUI version, all files appear in a revision list for a given repository, but this does not seem to be the case with the CLI.  How would I best go about doing this?

**Comment by gilbertchen** [comment]
When you specify a revision to restore, Duplicacy should be able to restore all files to the state when the backup was taken.  If that doesn't work it must be a bug.

To restore files to a different directory, you can initialize that directory as another repository, but with the same repository id and the same storage url. You'll then be able to run the restore command as if you were in the same repository.

**Comment by bealsaj** [comment]
Thanks - For some reason there were incomplete revisions in the different directory I had.  Once I initialized a new directory everything worked as expected.
