### ISSUE TITLE
copy does not take previous revisions into account

### ISSUE THREAD

**Issue by untoreh** [gilbertchen/duplicacy#88]
When copying a snapshot with a specified revision all the chunks get copied always, instead of copying the actual diff of the revision.

**Comment by gilbertchen** [comment]
Duplicacy assumes that you may want to copy selected revisions to the destination storage, not all of them, so it will just blindly copy all referenced chunks to the destination.  However, for each chunk it does check if the chunk already exists in the destination and only actually copies it if it doesn't.

**Comment by untoreh** [comment]
Ok, so I just misread the output
