### ISSUE TITLE
Backup multiple folders from partition

### ISSUE THREAD

**Issue by tehmaestro** [gilbertchen/duplicacy#91]
Hi, is there any way I can backup multiple folders located at the root of my partition.
 For example, let's say I have the following folders: D:\test1\ , D:\test2\ , D:\test3\ . I assumed that the repository, in this case, should be the partition, D: , and by using include regex I would be able to only backup the desired folders.

However, when I select an entire partition as my repository, nothing is being backed up, regex or no regex.
Is this not supported currently? Thank you.

**Comment by gilbertchen** [comment]
It should be supported, but the include/exclude patterns can't be regex -- only * and ?, and the paths should be relative to the repository.

In your case I think the patterns should be:
```
+test1/*
+test2/*
+test3/*
-*
```

**Comment by tehmaestro** [comment]
Ok, it works. I was missing the ```*``` at the end of the folders. Sorry.
