### ISSUE TITLE
Symlink/Permissions issue

### ISSUE THREAD

**Issue by tehmaestro** [gilbertchen/duplicacy#94]
Hi. Trying to execute a restore and got the following error:
```
  Can't create symlink myfolder/folder/folder: symlink C:\Users\folder . A required privilege is not held by the client.
```
 I would like to mention that I was restoring to a different computer than the one from which I had created the backup.

**Comment by gilbertchen** [comment]
To create symlinks you'll need to run as administrator -- this is one of the weird things about Windows!

**Comment by tehmaestro** [comment]
That seems to fix it. Thanks!
