### ISSUE TITLE
Documentation : complete the "Include/Exclude Patterns" section

### ISSUE THREAD

**Issue by vibl** [gilbertchen/duplicacy#96]
The "Include/Exclude Patterns" section of the user guide is still incomplete.

Does the pattern match the whole path or part of it?

What is the "normal meaning" of `*` and `?` ? Do they match the directory separator `/` ? If so, it is not the same meaning as Rsync or Bash, for example. If not, how do I match multiple directory levels?

Specifically, I need to exclude these patterns:
```
**/.cache/**
**/Trash/**
**/.Trash/**
**/Cache/**
**/tmp/**
**/Temp/**
```

Where `**` matches multiple directory levels. Is it possible in Duplicacy?

From what I read in the source code, the `matchPattern()` function does not seem to take the `/` separator into account. Does that mean that the pattern `*tmp*` means "any path that contains the string 'tmp' anywhere in it"?

I guess I could find out the answers to these questions by trials and errors but that would not benefit the other users.

And what's more, I feel uneasy about using a backup utility where the filtering options are not clear: mistakes in filters are common ways to either not backup important data (and realize it when you need the backup and it's too late) or backup data you didn't need (and realize it after you have paid extra fees to the cloud provider). To be honest, I'm wondering if other important parts of the backup and recovery process I'm not aware of have been neglected as well (this feedback might be useful to you if you want to build a business around Duplicacy).

**Comment by vibl** [comment]
I've been experimenting with the filtering patterns and their behavior is different from all the tools I've used yet:
`*` matches any character, including the separator `/`. So it's the equivalent to the `.*` regex pattern.

It would be better if this behavior were mentioned in the user guide, instead of `with their normal meaning.` 

For the moment, I seem to be able to do the filtering I need. We'll see on the long run if there are some limitations.

For anyone interested in testing, I recommend you create a directory with some dummy files and directories with interesting filenames, and then use the command below repeatedly to try out different patterns in a file called `duplicacy_filters`:
```
/bin/rm -rf .duplicacy ; /bin/rm -rf /tmp/duplicacy_store/* ; mkdir -p /tmp/duplicacy_store ; duplicacy init tmp /tmp/duplicacy_store && cp duplicacy_filters .duplicacy/filters && duplicacy backup -stats
```

**Comment by gilbertchen** [comment]
I updated the doc to emphasize that `*` matches any character including `/`.  This may have limitations but my plan is to add full regex support in the future.

**Comment by vibl** [comment]
Cool :-) Thank you for your work. This application has a great future!

**Comment by nikjft** [comment]
Still confused @gilbertchen on how the exclude/include patterns work. Should these be absolute patterns? Relative from the top of the repository? Example

I'm backing up my home folder (/users/nikjft/)
I want to exclude Downloads, Movies and Music, do I have this right?

> -Downloads/*
-Movies/*
-Music/*

Or do I want:

> -/Users/nikjft/Downloads/*
-/Users/nikjft/Music/*
-/Users/nikjft/Movies/*

**Comment by gilbertchen** [comment]
It should be relative to the top of the repository.  So
> -Downloads/*
-Movies/*
-Music/*

is right.

**Comment by jt70471** [comment]
I believe this can be closed because the regular expression support via PR #187 has now been merged.
